### ISSUE TITLE
[C++] Lookup for function call syntax to implicitly declared copy-assignement fails in template classes

### ISSUE THREAD

**Issue by TheCalligrapher** [llvm/llvm-project#110009]
For the following code 

```
template <typename = int> struct C
{
  C &foo(const C &c) { return operator =(c); }
};
 
int main()
{
  C<> c;
  c.foo(c);
}
```

Clang will generate a diagnostic 

```
error: explicit qualification required to use member 'operator=' from dependent base class
    3 |   C &foo(const C &c) { return operator =(c); }
      |                
```

The code appears to be perfectly valid, yet it is rejected by Clang. The above diagnostic mentions "base class", although obviously there's no inheritance of any kind in this code.

Prepending the call to copy-assigment with `this->`

`  C &foo(const C &c) { return this->operator =(c); }`

solves the problem (which incidentally is how one solves the "lookup in a dependent base class" issues).

Also, switching from functional notation to operator-in-expression notation makes the error to go away

`  C &foo(const C &c) { return *this = c; }`

Trying to qualify the call

`  C &foo(const C &c) { return C::operator =(c); }`

results in 

```
error: no member named 'operator=' in 'C<type-parameter-0-0>'
    3 |   C &foo(const C &c) { return C::operator =(c); }
      |        
```

With non-template classes the issue does not manifest itself.

The diagnostic implies that when functional notation is used to refer to the implicitly declared copy-assignment operator in a template class (from within a member definition), name lookup fails for some unknown reason, and the compiler immediately jumps to conclusion that it is a "lookup in a dependent base class" issue. It is obviously not.

Anyway, is this a known issue? Or am I missing some peculiarity of name lookup in template classes?

**Comment by zygoloid** [comment]
This is a peculiarity of name lookup in class templates. See https://eel.is/c++draft/temp.dep.general#2.5

The problem is that we don't know whether the class has a member named `operator=` in general until instantiation. So we don't know what the result of unqualified lookup should be.

But the diagnostic is definitely bad and we should fix that!

**Comment by TheCalligrapher** [comment]
The linked wording defines a call to `operator =` as a _dependent call_, but I still don't see where it says that it is permissible to fail to resolve this call in the above example. Dependent names are looked up in accordance with a different set of rules (e.g. "two-phase lookup" and other informal monikers), but they are still supposed to be looked up. Why does this lookup for unqualified `operator =` fail in this case? Where is that allowed to fail in the spec?

**Comment by zygoloid** [comment]
Yeah, I agree that the standard seems to suggest that this is supposed to work, but it's not completely clear how.

The lookup is being postponed -- Clang accepts the template definition, and only rejects during the instantiation. During instantiation, ADL is performed (and finds nothing useful), but unqualified lookup is only ever performed in the template definition context, and in the template definition context, no `operator=` can be found.

Probably the best thing we could do would be, if we try to instantiate an `UnqualifiedLookupExpr` naming `operator=`, perform class member lookup into the type of `*this`.

**Comment by TheCalligrapher** [comment]
Also, it is not clear to me what you mean by "the problem is that we don't know whether the class has a member named `operator=` in general until instantiation". 

A class **always** has such a member. No way around it. Each and every class always unconditionally includes a declaration of a copy assignment operator. If the user does not declare one explicitly, the compiler is required to declare one implicitly: https://eel.is/c++draft/class.copy.assign#2

The copy assignment might be _defined_ as _deleted_, but that bears no relevance to the matter at hand, since we are talking exclusively about _name lookup_. _Name lookup_ is not affected by definitions.

If I'm not missing anything, the only name-lookup-related thing about copy assignment operator that depends on the template arguments is the exact argument type: it is either `X& X::operator=(const X&)` or `X& X::operator=(X&)`. This "`const` or no `const`" dilemma is why we might have to postpone the lookup to the second phase. 

(BTW, the wording you linked is ultra-new. Even something as fresh as C++20 does not have it. Is it still supposed to be present in older standards in some other form? And if not, why has it appeared only now? Is there a proposal or DR which triggered this change?)
