### ISSUE TITLE
[lldb-dap] Invalid variable reference ids

### ISSUE THREAD

**Issue by Anthony-Eid** [llvm/llvm-project#119784]
# Summary

It seems like lldb-dap reuses variable reference numbers across scopes during the same suspended state. For example, if a client sends two scope requests with different frame_ids, lldb-dap uses the same variable reference numbers for different variables across scopes. 

This goes against the DAP specifications in regard to the lifetime of object references and variableReference's definition, because references become invalid before the program exits its suspended state thus making `variables` request respond with invalid data. 

```javascript
   /**
   * If `variablesReference` is > 0, the variable is structured and its children
   * can be retrieved by passing `variablesReference` to the `variables` request
   * as long as execution remains suspended. See 'Lifetime of Object References'
   * in the Overview section for details.
   */
  variablesReference: number;
```

## Example 

```json
{
  "type": "request",
  "seq": 11,
  "command": "scopes",
  "arguments": {
    "frameId": 524289
  }
}
{
  "type": "request",
  "seq": 10,
  "command": "scopes",
  "arguments": {
    "frameId": 524290
  }
}
{
  "body": {
    "scopes": [
      {
        "expensive": false,
        "name": "Locals",
        "namedVariables": 1,
        "presentationHint": "locals",
        "variablesReference": 1
      },
      {
        "expensive": false,
        "name": "Globals",
        "namedVariables": 0,
        "variablesReference": 2
      },
      {
        "expensive": false,
        "name": "Registers",
        "namedVariables": 3,
        "presentationHint": "registers",
        "variablesReference": 3
      }
    ]
  },
  "command": "scopes",
  "request_seq": 9,
  "seq": 0,
  "success": true,
  "type": "response"
},
{
  "body": {
    "scopes": [
      {
        "expensive": false,
        "name": "Locals",
        "namedVariables": 0,
        "presentationHint": "locals",
        "variablesReference": 1
      },
      {
        "expensive": false,
        "name": "Globals",
        "namedVariables": 0,
        "variablesReference": 2
      },
      {
        "expensive": false,
        "name": "Registers",
        "namedVariables": 3,
        "presentationHint": "registers",
        "variablesReference": 3
      }
    ]
  },
  "command": "scopes",
  "request_seq": 12,
  "seq": 0,
  "success": true,
  "type": "response"
}
```

## Additional Information 

I’m one of the people working on creating a client-side debug adapter implementation for the Zed code editor and noticed this bug occurring when requesting variable information. This is preventing Zed from getting valid variable information during debugging. I used the below simple program to get the above log message

While we could fix the order of our requests to mimic VSCode or Neo Vim to fix this issue, it wouldn't solve this bug during Zed's collaborative debugging sessions where multiple users could be looking at different scopes at the same time. So changing the order of Zed's requests isn't an adequate solution.

compiled with `gcc -g3 -o main.out`

```c
int main() {

    int x = 1;

    return x; // Breakpoint on this line to trigger a stop event
}
```

I installed lldb-dap through Pacman on Arch Linux and am using lldb version 18.1.18. 

## Log files
[vscode-lldb-dap-logs.txt](https://github.com/user-attachments/files/18118198/vscode-lldb-dap-logs.txt)
[zed-lldb-dap-logs.txt](https://github.com/user-attachments/files/18118199/zed-lldb-dap-logs.txt)

Please let me know if there's additional information I could provide to help fix this. I'll also be willing to collaborate with someone to come up with a patch, but I don't have any exposure to the code base so I would really appreciate help.

**Comment by DavidSpickett** [comment]
@clayborg / @walter-erquinigo could you help @Anthony-Eid get started on this issue?

Anthony please tell us how far you've gone so far.

**Comment by walter-erquinigo** [comment]
Thank you for working on this!

I think that the minimal change that you could do, that can potentially be enough, is to make these constants https://github.com/llvm/llvm-project/blob/main/lldb/tools/lldb-dap/DAP.h#L43 actual variables. We also have the variable `next_permanent_var_ref` that is simply a counter to generate variable references. You could unify all references into `next_permanent_var_ref` and it might just work.

**Comment by Anthony-Eid** [comment]
Thank you for the advice on tackling this issue. So far, I've only just started looking into solving this and got my first build working. I'm having some trouble setting up clangd, but overall, it hasn't been an issue.

I just wanted to give you guys a heads up that I'm still planning on making a PR in the near future, but I want to finish some other features first with the Zed debugger. I should be able to start working on this within two weeks.

**Comment by walter-erquinigo** [comment]
Beautiful. Looking forward to it!

**Comment by Anthony-Eid** [comment]
Hey I was hoping I could get some guidance on another potential bug I found.

In lldb/tools/lldb-dap/lldb-dap.cpp::request_scopes() function there's this comment

  > As the user selects different stack frames in the GUI, a "scopes" request
  > will be sent to the DAP. This is the only way we know that the user has
  > selected a frame in a thread. There are no other notifications that are
  > sent and VS code doesn't allow multiple frames to show variables
  > concurrently. If we select the thread and frame as the "scopes" requests
  > are sent, this allows users to type commands in the debugger console
  > with a backtick character to run lldb commands and these lldb commands
  > will now have the right context selected as they are run. If the user
  > types "`bt" into the debugger console and we had another thread selected
  > in the LLDB library, we would show the wrong thing to the user. If the
  > users switches threads with a lldb command like "`thread select 14", the
  > GUI will not update as there are no "event" notification packets that
  > allow us to change the currently selected thread or frame in the GUI that
  > I am aware of.


This seems to be because the console evaluation and completion requests both can include a frame_id as an argument. Wouldn't it be better to use that frame_id as the context to evaluate console requests, then fall back to the last scope request a user sent if frame_id doesn't exist? 

Also, resetting the variables to a singular stack frame is causing problems when a client sends a variables request for a variable that is in another stack frame.

**Comment by walter-erquinigo** [comment]
@Anthony-Eid , it's possible that the DA protocol didn't have the frameId field everywhere when we implemented lldb-dap, but if what you say is true, we should simply use the frameId field as context everywhere, instead of the ad hoc change we did. Can you try to do that? Because otherwise you might see issues in your editor

**Comment by Anthony-Eid** [comment]
Hi @walter-erquinigo,

I'm close to finishing up this PR, but I'm having some trouble getting the set variable request to work properly and pass the unit tests. Would you be able to take a look at my draft when you have some time? I'd really appreciate any guidance you can offer, especially since I'm still getting familiar with the lldb-dap codebase and LLVM.

Thanks so much!

**Comment by Anthony-Eid** [comment]
Hi @walter-erquinigo I just wanted to bump my message, I would really appreciate any help you can provide. Thanks

**Comment by da-viper** [comment]
> I'm having some trouble getting the set variable request to work properly and pass the unit tests.


There was an issue with the setVariable request not sending the correct response body see #130773

**Comment by Anthony-Eid** [comment]
@da-viper  Thank you for letting me know. I'll merge main into my PR and see if that fixes my issues

**Comment by da-viper** [comment]
@Anthony-Eid  did it fix the issue ?

**Comment by Anthony-Eid** [comment]
@da-viper I spent a couple hours on it today and just finished resolving the merge conflicts when I updated my branch. My PR is in a broken state now but I'll be able to fix it pretty soon. I'll update you when I finish getting my PR working again

**Comment by da-viper** [comment]
> Edit: The PR should be working now! If all the tests pass I can add a simple regression test to prevent this from happening again in the future. Please let me know if there's anything else I would need to do to get this merged

It seem the pr includes temp files that is not related to the PR.

**Comment by Anthony-Eid** [comment]
@da-viper I can fix that later today. I'm having some trouble getting all the tests passing in the test suite, mainly some of the API ones. Would you or anyone you know be willing to pair with me on this? I would love to get it merged soon.

**Comment by da-viper** [comment]
I could look at why the test is failing once the unrelated files are removed, because it confusing to separate what is useful and what is not
