### ISSUE TITLE
Unable to rename temporary object file to output file (randomly occurs)

### ISSUE THREAD

**Issue by cpunion** [llvm/llvm-project#127556]
Same errors in other cases has similar situation: call clang command line in a program that linked LLVM.

System info:

```
Operating System
  Ubuntu
  24.04.1
  LTS
Runner Image
  Image: ubuntu-24.04
  Version: 20250209.1.0
```

Clang version:

```
Ubuntu clang version 18.1.8 (++20240731025043+3b5b5c1ec4a3-1~exp1~20240731145144.92)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/lib/llvm-18/bin
```

```
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /usr/lib/llvm-18/bin/clang -cc1 -triple x86_64-pc-linux-gnu -emit-obj -mrelax-all -dumpdir /tmp/llgo-1969456538- -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name a14d451a0ef048c2fae6a398d57a95eb2a137fcef4784211d0153de717c15890-d.ll -mrelocation-model pic -pic-level 2 -pic-is-pie -mframe-pointer=all -fmath-errno -ffp-contract=on -fno-rounding-math -mconstructor-aliases -funwind-tables=2 -target-cpu x86-64 -tune-cpu generic -debugger-tuning=gdb -fdebug-compilation-dir=/home/runner/work/llgo/llgo/compiler/internal/build -ffunction-sections -fdata-sections -fcoverage-compilation-dir=/home/runner/work/llgo/llgo/compiler/internal/build -resource-dir /usr/lib/llvm-18/lib/clang/18 -Wno-override-module -ferror-limit 19 -fgnuc-version=4.2.1 -fskip-odr-check-in-gmf -dwarf-debug-flags "/usr/lib/llvm-18/bin/clang -o /tmp/llgo-1969456538 -Wl,--error-limit=0 -fuse-ld=lld -Wno-override-module -rpath $ORIGIN -rpath $ORIGIN/../lib -fdata-sections -ffunction-sections -Xlinker --gc-sections -lm -latomic -lpthread /home/runner/.cache/go-build/ab/ab402c00678347d41017afe19faeec6cc04c000a1dca2cc08bd5239495ed2e69-d.ll /home/runner/.cache/go-build/1b/1b42b3650e199718b1c652f14efdd243b972acfb7f0e2f06528dd3dca7a8e686-d.ll /home/runner/.cache/go-build/64/64f97edd7e682b75e55a7c6880d06640730b5339d38e0db9d8ddd680d11b8903-d.ll /home/runner/.cache/go-build/5f/5f10ffd0aa11c4083063610d19e96c549dbe94d4ad8cff788fa727766def3bb5-d.ll /home/runner/.cache/go-build/0f/0f55a67b9c0cacf36e0cbd80facf0174eaeb4c6299b6f5db680156739127a155-d.ll /home/runner/.cache/go-build/db/db9fdac6cfe231cb9459d2f61b02aadf7fe7fd3ff729278090708754ff52738b-d-cgo-2102847250.c.ll /home/runner/.cache/go-build/db/db9fdac6cfe231cb9459d2f61b02aadf7fe7fd3ff729278090708754ff52738b-d.ll /home/runner/.cache/go-build/ae/aec24dc194582dc65ba9c5251344c1dd553a39c932a4915d8c4cb48b3a86efc9-d.ll /home/runner/.cache/go-build/4b/4b0d236dd5d12dab5177be2870586db64def33e5c5443c49826b0be81b6ec313-d.ll /home/runner/.cache/go-build/92/92f78335fc9d841b52fc885424618aa4bdc8e0a6da6e58b176b07e992a78f9a5-d.ll /home/runner/.cache/go-build/48/48048b5d8a233f605ada6042fef42eccb0af9b2cb66b731ae95cb1fbe660318b-d.ll /home/runner/.cache/go-build/b6/b69261fbecc76c8655fd031979cca9ff0cc7ceba9a4b4d303106113cb6c0265d-d.ll /home/runner/.cache/go-build/07/070373f17cd62c232dcffa775ec3bca8cf2a619078aad68248f9b4d3d1612a3d-d.ll /home/runner/.cache/go-build/32/32f793f0d17ef2a31c588e5571e20ce42bd89f2d4ef62c878a04e9aa9dd74e7d-d.ll /home/runner/.cache/go-build/43/43939aa9a6554a3844344b685bfe10bac036c4c4bb21ab21e2207cef634b4762-d.ll /home/runner/.cache/go-build/49/49d4ef57ac347cb762bb2f9db061dce9dc7d9ee96563c69b0372112d8dce561f-d.ll /home/runner/.cache/go-build/a7/a70c9548f4459501f9a5f46788e1ddde3a9ea10fe98661bed202e77a9838bea8-d.ll /home/runner/.cache/go-build/cd/cd68fc4ce9c89ae65083a32915341dcb329eee2c9c7d70e3467a264ee5fccd4c-d.ll /home/runner/.cache/go-build/a6/a616d40572ce319356f53ec7fe6edc41b16cc615cdede0f36bb8c6bb893046db-d.ll /home/runner/.cache/go-build/68/682b091e26346187944426e694ef4c9c09ff710033842706b6b97a85b0d37d87-d.ll /home/runner/.cache/go-build/c1/c1f4c32ee24a721157dd9f79f48a2551c1c888441184c7d439d99dfea6d5ccce-d.ll /home/runner/.cache/go-build/eb/eb995a1991158940fece95a98ab8304eedca02e6dfcf3a49fe54bba15b519043-d.ll /home/runner/.cache/go-build/d7/d72c4c96ff3a6b3d26ba6fbc59c81d1ef3d778e4a922064c16a6f903876830d9-d.ll /home/runner/.cache/go-build/80/80cc3857eff569162d6818c4c63f180ef05bd385320b7a6701fd0efa8fb44bb3-d.ll /home/runner/.cache/go-build/bd/bdd8ee70c8e99eb374fa82d50e1d8fcd73ff062d2cfbfe8401b79ac14011549c-d.ll /home/runner/.cache/go-build/e3/e316265b8a155d7f020e0a4f832ce57d7544d7c00d44ef92358861ebc81fb65c-d-cgo-1069619004.c.ll /home/runner/.cache/go-build/e3/e316265b8a155d7f020e0a4f832ce57d7544d7c00d44ef92358861ebc81fb65c-d.ll /home/runner/.cache/go-build/e5/e599536f06d8435bec78f8276ce17553f7d6c63af7d55c71dd651e41d176d1dc-d.ll /home/runner/.cache/go-build/d1/d1eb9b0800493004e909ddab413a03b2ad05ecb842afc0bf6899f72ae39505ad-d.ll /home/runner/.cache/go-build/a9/a93a71ef776cc21d67dd0ac70966fcea3b0c9deb63124ec8ba962c15b52da69d-d.ll /home/runner/.cache/go-build/43/43e2ecf893dfcb9a1a679e938c0daa0f6db03ec2fe185b164d5f1411a4b978bc-d.ll /home/runner/.cache/go-build/f1/f1b8478f36fe039167806f36e168035fc5114b541e2342e54a6b2676df24b048-d.ll /home/runner/.cache/go-build/cd/cda023afb79c57d05dfc870123ba6684db84a5b6f91602d1c6834ddffce37bdb-d.ll /home/runner/.cache/go-build/0c/0c77fcf004c73676caf1fe490569d07edcf7ab24c55098dad827f3fac10ac4ff-d.ll /home/runner/.cache/go-build/8b/8b34baaab82c5dfbf80226b5af0bcc6739ea1f1ac946e4e6d4c5607bd95c3096-d.ll /home/runner/.cache/go-build/82/8272361b0f71864735810c14cfe18bfdef4a16d5d2bd57cf7799800ac318ea17-d.ll /home/runner/.cache/go-build/d6/d68c491629d59ecc9492770ae1e1fb9ed4d0750449ce6ae80e3c72e7807c7311-d.ll /home/runner/.cache/go-build/3d/3dbf76b130dd490e6e871f87305c2e2d10c287fd48e0469f9e4b85be75c32076-d.ll /home/runner/.cache/go-build/12/12cfe56c7022ff4a92518f474d41661c472aa62519ed6c97037e1c2be082a5dd-d.ll /home/runner/.cache/go-build/a6/a6974d9da51640f6bb6f8d8a9825ce6ef772d28ee9ef45a0232b13a08cae7e38-d.ll /home/runner/.cache/go-build/ce/ce6ecb331d68fd6b47d922f15bd798c378597d03756b0630c5e8da643fd46f4a-d.ll /home/runner/.cache/go-build/8c/8c707b0e2df0f4b1d1242e55c9811990b6131a542b008a2b32d26c5451c8c1c7-d.ll /home/runner/.cache/go-build/5f/5f1c4d076040bb06b9dad68ff3f59de9c23869c5712e4b7701c904063887e475-d.ll /home/runner/.cache/go-build/a1/a14d451a0ef048c2fae6a398d57a95eb2a137fcef4784211d0153de717c15890-d.ll /home/runner/.cache/go-build/ac/ac51e118b16853ff665c61b91344215e61c9b1915f9f9ffb44f24eb67a459975-d.ll /home/runner/.cache/go-build/54/54561bc26cf4695de22365c70e46a836fcff0795b7dcc11f6445265f024b6a06-d.ll /home/runner/.cache/go-build/52/52ab4116ca77381e3a10b2fb49a764d5166a1edfd2de9468bd1ee72e56dce3a7-d.ll /home/runner/.cache/go-build/f1/f194e993653b3a06579d7208bb28e7f702c69cb5cd215fd9f03020f47b3884f2-d.ll /home/runner/.cache/go-build/9e/9e90f1ebc1d175767078574990d213ad2cd5df36667ed6d4a48fa7aa6344f0f8-d.ll /home/runner/.cache/go-build/ef/ef74b008a225f4ac313c96619f580b501b928644db33541ea238f0fee3555013-d.ll /home/runner/.cache/go-build/f0/f0ec0f11984b179c0bd4452d6b6c290d0867b611c25d910a68917903a1facdc7-d.ll /home/runner/.cache/go-build/36/3670495a9a69b3bad647df71c37a95f3cecff10a1702ab4603a427dc723f95e7-d.ll /home/runner/.cache/go-build/de/de07cae949b135bcef159b291c3908ad0ccf572a70023430e9ebfd83074a0221-d.ll /home/runner/.cache/go-build/9b/9bdccb11f1bc45e4cf749b9361d053a2ff54722975fbdb12059b720145c3b9eb-d.ll /home/runner/.cache/go-build/21/21a4050ad9b35abce51ebd26f05424c1adf769a527234d8f6590897640caaa45-d.ll /home/runner/.cache/go-build/b5/b5596f3af64bfc90d52558ef1b1ccfdf943442a9fc0bddb5f9e3d948c2bb6442-d.ll /home/runner/.cache/go-build/fe/fe9c138495215c5aefa06280e439efd8933c7c8ce5002286517381857938c996-dfcntl_unix.c.ll /home/runner/.cache/go-build/5a/5aa326f063b6712cf23a6a808df32700ebd86189c90e228d0cd1aec0f29890cf-d.ll /home/runner/.cache/go-build/05/0563198ecaae270829a0d3d53017f7223bb73a275b9d63816c71e47a48e7c95d-d.ll /home/runner/.cache/go-build/39/3942740f5176a980f4dc3488b385c3f11892d6eb379e79b857ab57faf4b816d6-d.ll /home/runner/.cache/go-build/3b/3bf2d44f6ed5b6a512af55f3f6030031a5aed664e26322350dd86b4ff490fc81-d.ll /home/runner/.cache/go-build/9c/9c13618c7321cc90f6aba5b46666c063eb82581b9338b1d7d9f843b8eea881b7-d.ll /home/runner/.cache/go-build/ac/ac006910705bb1d3c9d35c5df9ec9462b62047e41c3abc2f4e4886cc794632c6-d.ll /home/runner/.cache/go-build/25/25bcb3a941363bd9b2fc34319956c9eb9e719c487d8caaa7a54ca1950426afad-d.ll /home/runner/.cache/go-build/6d/6dbc215d17f21b3685bf9526b2b937f0f33667295405ed541456ec203cd0ce43-d.ll /home/runner/.cache/go-build/54/54de10a38821844884d59bb60b62f284f15c2b44f597fc94b53a78384fb1c4c9-d.ll /home/runner/.cache/go-build/1e/1ef466eeaf0f45a1b9555cd9f96cddfdab2ed8ad9f5fcd22466b65f35d1d6889-d.ll /home/runner/.cache/go-build/dc/dc96091214f8e428e57c927fabf1a3aed57e8f45c24ae2530787a69f056daec1-d.ll /home/runner/.cache/go-build/2e/2ee86b2c3521a19345dde40b48420cb780d5a03b692f519140b18fafcf478d2a-d.ll /home/runner/.cache/go-build/74/74ab8bba36ecd71870f419cff6cd122636a5dc23e9371ea26215f68fcaf5c867-d.ll /home/runner/.cache/go-build/28/28e6a8a7181909d83efad5dba94bbb7bd63e7607f71d3a7471aafe036922a71d-d.ll /home/runner/.cache/go-build/25/252a574968e8ea435604006ed06303c78c1668353b553765857feca3bd5b44e3-d.ll /home/runner/.cache/go-build/a5/a5bd0a7ba904c0fe0d582d484f500637df652946a80c32d018a6f2478d268129-d.ll /home/runner/.cache/go-build/4c/4c425d73f9f85642a4450babe94e57fde350e31bd003c28782e886d77ac69301-d.ll /home/runner/.cache/go-build/22/22515730397f13b9fdf2eb6c648e3dbb7edaa664d85a5628a2fc50d556c8ad4f-d.ll /home/runner/.cache/go-build/56/56c43a536158ac2b937aadbaab5483b8922daeca91ace2ba5e2820e60cc95904-d.ll /home/runner/.cache/go-build/0d/0dc9c813089c3745a2700544a6373d4813870cf5a640252c17bced7879d4bcdb-d.ll /home/runner/.cache/go-build/0b/0b613ae850e26bcada85ddd76a9d6fdddcebc83e91dca8c9a4e970d70cb08a52-d.ll /home/runner/.cache/go-build/92/9246a4c846a76abd5acc261648aa2f424d7645f201d477399a330f30231ba3b8-d.ll /home/runner/.cache/go-build/a0/a0679993683aa2e0d194118d0ceadf72aaffcaed98441a5d952fe5e248fb2f81-d.ll /home/runner/.cache/go-build/0e/0e5cb2e1d8452813a7cba6b35ad62145822b2d9f6c187e3e25076fe30b6679d6-d.ll /home/runner/.cache/go-build/6a/6a8bc56fd7199bae5e61b3f007dd5e76e951bab93289bf727b1943b4bad5b930-d.ll /home/runner/.cache/go-build/57/5708a8f2d27d28298f4a9245ed4d742ab450830832434944a4f881dfa61cb414-d.ll /home/runner/.cache/go-build/0a/0a85dd324a97c457ed727ff37e6732257afb03636338f8380f84fe50c82da4d3-d.ll /home/runner/.cache/go-build/99/99196507412aa4c19a7d8c7d71496949033cd87fd6b5c6e3bdeaace5e4654b5b-d.ll /home/runner/.cache/go-build/61/6119403ec4ba070b07530e8df7537e29324447b86d06d3574be0e42ededba171-d.ll /home/runner/.cache/go-build/bb/bb8d7c9f7d070cf96bb0751aec454bf250e9c07e69c3f23157ab8dfe667a4da4-d.ll /home/runner/.cache/go-build/8b/8b4446c4ce5d3bcdbf3d0a606c217879e095410d5734322076344bc67c6cfd61-d.ll /home/runner/.cache/go-build/2f/2f337284ad1d457464494bc2593edaea2ee106b70ccedd6fc5da1abb7a3902d2-d.ll /home/runner/.cache/go-build/c8/c8a0634449758071fe65a806f619c0908b3a6f1a76109137f2c00aeb964b1b73-d.ll /home/runner/.cache/go-build/ba/ba5f0ab01d269502d9bbc5de200c3d114cbab039a24704ef5c2109ccb322bbc9-d.ll /home/runner/.cache/go-build/c6/c6d08332fc5958b3e8b8c24abaec5ae924f670322a7e7dfea42b590937abd27d-d.ll /home/runner/.cache/go-build/1a/1aad0a045f9b571208377c5841980b715f1e8ab060a1d087e1782c833f8c0e77-d.ll /home/runner/.cache/go-build/63/63bd038e517f822530733354febfed0c4029adacab2891d4d44b299f3a72c81f-d.ll /home/runner/.cache/go-build/9a/9aeab1524f31a4e232bb52bdae555a6bd6a7ca640118224dd69512dce5801b64-d.ll /home/runner/.cache/go-build/8a/8a3d6e2ca3acfcd0c1d199b19afff6f21e4621a88e84f8e7d61b661818e84c8f-d.ll /home/runner/.cache/go-build/78/787298d926ad5d4034e8ce9d825fc9e2acc32d365b7c4de813f04b3b6cf02514-d.ll /home/runner/.cache/go-build/58/5848df920872747b1159bb1e5f94845ca476d8bb0eafc5a99c8927dfc627abe5-d.ll /home/runner/.cache/go-build/7d/7d176c7e29b4f0500f233ce1456bc33043f3bdfc80533b1a64ce362d92a1e87d-d.ll /home/runner/.cache/go-build/2f/2ff346edfff32d26f6e981ba3302a49fe4ec5583a98f7d1977eaf9a05eff6598-d.ll /home/runner/.cache/go-build/3e/3e904527a727a59e5f8601544a9203f6861c83a097bede4825a6beca0b415bdb-d.ll /home/runner/.cache/go-build/ce/ce5e1789b2a85cec7278f6978ef3c55a2ee372bacc31657a69b6a02ee8d9136f-d.ll /home/runner/.cache/go-build/5b/5bfa27841b000caed2e25419474505d851eb2b3e07912af755262bcc7314f741-d.ll /home/runner/.cache/go-build/6b/6bd15d51eaa0c30b362a2b92d66de4fd473d68f2cb1c79d277dc849c5671b394-d.ll /home/runner/.cache/go-build/1e/1ef0ae451e86f651c1f8f5dc6b016c4eb296b29c0d4ed86d193d65615f2f4ffb-d.ll /home/runner/.cache/go-build/e7/e7fe24d7b6109589ec9d8a52b3a131957ee02528503e4355aca297b29de76aeb-d.ll /home/runner/.cache/go-build/b1/b1b8278a9aab13bc59b044e8e4f4f0a629ee107e3238ec3f5b1871cb493d05eb-d.ll /home/runner/.cache/go-build/76/76df7f6ae70847475e00cbd1903e56d4fbe0fb652dc0e87c95a955dfced59369-d.ll /home/runner/.cache/go-build/23/23f1b4cb7a4b4e8dd50245565a2efeef0119298ea8b313478d3047ee63d7a324-d.ll /home/runner/.cache/go-build/14/14d1f9af0b844b359b56ae00cc41247697180fdc978a560d5c60bcba79a883fe-d.ll /home/runner/.cache/go-build/d0/d0617f8ac5925b1600413118ac2504057e70c04185a6d4d7a4153b192ecf97b5-d.ll /home/runner/.cache/go-build/1c/1cba2ed067eeae9144f5c37670eb6df094dcec4ee580dcb9a10c897bc4ddee57-d.ll /home/runner/.cache/go-build/27/27f6e38b38bc52a72d86fa89b549d2ea3493bcc3c19dcc6707f00818a95bed73-d.ll /home/runner/.cache/go-build/27/2776e9f0ecb4552e95f3728b87011c528273486a474731ec4da14b3bad0d41d5-d.ll /home/runner/.cache/go-build/50/5029265c362f529668922fd8cd38a69d351191936194d2e7a699e09a01d65c3a-d.ll /home/runner/.cache/go-build/e5/e53bed19128b0db4b97c628244c258efd20c04a2a7207b66a21966d953dcff6c-d.ll /home/runner/.cache/go-build/43/430411a34e9f7cececba8623ea247c86a4a43eab7ff6393d6f40f69f24f78e5c-d.ll /home/runner/.cache/go-build/88/88537cbcb499eb804c1fa0c22cd649c4f3694cf9c392d72dce43f1f97934514d-d.ll /home/runner/.cache/go-build/3d/3d150fc32fb80ec2d0e15d786e5709d12f9ccbdc0bac36eddd1f9ab219aa98a8-d.ll /home/runner/.cache/go-build/a6/a69e2d46f05668d6535f3ae1d1ddd536588365b7f975d2ee71c3c52d5409a854-d.ll /home/runner/.cache/go-build/e5/e5332a096df521d720095337335e2cfc4fbccb51848e8bb02b62df614ff66a71-d.ll /tmp/main1557739843.ll /home/runner/.cache/go-build/49/49a1e72872c56699377dba5d99d370671b52325533c6bc9a85692ff7f12653e0-d.ll /home/runner/.cache/go-build/8f/8f23278ff99f02c407d13595eaa0cbe5cad88c0d7ef72384855541e5905dc717-d.ll -lgc -lpthread -ldl /home/runner/.cache/go-build/d7/d7027c86deb823ea6c1dc640eb1ba38c621cd7537a615604b5e30a63b6fedbfc-d.llcast.c.ll /home/runner/.cache/go-build/d7/d7027c86deb823ea6c1dc640eb1ba38c621cd7537a615604b5e30a63b6fedbfc-d.ll /home/runner/.cache/go-build/62/628f243b971ab9f4910381c2eff04bf235cdd5e52b300454b70c647834d81429-d.lldebug.c.ll /home/runner/.cache/go-build/62/628f243b971ab9f4910381c2eff04bf235cdd5e52b300454b70c647834d81429-d-cgo-3328521800.c.ll -lunwind /home/runner/.cache/go-build/62/628f243b971ab9f4910381c2eff04bf235cdd5e52b300454b70c647834d81429-d.ll /home/runner/.cache/go-build/85/85f91c1264d2eab9b0ccfee30b59b26a19b5b011d6ab8286a597b5e05ac0127b-d.ll -lgc -lpthread -ldl /home/runner/.cache/go-build/82/8239e8ffa421519a89e9ba41aa58b33746e959da9c3b5d02451a68ca5afe69f5-d.llpthd.c.ll /home/runner/.cache/go-build/82/8239e8ffa421519a89e9ba41aa58b33746e959da9c3b5d02451a68ca5afe69f5-d-cgo-3949623728.c.ll /home/runner/.cache/go-build/82/8239e8ffa421519a89e9ba41aa58b33746e959da9c3b5d02451a68ca5afe69f5-d.ll /home/runner/.cache/go-build/8b/8b99f2162bd2b30291a27ef4756ee015022b23eb275c5daf9a3e89b275d5ce0e-d.ll /home/runner/.cache/go-build/d0/d0eae99e38f029122b14977b24d28269135c340a133a8ac82dddbaa5a76dda85-d.ll /home/runner/.cache/go-build/99/99aa8d7258d5c96f2fc09d1cad9ab65324079137f4659b583e293fed5c371fd0-d.ll /home/runner/.cache/go-build/e2/e2733da4f2ce4d88fd01578ce9afe894a2f8aa1805276df3387e06627e3e40d1-d.ll /home/runner/.cache/go-build/42/424be3e94f9e475ac35843430b0bbba3a08e5ce1fbc5d2292ae651f053fdee79-d.ll /home/runner/.cache/go-build/43/43228426aa84980c16c485b8151301cc156ae8f82fcae0dd387e66fa7a423e66-d.llos.c.ll /home/runner/.cache/go-build/43/43228426aa84980c16c485b8151301cc156ae8f82fcae0dd387e66fa7a423e66-d-cgo-3531840087.c.ll /home/runner/.cache/go-build/43/43228426aa84980c16c485b8151301cc156ae8f82fcae0dd387e66fa7a423e66-d.ll /home/runner/.cache/go-build/c3/c3d6a9cbce22be110f5fb25cb645afce59bea3829b789ba3b685415c73c2f7eb-d.ll /home/runner/.cache/go-build/88/889c7b10c7bc9006bf9057b52aa806b631404e646b55ae1a1d548739f736bc61-d.lllibuv.c.ll /home/runner/.cache/go-build/88/889c7b10c7bc9006bf9057b52aa806b631404e646b55ae1a1d548739f736bc61-d.ll -luv -lpthread -ldl -lrt /home/runner/.cache/go-build/81/811c81eefd7555e78d29b92d7c3be4c8bd2f6bc0d3d7e20c711b7a4ef14a3293-d.lllibffi.c.ll /home/runner/.cache/go-build/81/811c81eefd7555e78d29b92d7c3be4c8bd2f6bc0d3d7e20c711b7a4ef14a3293-d.ll -lffi /home/runner/.cache/go-build/41/41d035e2082b2d23f8c439bff9ea867f3118086a5052cc2fe923633ffbbff631-d.ll /home/runner/.cache/go-build/13/133c33334973fa97765991fd9708f82c4d1ad617da883e76806f296779838231-d.llopenssl.c.ll /home/runner/.cache/go-build/13/133c33334973fa97765991fd9708f82c4d1ad617da883e76806f296779838231-d.ll -lssl -lcrypto /home/runner/.cache/go-build/b1/b165ec86e19bb9916c0ea78ca0e5fad66ba7804b91adf4dbe9dacc8d6ea81ed2-d.ll -lz -dumpdir /tmp/llgo-1969456538-" -faddrsig -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o /tmp/a14d451a0ef048c2fae6a398d57a95eb2a137fcef4784211d0153de717c15890-d-a5b514.o -x ir /home/runner/.cache/go-build/a1/a14d451a0ef048c2fae6a398d57a95eb2a137fcef4784211d0153de717c15890-d.ll
 #0 0x00007fe3981a63ff llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/lib/x86_64-linux-gnu/libLLVM-18.so.18.1+0xda63ff)
 #1 0x00007fe3981a4539 llvm::sys::RunSignalHandlers() (/lib/x86_64-linux-gnu/libLLVM-18.so.18.1+0xda4539)
 #2 0x00007fe3981a6b40 (/lib/x86_64-linux-gnu/libLLVM-18.so.18.1+0xda6b40)
 #3 0x00007fe396c45330 (/lib/x86_64-linux-gnu/libc.so.6+0x45330)
 #4 0x00007fe3980b0a4b llvm::APInt::fromString(unsigned int, llvm::StringRef, unsigned char) (/lib/x86_64-linux-gnu/libLLVM-18.so.18.1+0xcb0a4b)
 #5 0x00007fe3980c2b84 llvm::APSInt::APSInt(llvm::StringRef) (/lib/x86_64-linux-gnu/libLLVM-18.so.18.1+0xcc2b84)
 #6 0x00007fe39b1e1c32 llvm::LLLexer::LexDigitOrNegative() (/lib/x86_64-linux-gnu/libLLVM-18.so.18.1+0x3de1c32)
 #7 0x00007fe39b1f4339 llvm::LLParser::parseType(llvm::Type*&, llvm::Twine const&, bool) (/lib/x86_64-linux-gnu/libLLVM-18.so.18.1+0x3df4339)
 #8 0x00007fe39b1f53b4 llvm::LLParser::parseParameterList(llvm::SmallVectorImpl<llvm::LLParser::ParamInfo>&, llvm::LLParser::PerFunctionState&, bool, bool) (/lib/x86_64-linux-gnu/libLLVM-18.so.18.1+0x3df53b4)
 #9 0x00007fe39b20b446 llvm::LLParser::parseCall(llvm::Instruction*&, llvm::LLParser::PerFunctionState&, llvm::CallInst::TailCallKind) (/lib/x86_64-linux-gnu/libLLVM-18.so.18.1+0x3e0b446)
#10 0x00007fe39b205e3e llvm::LLParser::parseInstruction(llvm::Instruction*&, llvm::BasicBlock*, llvm::LLParser::PerFunctionState&) (/lib/x86_64-linux-gnu/libLLVM-18.so.18.1+0x3e05e3e)
#11 0x00007fe39b20574b llvm::LLParser::parseBasicBlock(llvm::LLParser::PerFunctionState&) (/lib/x86_64-linux-gnu/libLLVM-18.so.18.1+0x3e0574b)
#12 0x00007fe39b1e9110 llvm::LLParser::parseFunctionBody(llvm::Function&, llvm::ArrayRef<unsigned int>) (/lib/x86_64-linux-gnu/libLLVM-18.so.18.1+0x3de9110)
#13 0x00007fe39b1e550f llvm::LLParser::parseDefine() (/lib/x86_64-linux-gnu/libLLVM-18.so.18.1+0x3de550f)
#14 0x00007fe39b1e2d07 llvm::LLParser::parseTopLevelEntities() (/lib/x86_64-linux-gnu/libLLVM-18.so.18.1+0x3de2d07)
#15 0x00007fe39b1e28ed llvm::LLParser::Run(bool, llvm::function_ref<std::optional<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>> (llvm::StringRef, llvm::StringRef)>) (/lib/x86_64-linux-gnu/libLLVM-18.so.18.1+0x3de28ed)
#16 0x00007fe39b2230fb (/lib/x86_64-linux-gnu/libLLVM-18.so.18.1+0x3e230fb)
#17 0x00007fe39b22329c llvm::parseAssembly(llvm::MemoryBufferRef, llvm::SMDiagnostic&, llvm::LLVMContext&, llvm::SlotMapping*, llvm::function_ref<std::optional<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>> (llvm::StringRef, llvm::StringRef)>) (/lib/x86_64-linux-gnu/libLLVM-18.so.18.1+0x3e2329c)
#18 0x00007fe3983c307e llvm::parseIR(llvm::MemoryBufferRef, llvm::SMDiagnostic&, llvm::LLVMContext&, llvm::ParserCallbacks) (/lib/x86_64-linux-gnu/libLLVM-18.so.18.1+0xfc307e)
#19 0x00007fe3a0ba3c19 clang::CodeGenAction::loadModule(llvm::MemoryBufferRef) (/usr/lib/llvm-18/bin/../lib/libclang-cpp.so.18.1+0x1fa3c19)
#20 0x00007fe3a0ba485e clang::CodeGenAction::ExecuteAction() (/usr/lib/llvm-18/bin/../lib/libclang-cpp.so.18.1+0x1fa485e)
#21 0x00007fe3a1606cdc clang::FrontendAction::Execute() (/usr/lib/llvm-18/bin/../lib/libclang-cpp.so.18.1+0x2a06cdc)
#22 0x00007fe3a1583764 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/usr/lib/llvm-18/bin/../lib/libclang-cpp.so.18.1+0x2983764)
#23 0x00007fe3a1682ced clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/usr/lib/llvm-18/bin/../lib/libclang-cpp.so.18.1+0x2a82ced)
#24 0x000055c0d8bc43fe cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/usr/lib/llvm-18/bin/clang+0x143fe)
#25 0x000055c0d8bc1864 (/usr/lib/llvm-18/bin/clang+0x11864)
#26 0x000055c0d8bc09f6 clang_main(int, char**, llvm::ToolContext const&) (/usr/lib/llvm-18/bin/clang+0x109f6)
#27 0x000055c0d8bce353 main (/usr/lib/llvm-18/bin/clang+0x1e353)
#28 0x00007fe396c2a1ca (/lib/x86_64-linux-gnu/libc.so.6+0x2a1ca)
#29 0x00007fe396c2a28b __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2a28b)
#30 0x000055c0d8bbe225 _start (/usr/lib/llvm-18/bin/clang+0xe225)
error: unable to rename temporary '/tmp/a14d451a0ef048c2fae6a398d57a95eb2a137fcef4784211d0153de717c15890-d-a5b514-90e7df64.o.tmp' to output file '/tmp/a14d451a0ef048c2fae6a398d57a95eb2a137fcef4784211d0153de717c15890-d-a5b514.o': 'No such file or directory'
```

[stacktrace.txt](https://github.com/user-attachments/files/18837619/stacktrace.txt)

Original Github Actions failed: https://github.com/goplus/llgo/actions/runs/13381951254/job/37371894952?pr=995

**Comment by asudarsa** [comment]
I see that a similar issue was fixed in compiler explorer. https://github.com/compiler-explorer/compiler-explorer/commit/47195c29dc0c5297800d610666dd63393bd3d50c

May be we are also clearing temp files prematurely?

Thanks

**Comment by cpunion** [comment]
@asudarsa Thanks for the info.

I checked my workflow and during those days when this issue was occurring frequently, I replaced all the dependent setup* actions with simple shell commands, but the problem still persisted. Then at some point, it stopped happening completely. This leads me to suspect that there might have been a temporary issue with GitHub Actions at that time. I'll close this issue for now and continue to monitor for a while longer.
