### ISSUE TITLE
[AVR] clang LTO causes Arduino blink example to break

### ISSUE THREAD

**Issue by beakthoven** [llvm/llvm-project#127651]
When compiling the Blink example from the Arduino IDE for AVR using Clang with LTO enabled, the program fails to function correctly. The LED blinks once and then remains stuck in the ON position indefinitely. Disabling LTO for `wiring.c` from Arduino AVR core resolves the issue.

LLVM version: 20.1.0-rc2

### Blink example code:
```cpp
#include <Arduino.h>

void setup() {
  pinMode(LED_BUILTIN, OUTPUT);
}

void loop() {
  digitalWrite(LED_BUILTIN, HIGH); 
  delay(1000); 
  digitalWrite(LED_BUILTIN, LOW);
  delay(1000); 
}
```

### Compiler flags used (other than -flto -fno-fat-lto-objects):
```bash
--target=avr -c -g -Os -Wall -Wextra --sysroot=/home/dakkshesh/.arduino15/packages/ClangBuiltArduino/tools/cba-avr-sysroot/12022025 -std=gnu11 -ffunction-sections -fdata-sections -MMD -mmcu=atmega2560 -DF_CPU=16000000L
```
### Expected Behavior
The LED should continue blinking at a 1-second interval indefinitely.

### Attachments
LLVM IR files for wiring.c with LTO turned on and off.
[wiring.c-lto.ll.txt](https://github.com/user-attachments/files/18847521/wiring.c-lto.ll.txt)
[wiring.c-nonlto.ll.txt](https://github.com/user-attachments/files/18847522/wiring.c-nonlto.ll.txt)

`wiring.c`: https://github.com/ClangBuiltArduino/core_arduino_avr/blob/8b327d7bede1c1245db99daeba4e168c92c11194/cores/arduino/wiring.c

**Comment by foxtran** [comment]
Does GCC LTO have the same effect? Just to be sure that is not a problem with C code.

**Comment by dakkshesh07** [comment]
> Does GCC LTO have the same effect? Just to be sure that is not a problem with C code.

No, AVR GCC works perfectly fine with the same code with and without LTO.

**Comment by benshi001** [comment]
I am a little confused, I have tried your attached two `.ll.txt` files, with 
```bash
wujie@WUJIE-16:~/Downloads$ llc wiring.c-lto.ll.txt -mcpu=atmega2560 -o wiring.c-lto.s.txt
wujie@WUJIE-16:~/Downloads$ llc wiring.c-nonlto.ll.txt -mcpu=atmega2560 wiring.c-nonlto.s.txt
```

The generated assembly source only have difference in debug information, but not functional code.

[wiring.c-lto.s.txt](https://github.com/user-attachments/files/19267729/wiring.c-lto.s.txt)

[wiring.c-nonlto.s.txt](https://github.com/user-attachments/files/19267728/wiring.c-nonlto.s.txt)

**Comment by benshi001** [comment]
I also tried to compile `wiring.c` without debug information,

```bash
clang --target=avr  -S  -Os -Wall -Wextra  -std=gnu11 -ffunction-sections -fdata-sections -MMD -mmcu=atmega2560 -DF_CPU=16000000L ./core_arduino_avr/cores/arduino/wiring.c  -I core_arduino_avr/variants/mega/ -o wiring.nolto.s

clang --target=avr  -S  -Os -Wall -Wextra  -std=gnu11 -ffunction-sections -fdata-sections -MMD -mmcu=atmega2560 -DF_CPU=16000000L ./core_arduino_avr/cores/arduino/wiring.c -flto -I core_arduino_avr/variants/mega/ -o wiring.lto.ll
clang --target=avr wiring.lto.ll -S -mmcu=atmega2560 -o wiring.lto.s
```

The generated two `.s` files are also same in functional code.





so I guess, there is something wrong in the core libraries, other than `wire.c`.

**Comment by benshi001** [comment]
I also tried to compile `wiring.c` without debug information,

```bash
clang --target=avr  -S  -Os -Wall -Wextra  -std=gnu11 -ffunction-sections -fdata-sections -MMD -mmcu=atmega2560 -DF_CPU=16000000L ./core_arduino_avr/cores/arduino/wiring.c  -I core_arduino_avr/variants/mega/ -o wiring.nolto.s

clang --target=avr  -S  -Os -Wall -Wextra  -std=gnu11 -ffunction-sections -fdata-sections -MMD -mmcu=atmega2560 -DF_CPU=16000000L ./core_arduino_avr/cores/arduino/wiring.c -flto -I core_arduino_avr/variants/mega/ -o wiring.lto.ll
clang --target=avr wiring.lto.ll -S -mmcu=atmega2560 -o wiring.lto.s
```

The generated two `.s` files are also same in functional code.

[wiring.nolto.s.txt](https://github.com/user-attachments/files/19267912/wiring.nolto.s.txt)

[wiring.lto.s.txt](https://github.com/user-attachments/files/19267913/wiring.lto.s.txt)

so I guess, there is something wrong in the core libraries, other than `wire.c`.

**Comment by benshi001** [comment]
How did you get the arduino core lib built via clang? I did

1. use arduino cli to generate a blink project.
2. build the generated blink project and core lib with the attached script.

[a.sh.txt](https://github.com/user-attachments/files/19268058/a.sh.txt)

The core lib got successfully built by avr-gcc, but got failures with `clang --target=avr`.

And the failure log is
```bash
In file included from /usr/share/arduino/hardware/arduino/avr/cores/arduino/CDC.cpp:20:
/usr/lib/gcc/avr/5.4.0/../../../avr/include/avr/wdt.h:464:12: error: value '64' out of range for constraint 'I'
  464 |                                 : "I" (_SFR_IO_ADDR(_WD_CONTROL_REG)),
      |                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/lib/gcc/avr/5.4.0/../../../avr/include/avr/sfr_defs.h:183:27: note: expanded from macro '_SFR_IO_ADDR'
  183 | #define _SFR_IO_ADDR(sfr) (_SFR_MEM_ADDR(sfr) - __SFR_OFFSET)
      |                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/share/arduino/hardware/arduino/avr/cores/arduino/CDC.cpp:20:
/usr/lib/gcc/avr/5.4.0/../../../avr/include/avr/wdt.h:507:23: error: value '64' out of range for constraint 'I'
  507 |                                 : [WDTREG]  "I"  (_SFR_IO_ADDR(_WD_CONTROL_REG)),
      |                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/lib/gcc/avr/5.4.0/../../../avr/include/avr/sfr_defs.h:183:27: note: expanded from macro '_SFR_IO_ADDR'
  183 | #define _SFR_IO_ADDR(sfr) (_SFR_MEM_ADDR(sfr) - __SFR_OFFSET)
      |                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2 errors generated.
clang++: /home/wujie/benshi/llvm-project/clang/include/clang/CodeGen/CGFunctionInfo.h:185: static clang::CodeGen::ABIArgInfo clang::CodeGen::ABIArgInfo::getExtend(clang::QualType, llvm::Type*): Assertion `Ty->isIntegralOrEnumerationType() && "Unexpected QualType"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: clang++ --target=avr -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10819 -DARDUINO_AVR_NANO -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -I/usr/share/arduino/hardware/arduino/avr/variants/eightanaloginputs /usr/share/arduino/hardware/arduino/avr/cores/arduino/new.cpp -o /tmp/arduino_build_242933/core/new.cpp.o
1.	/usr/share/arduino/hardware/arduino/avr/cores/arduino/new.cpp:68:1: current parser token 'void'
2.	/usr/share/arduino/hardware/arduino/avr/cores/arduino/new.cpp:59:8: LLVM IR generation of declaration 'operator new'
3.	/usr/share/arduino/hardware/arduino/avr/cores/arduino/new.cpp:59:8: Generating code for declaration 'operator new'
 #0 0x000055d974314900 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/home/wujie/benshi/llvm-project/build/bin/clang-21+0x27fd900)
 #1 0x000055d9743111ff llvm::sys::RunSignalHandlers() (/home/wujie/benshi/llvm-project/build/bin/clang-21+0x27fa1ff)
 #2 0x000055d9741ecb38 CrashRecoverySignalHandler(int) CrashRecoveryContext.cpp:0:0
 #3 0x00007f7c19042520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #4 0x00007f7c190969fc pthread_kill (/lib/x86_64-linux-gnu/libc.so.6+0x969fc)
 #5 0x00007f7c19042476 gsignal (/lib/x86_64-linux-gnu/libc.so.6+0x42476)
 #6 0x00007f7c190287f3 abort (/lib/x86_64-linux-gnu/libc.so.6+0x287f3)
 #7 0x00007f7c1902871b (/lib/x86_64-linux-gnu/libc.so.6+0x2871b)
 #8 0x00007f7c19039e96 (/lib/x86_64-linux-gnu/libc.so.6+0x39e96)
 #9 0x000055d974a50084 (anonymous namespace)::AVRABIInfo::computeInfo(clang::CodeGen::CGFunctionInfo&) const AVR.cpp:0:0
#10 0x000055d974cb90fa clang::CodeGen::CodeGenTypes::arrangeLLVMFunctionInfo(clang::CanQual<clang::Type>, clang::CodeGen::FnInfoOpts, llvm::ArrayRef<clang::CanQual<clang::Type>>, clang::FunctionType::ExtInfo, llvm::ArrayRef<clang::FunctionType::ExtParameterInfo>, clang::CodeGen::RequiredArgs) (/home/wujie/benshi/llvm-project/build/bin/clang-21+0x31a20fa)
#11 0x000055d974cbd97b arrangeLLVMFunctionInfo(clang::CodeGen::CodeGenTypes&, bool, llvm::SmallVectorImpl<clang::CanQual<clang::Type>>&, clang::CanQual<clang::FunctionProtoType>) CGCall.cpp:0:0
#12 0x000055d974cbfc25 clang::CodeGen::CodeGenTypes::arrangeFunctionDeclaration(clang::FunctionDecl const*) (/home/wujie/benshi/llvm-project/build/bin/clang-21+0x31a8c25)
#13 0x000055d974978325 clang::CodeGen::CodeGenModule::EmitGlobalFunctionDefinition(clang::GlobalDecl, llvm::GlobalValue*) (/home/wujie/benshi/llvm-project/build/bin/clang-21+0x2e61325)
#14 0x000055d974973884 clang::CodeGen::CodeGenModule::EmitGlobalDefinition(clang::GlobalDecl, llvm::GlobalValue*) (/home/wujie/benshi/llvm-project/build/bin/clang-21+0x2e5c884)
#15 0x000055d974973efb clang::CodeGen::CodeGenModule::EmitGlobal(clang::GlobalDecl) (/home/wujie/benshi/llvm-project/build/bin/clang-21+0x2e5cefb)
#16 0x000055d97497cbd7 clang::CodeGen::CodeGenModule::EmitTopLevelDecl(clang::Decl*) (.part.0) CodeGenModule.cpp:0:0
#17 0x000055d974dd1cd6 (anonymous namespace)::CodeGeneratorImpl::HandleTopLevelDecl(clang::DeclGroupRef) ModuleBuilder.cpp:0:0
#18 0x000055d974dbf981 clang::BackendConsumer::HandleTopLevelDecl(clang::DeclGroupRef) (/home/wujie/benshi/llvm-project/build/bin/clang-21+0x32a8981)
#19 0x000055d976e12e94 clang::ParseAST(clang::Sema&, bool, bool) (/home/wujie/benshi/llvm-project/build/bin/clang-21+0x52fbe94)
#20 0x000055d975167bd9 clang::FrontendAction::Execute() (/home/wujie/benshi/llvm-project/build/bin/clang-21+0x3650bd9)
#21 0x000055d9750c251e clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/home/wujie/benshi/llvm-project/build/bin/clang-21+0x35ab51e)
#22 0x000055d975287dc8 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/home/wujie/benshi/llvm-project/build/bin/clang-21+0x3770dc8)
#23 0x000055d9728243bb cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/home/wujie/benshi/llvm-project/build/bin/clang-21+0xd0d3bb)
#24 0x000055d972815e9a ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&, llvm::ToolContext const&) driver.cpp:0:0
#25 0x000055d974e3311d void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const::'lambda'()>(long) Job.cpp:0:0
#26 0x000055d9741ecfe0 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/home/wujie/benshi/llvm-project/build/bin/clang-21+0x26d5fe0)
#27 0x000055d974e3576e clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const (.part.0) Job.cpp:0:0
#28 0x000055d974dde8c1 clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const (/home/wujie/benshi/llvm-project/build/bin/clang-21+0x32c78c1)
#29 0x000055d974ddf9e1 clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&, bool) const (/home/wujie/benshi/llvm-project/build/bin/clang-21+0x32c89e1)
#30 0x000055d974defeb4 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&) (/home/wujie/benshi/llvm-project/build/bin/clang-21+0x32d8eb4)
#31 0x000055d97281c13e clang_main(int, char**, llvm::ToolContext const&) (/home/wujie/benshi/llvm-project/build/bin/clang-21+0xd0513e)
#32 0x000055d97274cb0b main (/home/wujie/benshi/llvm-project/build/bin/clang-21+0xc35b0b)
#33 0x00007f7c19029d90 (/lib/x86_64-linux-gnu/libc.so.6+0x29d90)
#34 0x00007f7c19029e40 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e40)
#35 0x000055d9728155c5 _start (/home/wujie/benshi/llvm-project/build/bin/clang-21+0xcfe5c5)
clang++: error: clang frontend command failed with exit code 134 (use -v to see invocation)
clang version 21.0.0git (git@github.com:llvm/llvm-project.git 254951749febef42620242fd22dfba62f624f79f)
Target: avr
Thread model: posix
InstalledDir: /home/wujie/benshi/llvm-project/build/bin
Build config: +assertions, +expensive-checks
clang++: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang++: note: diagnostic msg: /tmp/new-92a0e9.cpp
clang++: note: diagnostic msg: /tmp/new-92a0e9.sh
clang++: note: diagnostic msg: 

********************
/usr/lib/gcc/avr/5.4.0/../../../avr/bin/ar: /tmp/arduino_build_242933/core/CDC.cpp.o: 没有那个文件或目录
/usr/lib/gcc/avr/5.4.0/../../../avr/bin/ar: /tmp/arduino_build_242933/core/new.cpp.o: 没有那个文件或目录
```

**Comment by benshi001** [comment]
How did you get the arduino core lib built via clang? I did

1. use arduino cli to generate a blink project.
2. build the generated blink project and core lib with the attached script.

[a.sh.txt](https://github.com/user-attachments/files/19268058/a.sh.txt)

The core lib got successfully built by avr-gcc, but got failures with `clang --target=avr`.

And the failure log is
```bash
In file included from /usr/share/arduino/hardware/arduino/avr/cores/arduino/CDC.cpp:20:
/usr/lib/gcc/avr/5.4.0/../../../avr/include/avr/wdt.h:464:12: error: value '64' out of range for constraint 'I'
  464 |                                 : "I" (_SFR_IO_ADDR(_WD_CONTROL_REG)),
      |                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/lib/gcc/avr/5.4.0/../../../avr/include/avr/sfr_defs.h:183:27: note: expanded from macro '_SFR_IO_ADDR'
  183 | #define _SFR_IO_ADDR(sfr) (_SFR_MEM_ADDR(sfr) - __SFR_OFFSET)
      |                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/share/arduino/hardware/arduino/avr/cores/arduino/CDC.cpp:20:
/usr/lib/gcc/avr/5.4.0/../../../avr/include/avr/wdt.h:507:23: error: value '64' out of range for constraint 'I'
  507 |                                 : [WDTREG]  "I"  (_SFR_IO_ADDR(_WD_CONTROL_REG)),
      |                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/lib/gcc/avr/5.4.0/../../../avr/include/avr/sfr_defs.h:183:27: note: expanded from macro '_SFR_IO_ADDR'
  183 | #define _SFR_IO_ADDR(sfr) (_SFR_MEM_ADDR(sfr) - __SFR_OFFSET)
      |                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2 errors generated.
clang++: /home/wujie/benshi/llvm-project/clang/include/clang/CodeGen/CGFunctionInfo.h:185: static clang::CodeGen::ABIArgInfo clang::CodeGen::ABIArgInfo::getExtend(clang::QualType, llvm::Type*): Assertion `Ty->isIntegralOrEnumerationType() && "Unexpected QualType"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: clang++ --target=avr -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10819 -DARDUINO_AVR_NANO -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -I/usr/share/arduino/hardware/arduino/avr/variants/eightanaloginputs /usr/share/arduino/hardware/arduino/avr/cores/arduino/new.cpp -o /tmp/arduino_build_242933/core/new.cpp.o
1.	/usr/share/arduino/hardware/arduino/avr/cores/arduino/new.cpp:68:1: current parser token 'void'
2.	/usr/share/arduino/hardware/arduino/avr/cores/arduino/new.cpp:59:8: LLVM IR generation of declaration 'operator new'
3.	/usr/share/arduino/hardware/arduino/avr/cores/arduino/new.cpp:59:8: Generating code for declaration 'operator new'
 #0 0x000055d974314900 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/home/wujie/benshi/llvm-project/build/bin/clang-21+0x27fd900)
 #1 0x000055d9743111ff llvm::sys::RunSignalHandlers() (/home/wujie/benshi/llvm-project/build/bin/clang-21+0x27fa1ff)
 #2 0x000055d9741ecb38 CrashRecoverySignalHandler(int) CrashRecoveryContext.cpp:0:0
 #3 0x00007f7c19042520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #4 0x00007f7c190969fc pthread_kill (/lib/x86_64-linux-gnu/libc.so.6+0x969fc)
 #5 0x00007f7c19042476 gsignal (/lib/x86_64-linux-gnu/libc.so.6+0x42476)
 #6 0x00007f7c190287f3 abort (/lib/x86_64-linux-gnu/libc.so.6+0x287f3)
 #7 0x00007f7c1902871b (/lib/x86_64-linux-gnu/libc.so.6+0x2871b)
 #8 0x00007f7c19039e96 (/lib/x86_64-linux-gnu/libc.so.6+0x39e96)
 #9 0x000055d974a50084 (anonymous namespace)::AVRABIInfo::computeInfo(clang::CodeGen::CGFunctionInfo&) const AVR.cpp:0:0
#10 0x000055d974cb90fa clang::CodeGen::CodeGenTypes::arrangeLLVMFunctionInfo(clang::CanQual<clang::Type>, clang::CodeGen::FnInfoOpts, llvm::ArrayRef<clang::CanQual<clang::Type>>, clang::FunctionType::ExtInfo, llvm::ArrayRef<clang::FunctionType::ExtParameterInfo>, clang::CodeGen::RequiredArgs) (/home/wujie/benshi/llvm-project/build/bin/clang-21+0x31a20fa)
#11 0x000055d974cbd97b arrangeLLVMFunctionInfo(clang::CodeGen::CodeGenTypes&, bool, llvm::SmallVectorImpl<clang::CanQual<clang::Type>>&, clang::CanQual<clang::FunctionProtoType>) CGCall.cpp:0:0
#12 0x000055d974cbfc25 clang::CodeGen::CodeGenTypes::arrangeFunctionDeclaration(clang::FunctionDecl const*) (/home/wujie/benshi/llvm-project/build/bin/clang-21+0x31a8c25)
#13 0x000055d974978325 clang::CodeGen::CodeGenModule::EmitGlobalFunctionDefinition(clang::GlobalDecl, llvm::GlobalValue*) (/home/wujie/benshi/llvm-project/build/bin/clang-21+0x2e61325)
#14 0x000055d974973884 clang::CodeGen::CodeGenModule::EmitGlobalDefinition(clang::GlobalDecl, llvm::GlobalValue*) (/home/wujie/benshi/llvm-project/build/bin/clang-21+0x2e5c884)
#15 0x000055d974973efb clang::CodeGen::CodeGenModule::EmitGlobal(clang::GlobalDecl) (/home/wujie/benshi/llvm-project/build/bin/clang-21+0x2e5cefb)
#16 0x000055d97497cbd7 clang::CodeGen::CodeGenModule::EmitTopLevelDecl(clang::Decl*) (.part.0) CodeGenModule.cpp:0:0
#17 0x000055d974dd1cd6 (anonymous namespace)::CodeGeneratorImpl::HandleTopLevelDecl(clang::DeclGroupRef) ModuleBuilder.cpp:0:0
#18 0x000055d974dbf981 clang::BackendConsumer::HandleTopLevelDecl(clang::DeclGroupRef) (/home/wujie/benshi/llvm-project/build/bin/clang-21+0x32a8981)
#19 0x000055d976e12e94 clang::ParseAST(clang::Sema&, bool, bool) (/home/wujie/benshi/llvm-project/build/bin/clang-21+0x52fbe94)
#20 0x000055d975167bd9 clang::FrontendAction::Execute() (/home/wujie/benshi/llvm-project/build/bin/clang-21+0x3650bd9)
#21 0x000055d9750c251e clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/home/wujie/benshi/llvm-project/build/bin/clang-21+0x35ab51e)
#22 0x000055d975287dc8 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/home/wujie/benshi/llvm-project/build/bin/clang-21+0x3770dc8)
#23 0x000055d9728243bb cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/home/wujie/benshi/llvm-project/build/bin/clang-21+0xd0d3bb)
#24 0x000055d972815e9a ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&, llvm::ToolContext const&) driver.cpp:0:0
#25 0x000055d974e3311d void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const::'lambda'()>(long) Job.cpp:0:0
#26 0x000055d9741ecfe0 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/home/wujie/benshi/llvm-project/build/bin/clang-21+0x26d5fe0)
#27 0x000055d974e3576e clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const (.part.0) Job.cpp:0:0
#28 0x000055d974dde8c1 clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const (/home/wujie/benshi/llvm-project/build/bin/clang-21+0x32c78c1)
#29 0x000055d974ddf9e1 clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&, bool) const (/home/wujie/benshi/llvm-project/build/bin/clang-21+0x32c89e1)
#30 0x000055d974defeb4 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&) (/home/wujie/benshi/llvm-project/build/bin/clang-21+0x32d8eb4)
#31 0x000055d97281c13e clang_main(int, char**, llvm::ToolContext const&) (/home/wujie/benshi/llvm-project/build/bin/clang-21+0xd0513e)
#32 0x000055d97274cb0b main (/home/wujie/benshi/llvm-project/build/bin/clang-21+0xc35b0b)
#33 0x00007f7c19029d90 (/lib/x86_64-linux-gnu/libc.so.6+0x29d90)
#34 0x00007f7c19029e40 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e40)
#35 0x000055d9728155c5 _start (/home/wujie/benshi/llvm-project/build/bin/clang-21+0xcfe5c5)
clang++: error: clang frontend command failed with exit code 134 (use -v to see invocation)
clang version 21.0.0git (git@github.com:llvm/llvm-project.git 254951749febef42620242fd22dfba62f624f79f)
Target: avr
Thread model: posix
InstalledDir: /home/wujie/benshi/llvm-project/build/bin
Build config: +assertions, +expensive-checks
clang++: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang++: note: diagnostic msg: /tmp/new-92a0e9.cpp
clang++: note: diagnostic msg: /tmp/new-92a0e9.sh
clang++: note: diagnostic msg: 

********************
/usr/lib/gcc/avr/5.4.0/../../../avr/bin/ar: /tmp/arduino_build_242933/core/CDC.cpp.o: 没有那个文件或目录
/usr/lib/gcc/avr/5.4.0/../../../avr/bin/ar: /tmp/arduino_build_242933/core/new.cpp.o: 没有那个文件或目录
```

**Comment by benshi001** [comment]
BTW: how did build arduino core library by clang? I used the attached script but failed.

[arduino.sh.txt](https://github.com/user-attachments/files/19268276/arduino.sh.txt)

The failure log is
```bash
In file included from /usr/share/arduino/hardware/arduino/avr/cores/arduino/CDC.cpp:20:
/usr/lib/gcc/avr/5.4.0/../../../avr/include/avr/wdt.h:464:12: error: value '64' out of range for constraint 'I'
  464 |                                 : "I" (_SFR_IO_ADDR(_WD_CONTROL_REG)),
      |                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/lib/gcc/avr/5.4.0/../../../avr/include/avr/sfr_defs.h:183:27: note: expanded from macro '_SFR_IO_ADDR'
  183 | #define _SFR_IO_ADDR(sfr) (_SFR_MEM_ADDR(sfr) - __SFR_OFFSET)
      |                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/share/arduino/hardware/arduino/avr/cores/arduino/CDC.cpp:20:
/usr/lib/gcc/avr/5.4.0/../../../avr/include/avr/wdt.h:507:23: error: value '64' out of range for constraint 'I'
  507 |                                 : [WDTREG]  "I"  (_SFR_IO_ADDR(_WD_CONTROL_REG)),
      |                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/lib/gcc/avr/5.4.0/../../../avr/include/avr/sfr_defs.h:183:27: note: expanded from macro '_SFR_IO_ADDR'
  183 | #define _SFR_IO_ADDR(sfr) (_SFR_MEM_ADDR(sfr) - __SFR_OFFSET)
      |                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2 errors generated.
clang++: /home/wujie/benshi/llvm-project/clang/include/clang/CodeGen/CGFunctionInfo.h:185: static clang::CodeGen::ABIArgInfo clang::CodeGen::ABIArgInfo::getExtend(clang::QualType, llvm::Type*): Assertion `Ty->isIntegralOrEnumerationType() && "Unexpected QualType"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: clang++ --target=avr -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10819 -DARDUINO_AVR_NANO -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -I/usr/share/arduino/hardware/arduino/avr/variants/eightanaloginputs /usr/share/arduino/hardware/arduino/avr/cores/arduino/new.cpp -o /tmp/arduino_build_960004/core/new.cpp.o
1.	/usr/share/arduino/hardware/arduino/avr/cores/arduino/new.cpp:68:1: current parser token 'void'
2.	/usr/share/arduino/hardware/arduino/avr/cores/arduino/new.cpp:59:8: LLVM IR generation of declaration 'operator new'
3.	/usr/share/arduino/hardware/arduino/avr/cores/arduino/new.cpp:59:8: Generating code for declaration 'operator new'
 #0 0x00005aa720523900 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/home/wujie/benshi/llvm-project/build/bin/clang-21+0x27fd900)
 #1 0x00005aa7205201ff llvm::sys::RunSignalHandlers() (/home/wujie/benshi/llvm-project/build/bin/clang-21+0x27fa1ff)
 #2 0x00005aa7203fbb38 CrashRecoverySignalHandler(int) CrashRecoveryContext.cpp:0:0
 #3 0x00007d6b34e42520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #4 0x00007d6b34e969fc pthread_kill (/lib/x86_64-linux-gnu/libc.so.6+0x969fc)
 #5 0x00007d6b34e42476 gsignal (/lib/x86_64-linux-gnu/libc.so.6+0x42476)
 #6 0x00007d6b34e287f3 abort (/lib/x86_64-linux-gnu/libc.so.6+0x287f3)
 #7 0x00007d6b34e2871b (/lib/x86_64-linux-gnu/libc.so.6+0x2871b)
 #8 0x00007d6b34e39e96 (/lib/x86_64-linux-gnu/libc.so.6+0x39e96)
 #9 0x00005aa720c5f084 (anonymous namespace)::AVRABIInfo::computeInfo(clang::CodeGen::CGFunctionInfo&) const AVR.cpp:0:0
#10 0x00005aa720ec80fa clang::CodeGen::CodeGenTypes::arrangeLLVMFunctionInfo(clang::CanQual<clang::Type>, clang::CodeGen::FnInfoOpts, llvm::ArrayRef<clang::CanQual<clang::Type>>, clang::FunctionType::ExtInfo, llvm::ArrayRef<clang::FunctionType::ExtParameterInfo>, clang::CodeGen::RequiredArgs) (/home/wujie/benshi/llvm-project/build/bin/clang-21+0x31a20fa)
#11 0x00005aa720ecc97b arrangeLLVMFunctionInfo(clang::CodeGen::CodeGenTypes&, bool, llvm::SmallVectorImpl<clang::CanQual<clang::Type>>&, clang::CanQual<clang::FunctionProtoType>) CGCall.cpp:0:0
#12 0x00005aa720ecec25 clang::CodeGen::CodeGenTypes::arrangeFunctionDeclaration(clang::FunctionDecl const*) (/home/wujie/benshi/llvm-project/build/bin/clang-21+0x31a8c25)
#13 0x00005aa720b87325 clang::CodeGen::CodeGenModule::EmitGlobalFunctionDefinition(clang::GlobalDecl, llvm::GlobalValue*) (/home/wujie/benshi/llvm-project/build/bin/clang-21+0x2e61325)
#14 0x00005aa720b82884 clang::CodeGen::CodeGenModule::EmitGlobalDefinition(clang::GlobalDecl, llvm::GlobalValue*) (/home/wujie/benshi/llvm-project/build/bin/clang-21+0x2e5c884)
#15 0x00005aa720b82efb clang::CodeGen::CodeGenModule::EmitGlobal(clang::GlobalDecl) (/home/wujie/benshi/llvm-project/build/bin/clang-21+0x2e5cefb)
#16 0x00005aa720b8bbd7 clang::CodeGen::CodeGenModule::EmitTopLevelDecl(clang::Decl*) (.part.0) CodeGenModule.cpp:0:0
#17 0x00005aa720fe0cd6 (anonymous namespace)::CodeGeneratorImpl::HandleTopLevelDecl(clang::DeclGroupRef) ModuleBuilder.cpp:0:0
#18 0x00005aa720fce981 clang::BackendConsumer::HandleTopLevelDecl(clang::DeclGroupRef) (/home/wujie/benshi/llvm-project/build/bin/clang-21+0x32a8981)
#19 0x00005aa723021e94 clang::ParseAST(clang::Sema&, bool, bool) (/home/wujie/benshi/llvm-project/build/bin/clang-21+0x52fbe94)
#20 0x00005aa721376bd9 clang::FrontendAction::Execute() (/home/wujie/benshi/llvm-project/build/bin/clang-21+0x3650bd9)
#21 0x00005aa7212d151e clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/home/wujie/benshi/llvm-project/build/bin/clang-21+0x35ab51e)
#22 0x00005aa721496dc8 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/home/wujie/benshi/llvm-project/build/bin/clang-21+0x3770dc8)
#23 0x00005aa71ea333bb cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/home/wujie/benshi/llvm-project/build/bin/clang-21+0xd0d3bb)
#24 0x00005aa71ea24e9a ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&, llvm::ToolContext const&) driver.cpp:0:0
#25 0x00005aa72104211d void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const::'lambda'()>(long) Job.cpp:0:0
#26 0x00005aa7203fbfe0 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/home/wujie/benshi/llvm-project/build/bin/clang-21+0x26d5fe0)
#27 0x00005aa72104476e clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const (.part.0) Job.cpp:0:0
#28 0x00005aa720fed8c1 clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const (/home/wujie/benshi/llvm-project/build/bin/clang-21+0x32c78c1)
#29 0x00005aa720fee9e1 clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&, bool) const (/home/wujie/benshi/llvm-project/build/bin/clang-21+0x32c89e1)
#30 0x00005aa720ffeeb4 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&) (/home/wujie/benshi/llvm-project/build/bin/clang-21+0x32d8eb4)
#31 0x00005aa71ea2b13e clang_main(int, char**, llvm::ToolContext const&) (/home/wujie/benshi/llvm-project/build/bin/clang-21+0xd0513e)
#32 0x00005aa71e95bb0b main (/home/wujie/benshi/llvm-project/build/bin/clang-21+0xc35b0b)
#33 0x00007d6b34e29d90 (/lib/x86_64-linux-gnu/libc.so.6+0x29d90)
#34 0x00007d6b34e29e40 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e40)
#35 0x00005aa71ea245c5 _start (/home/wujie/benshi/llvm-project/build/bin/clang-21+0xcfe5c5)
clang++: error: clang frontend command failed with exit code 134 (use -v to see invocation)
clang version 21.0.0git (git@github.com:llvm/llvm-project.git 254951749febef42620242fd22dfba62f624f79f)
Target: avr
Thread model: posix
InstalledDir: /home/wujie/benshi/llvm-project/build/bin
Build config: +assertions, +expensive-checks
clang++: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang++: note: diagnostic msg: /tmp/new-fd3c2f.cpp
clang++: note: diagnostic msg: /tmp/new-fd3c2f.sh
clang++: note: diagnostic msg: 

********************
/usr/lib/gcc/avr/5.4.0/../../../avr/bin/ar: /tmp/arduino_build_960004/core/CDC.cpp.o: 没有那个文件或目录
/usr/lib/gcc/avr/5.4.0/../../../avr/bin/ar: /tmp/arduino_build_960004/core/new.cpp.o: 没有那个文件或目录
```

**Comment by benshi001** [comment]
I think I should fix the above failure first, it indeed is clang's ICE, as the first step to let clang support arduino.

**Comment by dakkshesh07** [comment]
> I am a little confused, I have tried your attached two `.ll.txt` files, with
> 
> wujie@WUJIE-16:~/Downloads$ llc wiring.c-lto.ll.txt -mcpu=atmega2560 -o wiring.c-lto.s.txt
> wujie@WUJIE-16:~/Downloads$ llc wiring.c-nonlto.ll.txt -mcpu=atmega2560 wiring.c-nonlto.s.txt
> The generated assembly source files only have difference in debug information, but not functional code.
> 
> [wiring.c-lto.s.txt](https://github.com/user-attachments/files/19267729/wiring.c-lto.s.txt)
> 
> [wiring.c-nonlto.s.txt](https://github.com/user-attachments/files/19267728/wiring.c-nonlto.s.txt)

Then i think LTO optimizations made during link time are then likely the cause of the issue.  I'll try to upload LTO intermediate files shortly in order to debug this.

**Comment by benshi001** [comment]
> > I am a little confused, I have tried your attached two `.ll.txt` files, with
> > wujie@WUJIE-16:~/Downloads$ llc wiring.c-lto.ll.txt -mcpu=atmega2560 -o wiring.c-lto.s.txt
> > wujie@WUJIE-16:~/Downloads$ llc wiring.c-nonlto.ll.txt -mcpu=atmega2560 wiring.c-nonlto.s.txt
> > The generated assembly source files only have difference in debug information, but not functional code.
> > [wiring.c-lto.s.txt](https://github.com/user-attachments/files/19267729/wiring.c-lto.s.txt)
> > [wiring.c-nonlto.s.txt](https://github.com/user-attachments/files/19267728/wiring.c-nonlto.s.txt)
> 
> Then i think LTO optimizations made during link time are then likely the cause of the issue. I'll try to upload LTO intermediate files shortly in order to debug this.

It would be better if you can give the final linked file in the form of

1. LTO linked in IR
2. LTO linked in assembly
3. not LTO linked in IR
4. not LTO linked in assembly

**Comment by benshi001** [comment]
> [avrdudes/avr-libc#998](https://github.com/avrdudes/avr-libc/issues/998)

Thanks for your clarification, I would try
1. apply your patch to dismiss the first error
2. fix the second error 
3. reproduce the bug you encountered

**Comment by benshi001** [comment]
> > In file included from /usr/share/arduino/hardware/arduino/avr/cores/arduino/CDC.cpp:20:
> > /usr/lib/gcc/avr/5.4.0/../../../avr/include/avr/wdt.h:464:12: error: value '64' out of range for constraint 'I'
> > 464 |                                 : "I" (_SFR_IO_ADDR(_WD_CONTROL_REG)),
> > |                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> > /usr/lib/gcc/avr/5.4.0/../../../avr/include/avr/sfr_defs.h:183:27: note: expanded from macro '_SFR_IO_ADDR'
> > 183 | #define _SFR_IO_ADDR(sfr) (_SFR_MEM_ADDR(sfr) - __SFR_OFFSET)
> > |                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> > In file included from /usr/share/arduino/hardware/arduino/avr/cores/arduino/CDC.cpp:20:
> > /usr/lib/gcc/avr/5.4.0/../../../avr/include/avr/wdt.h:507:23: error: value '64' out of range for constraint 'I'
> > 507 |                                 : [WDTREG]  "I"  (_SFR_IO_ADDR(_WD_CONTROL_REG)),
> > |                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> > /usr/lib/gcc/avr/5.4.0/../../../avr/include/avr/sfr_defs.h:183:27: note: expanded from macro '_SFR_IO_ADDR'
> > 183 | #define _SFR_IO_ADDR(sfr) (_SFR_MEM_ADDR(sfr) - __SFR_OFFSET)
> > |                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> > 2 errors generated.
> 
> The constraint error you have encountered is because of a code in AVR libc thats written in a way that makes use of gcc specific behavior. avr-libc issue: [avrdudes/avr-libc#998](https://github.com/avrdudes/avr-libc/issues/998) llvm issue: [#51513](https://github.com/llvm/llvm-project/issues/51513)
> 
> For time being i have applied the [following patch](https://github.com/ClangBuiltArduino/avr-libc/commit/b0ecbda693844f45214792cf9a04308b0a08efaf) in my fork of avr-libc to mitigate the constraint issue since there is no official fix from avr-libc.
> 
> However about to the clang crash, I haven't encountered it during my builds so i dont know what we're looking here.
> 
> > BTW: how did build arduino core library by clang?
> 
> Well i wrote this simple [bash script](https://github.com/ClangBuiltArduino/build-scripts/blob/main/build-mega.sh) to use during initial stage. Now i have completely moved to arduino's build system, the required changes for this were made to the build files in the core lib repo as of commit [ClangBuiltArduino/core_arduino_avr@96cc1db](https://github.com/ClangBuiltArduino/core_arduino_avr/commit/96cc1dbd93c963f399443be82ad50cc4e6dd4347). This should be compatible with arduino-cli as well.

Thanks for your clarification, I would try

apply your patch to dismiss the first error
fix the second error
reproduce the bug you encountered

**Comment by benshi001** [comment]
I have fixed the first crash, as path https://github.com/llvm/llvm-project/pull/131976,

but I encountered a second crash, as reported in https://github.com/llvm/llvm-project/issues/132203

**Comment by benshi001** [comment]
@dakkshesh07 , may I ask

1. Is there a instruction about how to build your `ClangBuiltArduino` project? Or I simply follow the arduino CLI way  ？
2. which version of  clang /llvm are you using? Is yours the newest main branch ?

**Comment by dakkshesh07** [comment]
> 1. Is there a instruction about how to build your `ClangBuiltArduino` project? Or I simply follow the arduino CLI way  ？

You can directly add the custom board package json and then use it to compile.

```shell
arduino-cli config add board_manager.additional_urls https://raw.githubusercontent.com/ClangBuiltArduino/BoardManagerFiles/refs/heads/main/package_clangbuiltarduino_index.json
arduino-cli core update-index
arduino-cli core install ClangBuiltArduino:avr
arduino-cli compile -b ClangBuiltArduino:avr:mega $dir
```
> 3. which version of  clang /llvm are you using? Is yours the newest main branch ?

I haven't updated the json since 20.1.0-rc2 build, I have a 20.1.0 build ready to be used. I will update the json and try once.
I will also update toolchain scripts to add the ability to build off of main branch instead of release tarballs so that we can test bleeding edge builds.

Btw can you take a look at my llvm build configuration, maybe i disabled some crucial feature so I'm not getting those crashes?
https://github.com/ClangBuiltArduino/tc-build/blob/main/llvm/build-llvm-stage2.sh#L63-L223

> I still failed build the simplest blink program with the above two crashes.

I will try to use the latest 20.1.0 build or main branch build to see if i can hit those crashes.

**Comment by dakkshesh07** [comment]
I have updated the toolchain to 20.1.0 as of commit:
https://github.com/ClangBuiltArduino/BoardManagerFiles/commit/9584288805fe065b8fcb8779feec24d7ce2ab40d

```shell
$ arduino-cli compile --clean -b ClangBuiltArduino:avr:mega Blink

Sketch uses 1418 bytes (0%) of program storage space. Maximum is 253952 bytes.
Global variables use 9 bytes (0%) of dynamic memory, leaving 8183 bytes for local variables. Maximum is 8192 bytes.

Used platform         Version Path
ClangBuiltArduino:avr 1.0.1   /home/dakkshesh/.arduino15/packages/ClangBuiltArduino/hardware/avr/1.0.1
```

**Comment by dakkshesh07** [comment]
> I have fixed the first crash, as patch [#131976](https://github.com/llvm/llvm-project/pull/131976),

I'll try building off of main branch once this patch is merged.

**Comment by benshi001** [comment]
I have fixed the 2nd crash as https://github.com/llvm/llvm-project/pull/132398, but a third error (a link failure) rised. I never thought building the simplest blink with clang is so hard.


```bash
/data/home/bennshi/.cache/arduino/sketches/CEE06FE2D07E31C0BC8B101357BC67E2/core/core.a(HardwareSerial.cpp.o): In function `serialEventRun()':
/data/home/bennshi/.arduino15/packages/arduino/hardware/avr/1.8.6/cores/arduino/HardwareSerial.cpp:(.text._Z14serialEventRunv+0xa): undefined reference to `serialEvent()'
/data/home/bennshi/.arduino15/packages/arduino/hardware/avr/1.8.6/cores/arduino/HardwareSerial.cpp:(.text._Z14serialEventRunv+0xc): undefined reference to `serialEvent()'
/data/home/bennshi/.arduino15/packages/arduino/hardware/avr/1.8.6/cores/arduino/HardwareSerial.cpp:67: undefined reference to `serialEvent()'
/data/home/bennshi/.cache/arduino/sketches/CEE06FE2D07E31C0BC8B101357BC67E2/core/core.a(HardwareSerial.cpp.o):(.rodata._ZTI14HardwareSerial+0x0): undefined reference to `vtable for __cxxabiv1::__si_class_type_info'
/data/home/bennshi/.cache/arduino/sketches/CEE06FE2D07E31C0BC8B101357BC67E2/core/core.a(HardwareSerial.cpp.o):(.rodata._ZTI6Stream[_ZTI6Stream]+0x0): undefined reference to `vtable for __cxxabiv1::__si_class_type_info'
/data/home/bennshi/.cache/arduino/sketches/CEE06FE2D07E31C0BC8B101357BC67E2/core/core.a(Print.cpp.o):(.rodata._ZTI5Print+0x0): undefined reference to `vtable for __cxxabiv1::__class_type_info'
clang: error: avr-ld command failed with exit code 1 (use -v to see invocation)
```

**Comment by dakkshesh07** [comment]
> /data/home/bennshi/.cache/arduino/sketches/CEE06FE2D07E31C0BC8B101357BC67E2/core/core.a(HardwareSerial.cpp.o): In function `serialEventRun()':
> /data/home/bennshi/.arduino15/packages/arduino/hardware/avr/1.8.6/cores/arduino/HardwareSerial.cpp:(.text._Z14serialEventRunv+0xa): undefined reference to `serialEvent()'
> /data/home/bennshi/.arduino15/packages/arduino/hardware/avr/1.8.6/cores/arduino/HardwareSerial.cpp:(.text._Z14serialEventRunv+0xc): undefined reference to `serialEvent()'
> /data/home/bennshi/.arduino15/packages/arduino/hardware/avr/1.8.6/cores/arduino/HardwareSerial.cpp:67: undefined reference to `serialEvent()'

These errors should be fixed using the following commits:
https://github.com/ClangBuiltArduino/core_arduino_avr/commit/9602bbb2523eedbe1e8c7459659e3eb00781b000
https://github.com/ClangBuiltArduino/core_arduino_avr/commit/9602bbb2523eedbe1e8c7459659e3eb00781b000

> /data/home/bennshi/.cache/arduino/sketches/CEE06FE2D07E31C0BC8B101357BC67E2/core/core.a(HardwareSerial.cpp.o):(.rodata._ZTI14HardwareSerial+0x0): undefined reference to `vtable for __cxxabiv1::__si_class_type_info'
> /data/home/bennshi/.cache/arduino/sketches/CEE06FE2D07E31C0BC8B101357BC67E2/core/core.a(HardwareSerial.cpp.o):(.rodata._ZTI6Stream[_ZTI6Stream]+0x0): undefined reference to `vtable for __cxxabiv1::__si_class_type_info'
> /data/home/bennshi/.cache/arduino/sketches/CEE06FE2D07E31C0BC8B101357BC67E2/core/core.a(Print.cpp.o):(.rodata._ZTI5Print+0x0): undefined reference to `vtable for __cxxabiv1::__class_type_info'
> clang: error: avr-ld command failed with exit code 1 (use -v to see invocation)

This error should be fixed by using the `-fno-rtti` compiler flag

> I have fixed the 2nd crash as [#132398](https://github.com/llvm/llvm-project/pull/132398), but a third error (a link failure) rised. I never thought building the simplest blink with clang is such that hard.

It indeed is, i suggest you to use my fork of the [core lib](https://github.com/ClangBuiltArduino/core_arduino_avr) instead which already contains all required fixes.

**Comment by dakkshesh07** [comment]
I just used a llvm build off of main branch at commit c51d396f4dec65bac24e00ace3f5ce5582d2c699 with https://github.com/llvm/llvm-project/pull/132398 applied. The compiler was able to compile the blink sketch with no issues even with expensive checks enabled but the program breakage still exists, with LTO enabled globally the LED blinks once and then gets stuck in ON state forever. Please let me know if you need any other information.

Looking at the LED behavior i think the issue could be isolated to the interrupts or the delay timer? Im not sure though.

**Comment by benshi001** [comment]
> > /data/home/bennshi/.cache/arduino/sketches/CEE06FE2D07E31C0BC8B101357BC67E2/core/core.a(HardwareSerial.cpp.o): In function `serialEventRun()': /data/home/bennshi/.arduino15/packages/arduino/hardware/avr/1.8.6/cores/arduino/HardwareSerial.cpp:(.text._Z14serialEventRunv+0xa): undefined reference to `serialEvent()'
> > /data/home/bennshi/.arduino15/packages/arduino/hardware/avr/1.8.6/cores/arduino/HardwareSerial.cpp:(.text._Z14serialEventRunv+0xc): undefined reference to `serialEvent()' /data/home/bennshi/.arduino15/packages/arduino/hardware/avr/1.8.6/cores/arduino/HardwareSerial.cpp:67: undefined reference to `serialEvent()'
> 
> These errors should be fixed using the following commits: [ClangBuiltArduino/core_arduino_avr@698ad5d](https://github.com/ClangBuiltArduino/core_arduino_avr/commit/698ad5d0f7b6f5147d01fd4c0a352d21bc6d5899) [ClangBuiltArduino/core_arduino_avr@9602bbb](https://github.com/ClangBuiltArduino/core_arduino_avr/commit/9602bbb2523eedbe1e8c7459659e3eb00781b000)
> 
> > /data/home/bennshi/.cache/arduino/sketches/CEE06FE2D07E31C0BC8B101357BC67E2/core/core.a(HardwareSerial.cpp.o):(.rodata._ZTI14HardwareSerial+0x0): undefined reference to `vtable for __cxxabiv1::__si_class_type_info' /data/home/bennshi/.cache/arduino/sketches/CEE06FE2D07E31C0BC8B101357BC67E2/core/core.a(HardwareSerial.cpp.o):(.rodata._ZTI6Stream[_ZTI6Stream]+0x0): undefined reference to `vtable for __cxxabiv1::__si_class_type_info'
> > /data/home/bennshi/.cache/arduino/sketches/CEE06FE2D07E31C0BC8B101357BC67E2/core/core.a(Print.cpp.o):(.rodata._ZTI5Print+0x0): undefined reference to `vtable for __cxxabiv1::__class_type_info'
> > clang: error: avr-ld command failed with exit code 1 (use -v to see invocation)
> 
> This error should be fixed by using the `-fno-rtti` compiler flag
> 
> > I have fixed the 2nd crash as [#132398](https://github.com/llvm/llvm-project/pull/132398), but a third error (a link failure) rised. I never thought building the simplest blink with clang is such that hard.
> 
> It indeed is, i suggest you to use my fork of the [core lib](https://github.com/ClangBuiltArduino/core_arduino_avr) instead which already contains all required fixes.

thanks. I will try your fork.

**Comment by benshi001** [comment]
> /home/dakkshesh/install/bin/llvm-ar rcs

BTW, I saw `/home/dakkshesh/install/bin/llvm-ar` is used during your build process, I guess it may be 
 the reason why LTO failed? because `clang -flto` emits LLVM byte code instead of relocatable ELF (which `avr-gcc` emits), so you have to use `llvm-link` instead of `llvm-ar` ?

**Comment by dakkshesh07** [comment]
> > /home/dakkshesh/install/bin/llvm-ar rcs
> 
> BTW, I saw `/home/dakkshesh/install/bin/llvm-ar` is used during your build process, I guess it may be the reason why LTO failed? because `clang -flto` emits LLVM byte code instead of relocatable ELF (which `avr-gcc` emits), so you have to use `llvm-link` instead of `llvm-ar` ?

I believe llvm-ar can handle LLVM bitcode? According to the [docs](https://github.com/llvm/llvm-project/blob/441c9a9273c5d040f218986bf301c8a5c4d4c011/llvm/docs/CommandGuide/llvm-ar.rst)

> The :program:`llvm-ar` command is similar to the common Unix utility, :program:`ar`. It archives several files, such as objects and LLVM bitcode files into a single archive library that can be linked into a program.

**Comment by benshi001** [comment]
> > > /home/dakkshesh/install/bin/llvm-ar rcs
> > 
> > 
> > BTW, I saw `/home/dakkshesh/install/bin/llvm-ar` is used during your build process, I guess it may be the reason why LTO failed? because `clang -flto` emits LLVM byte code instead of relocatable ELF (which `avr-gcc` emits), so you have to use `llvm-link` instead of `llvm-ar` ?
> 
> I believe llvm-ar can handle LLVM bitcode? According to the [docs](https://github.com/llvm/llvm-project/blob/441c9a9273c5d040f218986bf301c8a5c4d4c011/llvm/docs/CommandGuide/llvm-ar.rst)
> 
> > The :program:`llvm-ar` command is similar to the common Unix utility, :program:`ar`. It archives several files, such as objects and LLVM bitcode files into a single archive library that can be linked into a program.

I see. Your are correct 👍

**Comment by dakkshesh07** [comment]
Here are the bitcode and IR LTO intermediate files for the Blink sketch, these should help us analyze what LTO is doing.

[Blink-intermediate.zip](https://github.com/user-attachments/files/19407335/Blink-intermediate.zip)

**Comment by benshi001** [comment]
> > 1. Is there a instruction about how to build your `ClangBuiltArduino` project? Or I simply follow the arduino CLI way  ？
> 
> You can directly add the custom board package json and then install the custom board support to use it.
> 
> arduino-cli config add board_manager.additional_urls https://raw.githubusercontent.com/ClangBuiltArduino/BoardManagerFiles/refs/heads/main/package_clangbuiltarduino_index.json
> arduino-cli core update-index
> arduino-cli core install ClangBuiltArduino:avr
> arduino-cli compile -b ClangBuiltArduino:avr:mega $dir
> > 3. which version of  clang /llvm are you using? Is yours the newest main branch ?
> 
> I haven't updated the json since 20.1.0-rc2 build, I have a 20.1.0 build ready to be used. I will update the json and try once. I will also update toolchain scripts to add the ability to build off of main branch instead of release tarballs so that we can test bleeding edge builds.
> 
> Btw can you take a look at my llvm build configuration, maybe i disabled some crucial feature so I'm not getting those crashes? https://github.com/ClangBuiltArduino/tc-build/blob/main/llvm/build-llvm-stage2.sh#L63-L223
> 
> > I still failed build the simplest blink program with the above two crashes.
> 
> I will try to use the latest 20.1.0 build or main branch build to see if i can hit those crashes.

Unfortunately I got the following error with your tools.
```[bennshi@VM-78-142-tencentos ~]$ ./bin/arduino-cli compile -b ClangBuiltArduino:avr:mega ~/MyFirstSketch/
/data/home/bennshi/.arduino15/packages/ClangBuiltArduino/tools/cba-avr-bfd/2.44-14022025/glibc/bin/avr-ld: /data/home/bennshi/.arduino15/packages/ClangBuiltArduino/tools/cba-llvm/20.1.0-06032025/bin/../lib/LLVMgold.so: error loading plugin: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /data/home/bennshi/.arduino15/packages/ClangBuiltArduino/tools/cba-llvm/20.1.0-06032025/bin/../lib/LLVMgold.so)
clang++: error: avr-ld command failed with exit code 1 (use -v to see invocation)
Error: exit status 1

Used platform         Version Path
ClangBuiltArduino:avr 1.0.1   /data/home/bennshi/.arduino15/packages/ClangBuiltArduino/hardware/avr/1.0.1
Error during build: exit status 1
```

My CentOS-7 is too old.

**Comment by beakthoven** [comment]
> > > 1. Is there a instruction about how to build your `ClangBuiltArduino` project? Or I simply follow the arduino CLI way  ？
> > 
> > 
> > You can directly add the custom board package json and then install the custom board support to use it.
> > arduino-cli config add board_manager.additional_urls https://raw.githubusercontent.com/ClangBuiltArduino/BoardManagerFiles/refs/heads/main/package_clangbuiltarduino_index.json
> > arduino-cli core update-index
> > arduino-cli core install ClangBuiltArduino:avr
> > arduino-cli compile -b ClangBuiltArduino:avr:mega $dir
> > > 3. which version of  clang /llvm are you using? Is yours the newest main branch ?
> > 
> > 
> > I haven't updated the json since 20.1.0-rc2 build, I have a 20.1.0 build ready to be used. I will update the json and try once. I will also update toolchain scripts to add the ability to build off of main branch instead of release tarballs so that we can test bleeding edge builds.
> > Btw can you take a look at my llvm build configuration, maybe i disabled some crucial feature so I'm not getting those crashes? https://github.com/ClangBuiltArduino/tc-build/blob/main/llvm/build-llvm-stage2.sh#L63-L223
> > > I still failed build the simplest blink program with the above two crashes.
> > 
> > 
> > I will try to use the latest 20.1.0 build or main branch build to see if i can hit those crashes.
> 
> Unfortunately I got the following error with your tools.
> 
> ```
> /data/home/bennshi/.arduino15/packages/ClangBuiltArduino/tools/cba-avr-bfd/2.44-14022025/glibc/bin/avr-ld: /data/home/bennshi/.arduino15/packages/ClangBuiltArduino/tools/cba-llvm/20.1.0-06032025/bin/../lib/LLVMgold.so: error loading plugin: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /data/home/bennshi/.arduino15/packages/ClangBuiltArduino/tools/cba-llvm/20.1.0-06032025/bin/../lib/LLVMgold.so)
> clang++: error: avr-ld command failed with exit code 1 (use -v to see invocation)
> Error: exit status 1
> 
> Used platform         Version Path
> ClangBuiltArduino:avr 1.0.1   /data/home/bennshi/.arduino15/packages/ClangBuiltArduino/hardware/avr/1.0.1
> Error during build: exit status 1
> ```
> 
> My CentOS-7 is too old.

Ah thats a bummer, i compiled them against bookworm libs just to be sure i get good compatibility but i think thats not enough.
The main toolchain is statically linked against musl libc so i dont think you would face any issues with it, however the bfd linker and the LLVMgold.so are dynamically linked to support loading plugins dynamically.

I could try building the dynamically linked programs against older libs to have more compatibility. Or you could edit the platform.txt in the core lib dir to point to your tools instead so that you end up compiling my fork of the core lib with fixes but use your tools to compile it.

**Comment by beakthoven** [comment]
This mess could be properly mitigated later once LLD supports AVR linkerscript syntax.

**Comment by benshi001** [comment]
could  you  please  try to add option `-mno-relax` to clang in your config file? I find another bug triggered by this option, to avoid this bug   `-mno-relax` is needed when calling `avr-ld`.

**Comment by benshi001** [comment]
I have created another issue https://github.com/llvm/llvm-project/issues/133579 for that.

**Comment by beakthoven** [comment]
> could you please try to add option `-mno-relax` to clang in your config file? I find another bug triggered by this option, to avoid this bug `-mno-relax` is needed when calling `avr-ld`.
> 
> I am not sure if this option affect LTO result, maybe you can have a try, and let me known your result.

Well it actually did fix the issue with LTO enabled! I tried it on both 20.1.1 release build as well as on a bleeding edge build with recent bug fixes, It seems to work fine on both builds when `-mno-relax` is passed during the final linking phase.

I also tried adding back the serial functions to see if #128536 got resolved as well, but that issue still persists. None the less its a big step, i'll try to follow your follow up issue and see if i can debug anything.

> [@beakthoven](https://github.com/beakthoven) I really appreciate you, since I never thought llvm-avr can be such that fragile !!!

Yeah! This project has definitely been full of surprises, but at least we’re making progress. Appreciate your effort in digging into these issues!

**Comment by benshi001** [comment]
So can this issue and https://github.com/llvm/llvm-project/issues/128536 be closed? Let us continue our discuss in https://github.com/llvm/llvm-project/issues/133579 or any further issue you may encounter.

**Comment by benshi001** [comment]
I closed this issue, and let us continue out discuss in https://github.com/llvm/llvm-project/issues/128536 and https://github.com/llvm/llvm-project/issues/133579. You are welcome to create any further issues if you encounter more clang/llvm bugs in the future.

**Comment by benshi001** [comment]
LTO has not been fixed, let us continue related discuss in the thread.

**Comment by benshi001** [comment]
@beakthoven 
According to my test, LTO+blink or nonLTO+Seral both work, only LTO+Serial is broken, due to corruption in the global `Serial` object's initialization.

Could you please confirm that ?

**Comment by beakthoven** [comment]
> [@beakthoven](https://github.com/beakthoven) According to my test, LTO+blink or nonLTO+Seral both work, only LTO+Serial is broken, due to corruption (caused by LTO) in the global `Serial` object's initialization.
> 
> Could you please confirm that ? of course `-mno-relax` is still needed.

Yes, i get the same results with my tests as well.

**Comment by benshi001** [comment]
OK, I see. My conclusion is:

The global object `Serial` contains v-table which holds its virtual methods addresses, since the v-table is not initialized correctly, then any call to those virtual methods will make program wild.

**Comment by beakthoven** [comment]
> OK, I see. My conclusion is:
> 
> The global object `Serial` contains v-table which holds its virtual methods addresses, since the v-table is not initialized correctly, then any call to those virtual methods will make program wild.

Umm I tried removing the virtual keyword, the same issue remains. Can you once check if we are losing any important section during dead code elimination. Try passing `-Wl,--print-gc-sections' to final link.

**Comment by benshi001** [comment]
I got 
```bash
/data/home/bennshi/.cache/arduino/sketches/BE3E4C349D44E43682DADB9640B8B5A5/sketch/test.ino.cpp
/data/home/bennshi/.arduino15/packages/arduino/tools/avr-gcc/usr/lib/gcc/avr/7.3.0/../../../../bin/avr-ld: Removing unused section '.text.avr-libc.fplib' in file '/data/home/bennshi/.arduino15/packages/arduino/tools/avr-gcc/usr/lib/gcc/avr/7.3.0/../../../../avr/lib/avr5/libm.a(isinf.o)'
/data/home/bennshi/.arduino15/packages/arduino/tools/avr-gcc/usr/lib/gcc/avr/7.3.0/../../../../bin/avr-ld: Removing unused section '.text.avr-libc.fplib' in file '/data/home/bennshi/.arduino15/packages/arduino/tools/avr-gcc/usr/lib/gcc/avr/7.3.0/../../../../avr/lib/avr5/libm.a(isnan.o)'
/data/home/bennshi/.arduino15/packages/arduino/tools/avr-gcc/usr/lib/gcc/avr/7.3.0/../../../../bin/avr-ld: Removing unused section '.text.avr-libc.fplib' in file '/data/home/bennshi/.arduino15/packages/arduino/tools/avr-gcc/usr/lib/gcc/avr/7.3.0/../../../../avr/lib/avr5/libm.a(fp_split3.o)'
/data/home/bennshi/.arduino15/packages/arduino/tools/avr-gcc/usr/lib/gcc/avr/7.3.0/../../../../bin/avr-ld: Removing unused section '.text.avr-libc' in file '/data/home/bennshi/.arduino15/packages/arduino/tools/avr-gcc/usr/lib/gcc/avr/7.3.0/../../../../avr/lib/avr5/libc.a(abort.o)'
/data/home/bennshi/.arduino15/packages/arduino/tools/avr-gcc/usr/lib/gcc/avr/7.3.0/../../../../bin/avr-ld: Removing unused section '.text.avr-libc' in file '/data/home/bennshi/.arduino15/packages/arduino/tools/avr-gcc/usr/lib/gcc/avr/7.3.0/../../../../avr/lib/avr5/libc.a(strlen.o)'
/data/home/bennshi/.arduino15/packages/arduino/tools/avr-gcc/usr/lib/gcc/avr/7.3.0/../../../../bin/avr-ld: Removing unused section '.text._ZN14HardwareSerial9availableEv' in file '/tmp/lto-llvm-08f1fb.o'
/data/home/bennshi/.arduino15/packages/arduino/tools/avr-gcc/usr/lib/gcc/avr/7.3.0/../../../../bin/avr-ld: Removing unused section '.text._ZN14HardwareSerial4peekEv' in file '/tmp/lto-llvm-08f1fb.o'
/data/home/bennshi/.arduino15/packages/arduino/tools/avr-gcc/usr/lib/gcc/avr/7.3.0/../../../../bin/avr-ld: Removing unused section '.text._ZN14HardwareSerial4readEv' in file '/tmp/lto-llvm-08f1fb.o'
/data/home/bennshi/.arduino15/packages/arduino/tools/avr-gcc/usr/lib/gcc/avr/7.3.0/../../../../bin/avr-ld: Removing unused section '.text._ZN14HardwareSerial17availableForWriteEv' in file '/tmp/lto-llvm-08f1fb.o'
/data/home/bennshi/.arduino15/packages/arduino/tools/avr-gcc/usr/lib/gcc/avr/7.3.0/../../../../bin/avr-ld: Removing unused section '.text._ZN14HardwareSerial5flushEv' in file '/tmp/lto-llvm-08f1fb.o'
/data/home/bennshi/.arduino15/packages/arduino/tools/avr-gcc/usr/lib/gcc/avr/7.3.0/../../../../bin/avr-ld: Removing unused section '.text._ZN14HardwareSerial5writeEh' in file '/tmp/lto-llvm-08f1fb.o'
/data/home/bennshi/.arduino15/packages/arduino/tools/avr-gcc/usr/lib/gcc/avr/7.3.0/../../../../bin/avr-ld: Removing unused section '.text._GLOBAL__sub_I_HardwareSerial0.cpp' in file '/tmp/lto-llvm-08f1fb.o'
/data/home/bennshi/.arduino15/packages/arduino/tools/avr-gcc/usr/lib/gcc/avr/7.3.0/../../../../bin/avr-ld: Removing unused section '.text._ZN5Print5writeEPKhj' in file '/tmp/lto-llvm-08f1fb.o'
/data/home/bennshi/.arduino15/packages/arduino/tools/avr-gcc/usr/lib/gcc/avr/7.3.0/../../../../bin/avr-ld: Removing unused section '.init_array' in file '/tmp/lto-llvm-08f1fb.o'
/data/home/bennshi/.arduino15/packages/arduino/tools/avr-gcc/usr/lib/gcc/avr/7.3.0/../../../../bin/avr-ld: Removing unused section '.rodata._ZTV14HardwareSerial' in file '/tmp/lto-llvm-08f1fb.o'
```

**Comment by benshi001** [comment]
> moving the virtual keyword, the same issue remains. Can you once check if we are losing any important section during dead code elimination. Try passing `-Wl,--print-gc-sections' to final link.

This LTO issue seems more complex than I previously thought.

Is there any other issue that block you? I mean I will try some quick fixes for any blocking issues, such as what I did for https://github.com/llvm/llvm-project/issues/132203.

All those following issues (including LTO) are complex, I need more time to fix their root causes.

https://github.com/llvm/llvm-project/issues/133579
https://github.com/llvm/llvm-project/issues/132203
https://github.com/llvm/llvm-project/issues/127651
