### ISSUE TITLE
Unprofitable loop vectorization

### ISSUE THREAD

**Issue by nikic** [llvm/llvm-project#128062]
LoopVectorize generates something really bad here, with lots of element-wise loads, inserts, extracts and stores. Letting it fall through to SLP generates much better code.

LoopVectorize: https://llvm.godbolt.org/z/dPcEedY1v
SLPVectorizer: https://llvm.godbolt.org/z/33d31djno

**Comment by fhahn** [comment]
I think this should be fixed by https://github.com/llvm/llvm-project/pull/106441 or by a slightly generalization of it.

**Comment by fhahn** [comment]
(https://github.com/llvm/llvm-project/pull/106441 should land soon)

**Comment by artagnon** [comment]
I don't think this is fixed by #106441.

**Comment by nikic** [comment]
@fhahn As https://github.com/llvm/llvm-project/pull/106441 did not fix this, any idea on what more would be needed here?

**Comment by sftlbcn** [comment]
doesn't look fixed

**Comment by artagnon** [comment]
A target needs to be supplied: https://llvm.godbolt.org/z/j36ejGsx6.

**Comment by nikic** [comment]
@artagnon https://llvm.godbolt.org/z/dPcEedY1v does have a target, which is x86 with avx2. It doesn't look like the issue is fixed, so reopening.
