### ISSUE TITLE
`__builtin_constant_p` incorrect with undefined variables

### ISSUE THREAD

**Issue by kees** [llvm/llvm-project#130649]
Given this situation:

```c
// -O2 -Wall
extern void knowable(void);
extern void unknowable(void);

void test(void)
{
    char buf[8];

    // The end of "buf" is undefined. That shouldn't make
    // __builtin_constant_p() undefined nor true, though.
    // It should just be false.
    if (__builtin_constant_p(buf[sizeof(buf)-1])) {
        knowable();
    } else {
    	unknowable();
    }
}
```

Clang is incorrectly resolving `__builtin_constant_p()` to `true` (or `undefined`) instead of `false`. GCC correctly resolves it to `false` (and emits a warning about using `buf` uninitialized).

Isolated from ClangBuiltLinux: https://github.com/ClangBuiltLinux/linux/issues/2073

Providing an initializer to `buf` makes this go away (in the sense that now it is correctly "knowable"). GCC flips over to `knowable()`:

```
    char buf[8] = "";
```

**Comment by efriedma-quic** [comment]
Even if we did change constant folding to fold `llvm.is.constant.i32(i32 undef)` to fold to false, I don't think that reliably helps you.  We don't, in general, preserve the undef-ness of a value in optimizations, so any optimization could flip it to true.  Given that, I don't see any way to reliably fix this.

Is there any way you can write your code so it doesn't involve reading uninitialized memory?

**Comment by kees** [comment]
Well, the code isn't trying to directly read a value, it's trying to check the "known to be a constant value" state of the variable so it can guide the code-gen (generally via DCE) toward either a compile-time constant codegen vs needing runtime calculation codegen. And I don't think it's too unreasonable that `undef` is analyzed here given that `__buitin_constant_p()` doesn't allow "side effects". I would count "reading the value" to be a side effect here (e.g. the value is not accessible nor used by `__builtin_constant_p()` nor its caller).

So I guess I'm saying, yes, let's do that constant folding since the value isn't needed (i.e. undef-ness preservation doesn't seem like something that would be a problem here, but perhaps I lack imagination).

**Comment by kees** [comment]
Hm, is it really as simple as this?

```diff
diff --git a/llvm/lib/IR/Constants.cpp b/llvm/lib/IR/Constants.cpp
index 9e3e739fae3d..36f413645761 100644
--- a/llvm/lib/IR/Constants.cpp
+++ b/llvm/lib/IR/Constants.cpp
@@ -841,6 +841,8 @@ Constant *Constant::mergeUndefsWith(Constant *C, Constant *Other) {
 }
 
 bool Constant::isManifestConstant() const {
+  if (isa<UndefValue>(this))
+    return false;
   if (isa<ConstantData>(this))
     return true;
   if (isa<ConstantAggregate>(this) || isa<ConstantExpr>(this)) {
```

A simple test works ... Attempting a full kernel build now.

**Comment by kees** [comment]
Yes, that fixes the ClangBuiltLinux bug and everything else appears to continue working correctly. I will write some tests and get a PR posted. Thank you for the hints for the name to track down was! (`llvm.is.constant` led me ultimately to `Constant::isManifestConstant()`)

**Comment by zygoloid** [comment]
I don't think this change gives the behavior you're expecting. For example, consider this change to your testcase:

```c
// -O2 -Wall
extern void knowable(void);
extern void unknowable(void);

extern bool always_returns_false(void);

void test(void)
{
    char buf[8];

    if (always_returns_false()) {
      buf[7] = 0;
    }

    // The end of "buf" is undefined. That shouldn't make
    // __builtin_constant_p() undefined nor true, though.
    // It should just be false.
    if (__builtin_constant_p(buf[sizeof(buf)-1])) {
      knowable();
    } else {
    	unknowable();
    }
}
```

If this worked as you expected, this would still call `unknowable()`. But it [calls `knowable()`, with both Clang trunk and GCC](https://godbolt.org/z/n4oxfYdTK).

Fundamentally, the source code in question is wrong. The operand to `__builtin_constant_p` has undefined behavior, so at best, the result of `__builtin_constant_p` is not specified, and we probably can't guarantee anything about the behavior of the function in general.

**Comment by shafik** [comment]
Based on @zygoloid comment, I don't think we really fully understand the semantics you want here. I don't think the patch had sufficient review, at least if I am understanding the feedback.

Maybe we should flush out the semantics fully and then implement what folks agree makes sense b/c it does not sounds like @zygoloid feels like this makes sense.

**Comment by zygoloid** [comment]
I don't think there's anything wrong with the change that was made -- evaluating to false rather than true here seems fine -- but I don't think we can give any guarantees about what happens in this case, so no-one should be relying on this. The kennel source code doing this should be fixed.

**Comment by shafik** [comment]
> I don't think there's anything wrong with the change that was made -- evaluating to false rather than true here seems fine -- but I don't think we can give any guarantees about what happens in this case, so no-one should be relying on this. The kennel source code doing this should be fixed.

That is my problem, if we don't have a guaranteed semantic, then why are we making this change for? It feels rather arbitrary from that perspective.

**Comment by kees** [comment]
Right, my example was a heavily minimized version of what Linux is doing. Here's a more complete dump, scraped together from various headers. The purpose is to provide compile-time analysis for the inlines to avoid needless calls to `strlen` when it is known at compile time, while building the bounds checking up around `strlen` and `strnlen` so that they can be efficiently reused in other fortified places, like `strcpy`, `snprintf`, etc. The macro that broke on Clang was `__compiletime_strlen()` below. Notably this is used to identify `const char *` strings that are not Constant Expressions, but for which compile-time analysis is still possible. There isn't any use of undefined variables -- that is precisely what `__builtin_constant_p()` is used to determine: "can we know the content here?" If so, use `__builtin_strlen()` which will optimize out to a integer, otherwise return `SIZE_MAX` to indicate that the length must be determined with a full run-time call to the fortified `strnlen`, etc, etc.

```c
#define __kernel_size_t size_t

// For details on this bad boy, see:
// https://web.git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/include/linux/compiler.h?h=v6.13#n270
#define __is_constexpr(x) \
        (sizeof(int) == sizeof(*(8 ? ((void *)((long)(x) * 0l)) : (int *)8)))

#define __always_inline                 inline __attribute__((__always_inline__))
#define __gnu_inline                    __attribute__((__gnu_inline__))
# define __overloadable                 __attribute__((__overloadable__))
#define __FORTIFY_INLINE extern __always_inline __gnu_inline __overloadable
#define __RENAME(x) __asm__(#x)

#define __diagnose_as(builtin...)      __attribute__((__diagnose_as_builtin__(builtin)))

# define __pass_dynamic_object_size(type)       __attribute__((__pass_dynamic_object_size__(type)))
#define POS                     __pass_dynamic_object_size(1)
#define __member_size(p)       __builtin_dynamic_object_size(p, 1)

#define __cold                         __attribute__((__cold__))
#define __noreturn                      __attribute__((__noreturn__))
void __fortify_panic(const u8 reason, const size_t avail, const size_t size) __cold __noreturn;

#define __compiletime_strlen(p)                                 \
({                                                              \
        char *__p = (char *)(p);                                \
        size_t __ret = SIZE_MAX;                                \
        const size_t __p_size = __member_size(p);               \
        if (__p_size != SIZE_MAX &&                             \
            __builtin_constant_p(*__p)) {                       \
                size_t __p_len = __p_size - 1;                  \
                if (__builtin_constant_p(__p[__p_len]) &&       \
                    __p[__p_len] == '\0')                       \
                        __ret = __builtin_strlen(__p);          \
        }                                                       \
        __ret;                                                  \
})

extern __kernel_size_t __real_strnlen(const char *, __kernel_size_t) __RENAME(strnlen);
__FORTIFY_INLINE __kernel_size_t strnlen(const char * const POS p, __kernel_size_t maxlen)
{
        const size_t p_size = __member_size(p);
        const size_t p_len = __compiletime_strlen(p);
        size_t ret;

        /* We can take compile-time actions when maxlen is const. */
        if (__builtin_constant_p(maxlen) && p_len != SIZE_MAX) {
                /* If p is const, we can use its compile-time-known len. */
                if (maxlen >= p_size)
                        return p_len;
        }

        /* Do not check characters beyond the end of p. */
        ret = __real_strnlen(p, maxlen < p_size ? maxlen : p_size);
        if (p_size <= ret && maxlen != ret)
                fortify_panic(FORTIFY_FUNC_strnlen, FORTIFY_READ, p_size, ret + 1, ret);
        return ret;
}

#define strlen(p)                                                       \
        __builtin_choose_expr(__is_constexpr(__builtin_strlen(p)),      \
                __builtin_strlen(p), __fortify_strlen(p))
__FORTIFY_INLINE __diagnose_as(__builtin_strlen, 1)
__kernel_size_t __fortify_strlen(const char * const POS p)
{
        const size_t p_size = __member_size(p);
        __kernel_size_t ret;

        /* Give up if we don't know how large p is. */
        if (p_size == SIZE_MAX)
                return __underlying_strlen(p);
        ret = strnlen(p, p_size);
        if (p_size <= ret)
                fortify_panic(FORTIFY_FUNC_strlen, FORTIFY_READ, p_size, ret + 1, ret);
        return ret;
}
```

**Comment by efriedma-quic** [comment]
> There isn't any use of undefined variables 

The expression `__p[__p_len]` is a use of an uninitialized variable. The compiler does not, in general, preserve whether a variable is uninitialized.  Even if we say `__builtin_constant_p(__p[__p_len])` isn't undefined behavior because the "use" of `__p` doesn't count, that doesn't help.  The issue is that the result of `__builtin_constant_p(__p[__p_len])` is unpredictable.  Your patch doesn't fix this, so the Linux kernel will break in the future.  I don't have time right now to write an example for you.

**Comment by dzaima** [comment]
I'd say at the core of the issue on the actual UB in [the linux reproducer](https://github.com/ClangBuiltLinux/linux/issues/2073#issuecomment-2710789925) is that the pattern `if (__builtin_constant_p(x)) { use(x); }` doesn't guarantee that the `x` in `use(x)` is a well-defined value (derived from the fact that optimizations needn't apply equally to both `x`es, so in `__builtin_constant_p(x)` any pass is entirely free to replace an undef `x` with any fixed constant value, while leaving `use(x)` having an undef `x`).

The best that might be possible for solving that would be doing `if (__builtin_constant_p(x)) { use(freeze(x)); }` (perhaps as a combined `if_constant (auto x_frozen = x) { use(x_frozen); }` or something), achieving a way to branch on hints without catastrophic failure, but clang doesn't expose `freeze`, and it wouldn't help cases where it's non-trivial to not use the original `x` (and it wouldn't help cases where you categorically don't want to accept values that ever were undef, but those cannot be helped in general anyway).

**Comment by zygoloid** [comment]
Here's a case where that `__compiletime_strlen ` macro misbehaves with Clang trunk (by making a runtime call to `strlen`): https://godbolt.org/z/svsne7b8o

**Comment by kees** [comment]
> Here's a case where that `__compiletime_strlen ` macro misbehaves with Clang trunk (by making a runtime call to `strlen`): https://godbolt.org/z/svsne7b8o

This case seems fine to me -- falling back to runtime strlen() is okay. Eliding an entire function because Clang thinks undef values are in use is not okay. ;)

But the specific case I'm trying to catch is `const char *str` where `str` is known. It doesn't resolve as a Constant Expression, but optimization will correctly figure it out.

This should be more clear from an excerpt from Linux's unit testing of this aspect of the FORTIFY_SOURCE support:

```c
static const char array_of_10[] = "this is 10";
static const char *ptr_of_11 = "this is 11!";
static const char * const unchanging_12 = "this is 12!!";
static char array_unknown[] = "compiler thinks I might change";

static void fortify_test_known_sizes(struct kunit *test)
{
        char stack[80] = "Test!";

        KUNIT_EXPECT_FALSE(test, __is_constexpr(__builtin_strlen(stack)));
        KUNIT_EXPECT_EQ(test, __compiletime_strlen(stack), 5);

        KUNIT_EXPECT_TRUE(test, __is_constexpr(__builtin_strlen("88888888")));
        KUNIT_EXPECT_EQ(test, __compiletime_strlen("88888888"), 8);

        KUNIT_EXPECT_TRUE(test, __is_constexpr(__builtin_strlen(array_of_10)));
        KUNIT_EXPECT_EQ(test, __compiletime_strlen(array_of_10), 10);

        KUNIT_EXPECT_FALSE(test, __is_constexpr(__builtin_strlen(ptr_of_11)));
        KUNIT_EXPECT_EQ(test, __compiletime_strlen(ptr_of_11), 11);

        KUNIT_EXPECT_TRUE(test, __is_constexpr(__builtin_strlen(unchanging_12)));
        KUNIT_EXPECT_EQ(test, __compiletime_strlen(unchanging_12), 12);

        KUNIT_EXPECT_FALSE(test, __is_constexpr(__builtin_strlen(array_unknown)));
        KUNIT_EXPECT_EQ(test, __compiletime_strlen(array_unknown), SIZE_MAX);

        /* Externally defined and dynamically sized string pointer: */
        KUNIT_EXPECT_FALSE(test, __is_constexpr(__builtin_strlen(test->name)));
        KUNIT_EXPECT_EQ(test, __compiletime_strlen(test->name), SIZE_MAX);
}
```

The whole reason for `__compiletime_strlen()` boils down to the `ptr_of_11` test above. `__builtin_strlen()` is *not* a constant expression, but `__builtin_strlen()` *will* ultimately resolve to a literal value. FORTIFY_SOURCE isn't able to do compile-time analysis of a lot of strings without this, which is why `__compiletime_strlen()` was developed. Otherwise we could just do:

```c
#define __compiletime_strlen(p) \
        __builtin_choose_expr(__is_constexpr(__builtin_strlen(p)), __builtin_strlen(p), SIZE_MAX)
```

But then coverage is reduced.

**Comment by efriedma-quic** [comment]
So, in the expression `__builtin_constant_p(__p[__p_len]) && __p[__p_len] == '\0'`... ideally __builtin_constant_p is false if the value is undef.  If both instances of `__p[__p_len]` fold to zero when the value is actually undef, you lose fortification.  If `__builtin_constant_p(__p[__p_len])` is true, and `__p[__p_len]` folds to undef, you get the miscompile.

I guess that's sort of unlikely to happen in the normal optimization pipeline because EarlyCSE will fold the two instances of `__p[__p_len]` together.  But that isn't something we promise anywhere; you're just getting lucky.

**Comment by kees** [comment]
Yeah, this part (that `__p[__p_len]` inside and outside of `__builtin_constant_p()` can be evaluated to different states) is certainly worrying, and I see why it is possible in Clang. I do find the earlier observation, "any pass is entirely free to replace an undef x with any fixed constant value" to be surprising. Why can it be legal to replace an undefined value with a _constant_ value? That seems very dangerous.

But anyway, I would rather avoid any chance of touching UB (which was my goal with the `__builtin_constant_p()` use). Does anyone see a way to answer the question, at compile-time, of "is this `const char` pointer pointing into a location that we: 

1. know the size of the object (currently answered with `__builtin_dynamic_object_size(ptr, 1) != SIZE_MAX`)
2. know the contents exist and we will get a fixed value out of `__builtin_strlen()` (currently answered with the "check for constant [0]")
3. without running past the end of the buffer (currently answered with "check for constant [size-1] and that it is a NUL byte")

It seems there isn't a way to say "is this variable defined?" It appeared as though `__builtin_constant_p()` did this for both GCC and Clang, right up until I got "unlucky" with 1 function out of 70,000 in Linux. ;)

**Comment by zygoloid** [comment]
> I do find the earlier observation, "any pass is entirely free to replace an undef x with any fixed constant value" to be surprising. Why can it be legal to replace an undefined value with a _constant_ value?

Why wouldn't it be legal? "Constant" here just means that LLVM knows what the value is. Requiring that optimizers never know (or rather, choose) what the value is would remove a lot of the value of undef.

> But anyway, I would rather avoid any chance of touching UB (which was my goal with the `__builtin_constant_p()` use). Does anyone see a way to answer the question, at compile-time, of "is this `const char` pointer pointing into a location that we:
> 
> 1. know the size of the object (currently answered with `__builtin_dynamic_object_size(ptr, 1) != SIZE_MAX`)
> 2. know the contents exist and we will get a fixed value out of `__builtin_strlen()` (currently answered with the "check for constant [0]")
> 3. without running past the end of the buffer (currently answered with "check for constant [size-1] and that it is a NUL byte")

I think what you're asking for (specifically the third part) is impossible. There's no way to write a predicate that is true when `*p == 0` but false when `*p` is uninitialized, because a program where `*p` is uninitialized can be refined to one where the value observed is 0.

Can you assume that `__builtin_strlen` -- or at least `__builtin_strnlen` -- would have defined behavior? If so, you could probably build something using `__builtin_constant_p(__builtin_strlen(ptr))`.

**Comment by dzaima** [comment]
> Why can it be legal to replace an undefined value with a _constant_ value? That seems very dangerous.

Optimization passes are about making the program faster, not making it less dangerous (though even then I'd argue replacing undefined values with constant values is the opposite of dangerous).

As such, to the optimizer, `undef` is a "the programmer doesn't care what the value here is" and it can thus make the value be whatever is most efficient; without optimizations that might be "whatever's on the stack/some register", but e.g. [here](https://godbolt.org/#z:OYLghAFBqd5TKALEBjA9gEwKYFFMCWALugE4A0BIEAZgQDbYB2AhgLbYgDkAjF%2BTXRMiAZVQtGIHgBYBQogFUAztgAKAD24AGfgCsp5eiyagA%2BudTkVjVEQJDqzTAGF09AK5smIAEzknADIETNgAcp4ARtikIABs5AAO6ErE9kyuHl6%2BicmpQkEh4WxRMfHW2LZpIkQspEQZnt5%2B5ZVC1bVEBWGR0XFWNXUNWc0DncHdxb2xAJRW6O6kqJxcwUQA1ILoEBHobmsYTJjTawCkAOwAQidaAIJr92urawBuEu7YJwDMV7cPjzRrCAHI4vN7YU6fAAiax4Pk%2BXx%2BN2udwepGwRAWTFBHg%2B32R50hXFm9G4AFZ%2BN4uDpyOhuM41kp5otwSc4XxyERtETZgBrECk6QAOi0pIAnKTYjxYQAOUk%2BWKxaTxElcaT8Nj8rTkSnU2lcfhKEBazlUonkOCwFAEChUCBcAC0NCY6HthCU4lImHtrxx9tYHCUXC55AwbASDGioXYy3U0ti9sV%2ByMJkBRFI7iYPOm/BwbGMwEY9qUAE9im5Dab/IQSKQCJgDHR6ERovaWEQ0wQIu5mxXqY3m6R7aGOMJe/x%2By2cF3gPbgoJgxPB8ElGn3K0mPaODVMG2WAv5GIJJwZHJhMo1JpK/pmtgbHYHBAnENvDx/IcukUSgYkil7%2Bk3I0365H%2BH49DEr4tH%2B7SDABWQQbeFRQaMoGTOB/QdM%2BBgrh0KFfjwsxptg2B1ka5AAO6kCwCTcHwxJkhSwZ6gEAQAGoALJrAAkgASmsLEENgZHRGssbxomqDJsAqbppmxwQPgxBkKcbLkGsrhhhGpDKZ8PjZhyXLTLMSDYCwOAxBAdGquqmraox3AGqRJo6IZ5B8gKwpihKUo%2BLK8qKsq3CfAxlZ6vwTlmhaCDwBAKChuGjA2tQcWaWgwBKKwCRKEg6BEAIDADoa2zBhEwS1MWNH8CVrCkMWADyES6IhFUhugbAjkQtVMPQ5WVlO7jAM4Ej0BW7K5vmki9daiEEM82Bjv46gVN2yzsqst7BvQnaUTVrg4MGHYarw/CzaQOwqJC2B5iYm0mAZAhGGl/GCbVCTMM1gjCIekgnh9igqBowb6K%2BkkgOYpiWJtESGpAszoAkf4VvatWfGsRZEJgXyQqgcL8OgJ21jg0MWVYCHro4hyYa%2BgTjJ%2BvSvj%2BeT/pkL45L%2BaS4XTJN3lUoyU1z01tMhNNgVhvOwSz2F1Bz4GzIyCxLFIlnkrZIXcCJcYJtIazAKgqDSRmWaAgpNbafhYUGbyIDSKSgqitIWjSJ80rSmcMhnJ8nykoY3BquQGqklqOq4/ZViOXdkUxWgrXxdElBJdHKW65JpirpmeVNtEhURMVpU1c1VVlfVjW2M1w7MB1XU9dSfUDUNI05pd43LNXU2VLN83YItqDLc1a0qtSkPbcWu3N2FtaHeyJ1ndgF1XQWwSgKasw0A9ShPWRL1vUdp6iOI32yL954A1e2Qg2DEOdkTsPw2kiPI6jK4Y1C2NBTS%2BN1nN8Cy6Tf7ky44sGGpoUEW9NgJpD5gzECwtUJYR/jzDCAD4Lc0FjhaBeF0IwWZqLVBwCYH4TmPLY8Stgq6jVqJTWSZ8z61kkbasSlWSfDNvpJeRkTJmWoJZX2/tA52X1KHY0FtXJWxtnbB2TsXZuw9l7FUr8g40hDuFFyKofAkODnwxRswTopAcNIIAA%3D%3D) it's just decided that setting the undefined value when `!cond` to `123` is most efficient, avoiding any need to involve `cond`; and that's indeed the efficient thing to do (in real cases stuff like this likely happening from macros/inlining making the undef usage in practice unreachable, but without the compiler being able to figure that out, so it's stuck just making the undef case nicer).

While just plain replacing `undef` by itself with a constant value is probably not particularly useful, it's nevertheless a valid transformation, as making it illegal would necessarily mean the `123` optimization, along with tons of other stuff, would also become illegal. Though, on the topic of safety, `-ftrivial-auto-var-init=zero` is an extremely literal case of taking all undefined variables and defining them to be exactly a constant `0`. (gcc seems to do this after optimizations, but clang does it before them)

> I think what you're asking for (specifically the third part) is impossible. There's no way to write a predicate that is sometimes true when `*p == 0` but always false when `*p` is uninitialized, because a program where `*p` is uninitialized can be refined to one where the value observed is 0.

While it's impossible from C AFAIK, with my previous mention of `freeze` at the LLVM IR level that could look like: `freeze`ing the entire memory range of the string (or a copy of it into a temp buffer), checking `the_frozen_memory[end] == 0`, and then running `__builtin_strlen` on the frozen memory, semantically achieving running strlen without any possibility of any UB, all from regular LLVM IR. Of course, freezing a memory range requires a loop and thus would probably (untested) break constant-folding which is the entire point here, and isn't doable from C.
