### ISSUE TITLE
[clang-tidy] How to specify multiple values for a key?

### ISSUE THREAD

**Issue by shrek1402** [llvm/llvm-project#53517]
Is it possible to specify multiple values for a key? Something like this:
```
CheckOptions:
  - key:   readability-identifier-naming.AbstractClassCase
    value: 'lower_case', 'UPPER_CASE'
  - key:   readability-identifier-naming.StructPrefix
    value: '_', '' # '_' or empty
```

**Comment by njames93** [comment]
There is no way to use multiple values for an option as in the common case it doesn't make sense. There are some options for checks which take semicolon separated lists.
For your case here it doesn't make sense to specify multiple styles and would remove the ability for that check to create fix-its. Maybe there is merit for the check to have a preferred style, but optionally ignore a different style pattern, but I'm not too sure how often that would come up in the wild

**Comment by firewave** [comment]
I came across this in the past with enums. There was an existing code base before the check was enforced and the enums had different naming style based on their usage. Enums used in place of constants were in `UPPER_CASE` and ones used as parameters to functions or used for bitfields were in `CamelCase`. So we had to use `aNy_CasE` and had to make sure that the naming was enforced by manual review.

This could have been fixed along the line by converting the constants pack to such and using `namespace` or `class` as a grouper. Than we would have lost the `-Wswitch` diagnostic for those. Also they part of library interfaces so the existing ones would have been kept for compatibility and required `NOLINT`. And the latter is never great in external headers.

**Comment by Febbe** [comment]
I am also interested having multiple values for `readability-identifier-naming`

@njames93 "remove the ability for that check to create fix-its"
Not directly, fix-its could be supplied as a list, so the user can choose.
For automatic fix-its, a preferred fix-it could be selected.

**Comment by shrek1402** [comment]
It would be nice to have such an opportunity.

**Comment by njames93** [comment]
I still don't think it's wise to create this infrastructure. For cases where header files use a different style, there is the [GetConfigPerFile](https://clang.llvm.org/extra/clang-tidy/checks/readability-identifier-naming.html#cmdoption-arg-getconfigperfile) option.
Then there is the *IgnoreRegexp options which can be tailored to ignore another style

**Comment by shrek1402** [comment]
Okay, I have to agree that this is a bad idea :D In general, it is bad to have different styles for the same type. It seems more logical to use only one type than to make a hash of it is not clear why
