### ISSUE TITLE
Assertion failure in clang-tidy bugprone-sizeof-expression with __int128_t

### ISSUE THREAD

**Issue by davidstone** [llvm/llvm-project#53963]
The following valid translation unit

```
template<__int128_t x>
void f() {
	x < 0;
}

void g() {
	f<-1>();
}
```

causes clang-tidy to crash when invoked with `clang-tidy main.cpp --checks='-*,bugprone-sizeof-expression'`

with the following message:

```
clang-tidy: /home/david/llvm/llvm/include/llvm/ADT/APInt.h:1487: uint64_t llvm::APInt::getZExtValue() const: Assertion `getActiveBits() <= 64 && "Too many bits for uint64_t"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.      Program arguments: /home/david/llvm/build/bin/clang-tidy main.cpp --checks=-*,bugprone-sizeof-expression
1.      <eof> parser at end of file
 #0 0x000055a0166e3f81 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/home/david/llvm/build/bin/clang-tidy+0x1abbf81)
 #1 0x000055a0166e1b9e llvm::sys::RunSignalHandlers() (/home/david/llvm/build/bin/clang-tidy+0x1ab9b9e)
 #2 0x000055a0166e4676 SignalHandler(int) Signals.cpp:0:0
 #3 0x00007f6dd7515560 __restore_rt libc_sigaction.c:0:0
 #4 0x00007f6dd756234c __pthread_kill_implementation pthread_kill.c:0:0
 #5 0x00007f6dd75154b8 gsignal (/usr/lib/libc.so.6+0x424b8)
 #6 0x00007f6dd74ff534 abort (/usr/lib/libc.so.6+0x2c534)
 #7 0x00007f6dd74ff45c _nl_load_domain.cold loadmsgcat.c:0:0
 #8 0x00007f6dd750e116 (/usr/lib/libc.so.6+0x3b116)
 #9 0x000055a016ee88db clang::tidy::bugprone::(anonymous namespace)::internal::matcher_isBiggerThan0Matcher::matches(clang::IntegerLiteral const&, clang::ast_matchers::internal::ASTMatchFinder*, clang::ast_matchers::internal::BoundNodesTreeBuilder*) const SizeofExpressionCheck.cpp:0:0
#10 0x000055a016dc3d7d clang::ast_matchers::internal::MatcherInterface<clang::IntegerLiteral>::dynMatches(clang::DynTypedNode const&, clang::ast_matchers::internal::ASTMatchFinder*, clang::ast_matchers::internal::BoundNodesTreeBuilder*) const DurationFactoryScaleCheck.cpp:0:0
#11 0x000055a016d43d02 clang::ast_matchers::internal::DynTypedMatcher::matches(clang::DynTypedNode const&, clang::ast_matchers::internal::ASTMatchFinder*, clang::ast_matchers::internal::BoundNodesTreeBuilder*) const (/home/david/llvm/build/bin/clang-tidy+0x211bd02)
#12 0x000055a016d486b9 clang::ast_matchers::internal::(anonymous namespace)::VariadicMatcher<&(clang::ast_matchers::internal::anyOfVariadicOperator(clang::DynTypedNode const&, clang::ast_matchers::internal::ASTMatchFinder*, clang::ast_matchers::internal::BoundNodesTreeBuilder*, llvm::ArrayRef<clang::ast_matchers::internal::DynTypedMatcher>))>::dynMatches(clang::DynTypedNode const&, clang::ast_matchers::internal::ASTMatchFinder*, clang::ast_matchers::internal::BoundNodesTreeBuilder*) const ASTMatchersInternal.cpp:0:0
#13 0x000055a016d43d02 clang::ast_matchers::internal::DynTypedMatcher::matches(clang::DynTypedNode const&, clang::ast_matchers::internal::ASTMatchFinder*, clang::ast_matchers::internal::BoundNodesTreeBuilder*) const (/home/david/llvm/build/bin/clang-tidy+0x211bd02)
#14 0x000055a016db3355 clang::ast_matchers::internal::matcher_ignoringParenImpCasts0Matcher::matches(clang::Expr const&, clang::ast_matchers::internal::ASTMatchFinder*, clang::ast_matchers::internal::BoundNodesTreeBuilder*) const DurationAdditionCheck.cpp:0:0
#15 0x000055a016dace70 clang::ast_matchers::internal::MatcherInterface<clang::Expr>::dynMatches(clang::DynTypedNode const&, clang::ast_matchers::internal::ASTMatchFinder*, clang::ast_matchers::internal::BoundNodesTreeBuilder*) const ComparisonInTempFailureRetryCheck.cpp:0:0
#16 0x000055a016d43d02 clang::ast_matchers::internal::DynTypedMatcher::matches(clang::DynTypedNode const&, clang::ast_matchers::internal::ASTMatchFinder*, clang::ast_matchers::internal::BoundNodesTreeBuilder*) const (/home/david/llvm/build/bin/clang-tidy+0x211bd02)
#17 0x000055a016db59cb clang::ast_matchers::internal::matcher_hasLHS0Matcher<clang::BinaryOperator, clang::ast_matchers::internal::Matcher<clang::Expr> >::matches(clang::BinaryOperator const&, clang::ast_matchers::internal::ASTMatchFinder*, clang::ast_matchers::internal::BoundNodesTreeBuilder*) const (/home/david/llvm/build/bin/clang-tidy+0x218d9cb)
#18 0x000055a016dad070 clang::ast_matchers::internal::MatcherInterface<clang::BinaryOperator>::dynMatches(clang::DynTypedNode const&, clang::ast_matchers::internal::ASTMatchFinder*, clang::ast_matchers::internal::BoundNodesTreeBuilder*) const ComparisonInTempFailureRetryCheck.cpp:0:0
#19 0x000055a016d43e85 clang::ast_matchers::internal::DynTypedMatcher::matchesNoKindCheck(clang::DynTypedNode const&, clang::ast_matchers::internal::ASTMatchFinder*, clang::ast_matchers::internal::BoundNodesTreeBuilder*) const (/home/david/llvm/build/bin/clang-tidy+0x211be85)
#20 0x000055a016d48426 clang::ast_matchers::internal::(anonymous namespace)::VariadicMatcher<&(clang::ast_matchers::internal::allOfVariadicOperator(clang::DynTypedNode const&, clang::ast_matchers::internal::ASTMatchFinder*, clang::ast_matchers::internal::BoundNodesTreeBuilder*, llvm::ArrayRef<clang::ast_matchers::internal::DynTypedMatcher>))>::dynMatches(clang::DynTypedNode const&, clang::ast_matchers::internal::ASTMatchFinder*, clang::ast_matchers::internal::BoundNodesTreeBuilder*) const ASTMatchersInternal.cpp:0:0
#21 0x000055a016d43d02 clang::ast_matchers::internal::DynTypedMatcher::matches(clang::DynTypedNode const&, clang::ast_matchers::internal::ASTMatchFinder*, clang::ast_matchers::internal::BoundNodesTreeBuilder*) const (/home/david/llvm/build/bin/clang-tidy+0x211bd02)
#22 0x000055a016d486b9 clang::ast_matchers::internal::(anonymous namespace)::VariadicMatcher<&(clang::ast_matchers::internal::anyOfVariadicOperator(clang::DynTypedNode const&, clang::ast_matchers::internal::ASTMatchFinder*, clang::ast_matchers::internal::BoundNodesTreeBuilder*, llvm::ArrayRef<clang::ast_matchers::internal::DynTypedMatcher>))>::dynMatches(clang::DynTypedNode const&, clang::ast_matchers::internal::ASTMatchFinder*, clang::ast_matchers::internal::BoundNodesTreeBuilder*) const ASTMatchersInternal.cpp:0:0
#23 0x000055a016d43d02 clang::ast_matchers::internal::DynTypedMatcher::matches(clang::DynTypedNode const&, clang::ast_matchers::internal::ASTMatchFinder*, clang::ast_matchers::internal::BoundNodesTreeBuilder*) const (/home/david/llvm/build/bin/clang-tidy+0x211bd02)
#24 0x000055a016de40b7 clang::ast_matchers::internal::matcher_hasOperands0Matcher<clang::BinaryOperator, clang::ast_matchers::internal::Matcher<clang::Expr>, clang::ast_matchers::internal::Matcher<clang::Expr> >::matches(clang::BinaryOperator const&, clang::ast_matchers::internal::ASTMatchFinder*, clang::ast_matchers::internal::BoundNodesTreeBuilder*) const (/home/david/llvm/build/bin/clang-tidy+0x21bc0b7)
#25 0x000055a016dad070 clang::ast_matchers::internal::MatcherInterface<clang::BinaryOperator>::dynMatches(clang::DynTypedNode const&, clang::ast_matchers::internal::ASTMatchFinder*, clang::ast_matchers::internal::BoundNodesTreeBuilder*) const ComparisonInTempFailureRetryCheck.cpp:0:0
#26 0x000055a016d43e85 clang::ast_matchers::internal::DynTypedMatcher::matchesNoKindCheck(clang::DynTypedNode const&, clang::ast_matchers::internal::ASTMatchFinder*, clang::ast_matchers::internal::BoundNodesTreeBuilder*) const (/home/david/llvm/build/bin/clang-tidy+0x211be85)
#27 0x000055a016d4844c clang::ast_matchers::internal::(anonymous namespace)::VariadicMatcher<&(clang::ast_matchers::internal::allOfVariadicOperator(clang::DynTypedNode const&, clang::ast_matchers::internal::ASTMatchFinder*, clang::ast_matchers::internal::BoundNodesTreeBuilder*, llvm::ArrayRef<clang::ast_matchers::internal::DynTypedMatcher>))>::dynMatches(clang::DynTypedNode const&, clang::ast_matchers::internal::ASTMatchFinder*, clang::ast_matchers::internal::BoundNodesTreeBuilder*) const ASTMatchersInternal.cpp:0:0
#28 0x000055a016d46d6f clang::ast_matchers::internal::(anonymous namespace)::IdDynMatcher::dynMatches(clang::DynTypedNode const&, clang::ast_matchers::internal::ASTMatchFinder*, clang::ast_matchers::internal::BoundNodesTreeBuilder*) const ASTMatchersInternal.cpp:0:0
#29 0x000055a016d43d02 clang::ast_matchers::internal::DynTypedMatcher::matches(clang::DynTypedNode const&, clang::ast_matchers::internal::ASTMatchFinder*, clang::ast_matchers::internal::BoundNodesTreeBuilder*) const (/home/david/llvm/build/bin/clang-tidy+0x211bd02)
#30 0x000055a016d0a096 clang::ast_matchers::internal::(anonymous namespace)::MatchASTVisitor::matchWithFilter(clang::DynTypedNode const&) ASTMatchFinder.cpp:0:0
#31 0x000055a016d19b85 clang::RecursiveASTVisitor<clang::ast_matchers::internal::(anonymous namespace)::MatchASTVisitor>::TraverseCompoundStmt(clang::CompoundStmt*, llvm::SmallVectorImpl<llvm::PointerIntPair<clang::Stmt*, 1u, bool, llvm::PointerLikeTypeTraits<clang::Stmt*>, llvm::PointerIntPairInfo<clang::Stmt*, 1u, llvm::PointerLikeTypeTraits<clang::Stmt*> > > >*) ASTMatchFinder.cpp:0:0
#32 0x000055a016d18a00 clang::RecursiveASTVisitor<clang::ast_matchers::internal::(anonymous namespace)::MatchASTVisitor>::TraverseStmt(clang::Stmt*, llvm::SmallVectorImpl<llvm::PointerIntPair<clang::Stmt*, 1u, bool, llvm::PointerLikeTypeTraits<clang::Stmt*>, llvm::PointerIntPairInfo<clang::Stmt*, 1u, llvm::PointerLikeTypeTraits<clang::Stmt*> > > >*) ASTMatchFinder.cpp:0:0
#33 0x000055a016d42e7f clang::RecursiveASTVisitor<clang::ast_matchers::internal::(anonymous namespace)::MatchASTVisitor>::TraverseFunctionHelper(clang::FunctionDecl*) ASTMatchFinder.cpp:0:0
#34 0x000055a016d13902 clang::RecursiveASTVisitor<clang::ast_matchers::internal::(anonymous namespace)::MatchASTVisitor>::TraverseFunctionDecl(clang::FunctionDecl*) ASTMatchFinder.cpp:0:0
#35 0x000055a016d0d164 clang::ast_matchers::internal::(anonymous namespace)::MatchASTVisitor::TraverseDecl(clang::Decl*) ASTMatchFinder.cpp:0:0
#36 0x000055a016d1085b clang::RecursiveASTVisitor<clang::ast_matchers::internal::(anonymous namespace)::MatchASTVisitor>::TraverseFunctionTemplateDecl(clang::FunctionTemplateDecl*) ASTMatchFinder.cpp:0:0
#37 0x000055a016d0cf84 clang::ast_matchers::internal::(anonymous namespace)::MatchASTVisitor::TraverseDecl(clang::Decl*) ASTMatchFinder.cpp:0:0
#38 0x000055a016d16a7b clang::RecursiveASTVisitor<clang::ast_matchers::internal::(anonymous namespace)::MatchASTVisitor>::TraverseTranslationUnitDecl(clang::TranslationUnitDecl*) ASTMatchFinder.cpp:0:0
#39 0x000055a016d0cd8f clang::ast_matchers::internal::(anonymous namespace)::MatchASTVisitor::TraverseDecl(clang::Decl*) ASTMatchFinder.cpp:0:0
#40 0x000055a016cd5911 clang::ast_matchers::MatchFinder::matchAST(clang::ASTContext&) (/home/david/llvm/build/bin/clang-tidy+0x20ad911)
#41 0x000055a017b0ba4c clang::MultiplexConsumer::HandleTranslationUnit(clang::ASTContext&) (/home/david/llvm/build/bin/clang-tidy+0x2ee3a4c)
#42 0x000055a017d00744 clang::ParseAST(clang::Sema&, bool, bool) (/home/david/llvm/build/bin/clang-tidy+0x30d8744)
#43 0x000055a017a878de clang::FrontendAction::Execute() (/home/david/llvm/build/bin/clang-tidy+0x2e5f8de)
#44 0x000055a0179edeaf clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/home/david/llvm/build/bin/clang-tidy+0x2dc5eaf)
#45 0x000055a0167595f3 clang::tooling::FrontendActionFactory::runInvocation(std::shared_ptr<clang::CompilerInvocation>, clang::FileManager*, std::shared_ptr<clang::PCHContainerOperations>, clang::DiagnosticConsumer*) (/home/david/llvm/build/bin/clang-tidy+0x1b315f3)
#46 0x000055a01679cc5a clang::tidy::runClangTidy(clang::tidy::ClangTidyContext&, clang::tooling::CompilationDatabase const&, llvm::ArrayRef<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, llvm::IntrusiveRefCntPtr<llvm::vfs::OverlayFileSystem>, bool, bool, llvm::StringRef)::ActionFactory::runInvocation(std::shared_ptr<clang::CompilerInvocation>, clang::FileManager*, std::shared_ptr<clang::PCHContainerOperations>, clang::DiagnosticConsumer*) ClangTidy.cpp:0:0
#47 0x000055a016759345 clang::tooling::ToolInvocation::runInvocation(char const*, clang::driver::Compilation*, std::shared_ptr<clang::CompilerInvocation>, std::shared_ptr<clang::PCHContainerOperations>) (/home/david/llvm/build/bin/clang-tidy+0x1b31345)
#48 0x000055a016758020 clang::tooling::ToolInvocation::run() (/home/david/llvm/build/bin/clang-tidy+0x1b30020)
#49 0x000055a01675af96 clang::tooling::ClangTool::run(clang::tooling::ToolAction*) (/home/david/llvm/build/bin/clang-tidy+0x1b32f96)
#50 0x000055a0167978b0 clang::tidy::runClangTidy(clang::tidy::ClangTidyContext&, clang::tooling::CompilationDatabase const&, llvm::ArrayRef<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, llvm::IntrusiveRefCntPtr<llvm::vfs::OverlayFileSystem>, bool, bool, llvm::StringRef) (/home/david/llvm/build/bin/clang-tidy+0x1b6f8b0)
#51 0x000055a01669418a clang::tidy::clangTidyMain(int, char const**) (/home/david/llvm/build/bin/clang-tidy+0x1a6c18a)
#52 0x00007f6dd7500310 __libc_start_call_main libc-start.c:0:0
#53 0x00007f6dd75003c1 __libc_start_main@GLIBC_2.2.5 (/usr/lib/libc.so.6+0x2d3c1)
#54 0x000055a016691355 _start (/home/david/llvm/build/bin/clang-tidy+0x1a69355)
```

**Comment by njames93** [comment]
Ahh the issue here is that the getZExtValue() asserts when the type is larger than 64 bits, should be a relatively simple fix.

**Comment by SimplyDanny** [comment]
I propose [a fix](https://reviews.llvm.org/D122544) for this issue.

**Comment by SimplyDanny** [comment]
Hey @junaire, I noticed you just closed the issue. Since I almost wanted to hit the close button before, but didn't dare, I'm interested in the workflow:
* Is it okay to close issues if a fix is merged?
* Does it require a further manual review?
* Is there no need to wait for a released version which contains the fix?

**Comment by AaronBallman** [comment]
It's great to close the issue once the fix has been merged (we encourage it), but please close the issue with a link to the commit hash for the fix (or whatever resolution occurred) so people can connect the issue to the correction. In this case, the fix was done in ff60af91ac0bbab12dd5ff5dc9b78bc1636f2d86.

It doesn't require further manual review to close the issue and there's no need to wait for the release before closing the issue. If the stated fix works for the original reporter (and comments within the report), the report's ready to be closed. If there's more work left to be done, you can either leave the issue open, or close it and open a new issue for what remains (and mention the new issue in the old issue so there's a paper trail).

**Comment by junaire** [comment]
> Hey @junaire, I noticed you just closed the issue. Since I almost wanted to hit the close button before, but didn't dare, I'm interested in the workflow:
> 
> * Is it okay to close issues if a fix is merged?
> * Does it require a further manual review?
> * Is there no need to wait for a released version which contains the fix?

Hi, for me I usually don't close the issue manually but left something in the commit message like:
```
Fixes https://github.com/llvm/llvm-project/issues/NUMBER
``` 
So when you commit it, the Github will automatically close it.

**Comment by junaire** [comment]
> It's great to close the issue once the fix has been merged (we encourage it), but please close the issue with a link to the commit hash for the fix (or whatever resolution occurred) so people can connect the issue to the correction. In this case, the fix was done in [ff60af9](https://github.com/llvm/llvm-project/commit/ff60af91ac0bbab12dd5ff5dc9b78bc1636f2d86).

Hi Aaron, thanks for the clarification, but I noticed that GitHub shows a message like Somebody adds a commit that references the issue, so I haven't provided repeated information. Hope it won't cause trouble to you!
> 
> It doesn't require further manual review to close the issue and there's no need to wait for the release before closing the issue. If the stated fix works for the original reporter (and comments within the report), the report's ready to be closed. If there's more work left to be done, you can either leave the issue open, or close it and open a new issue for what remains (and mention the new issue in the old issue so there's a paper trail).

**Comment by AaronBallman** [comment]
> Hi Aaron, thanks for the clarification, but I noticed that GitHub shows a message like Somebody adds a commit that references the issue, so I haven't provided repeated information. Hope it won't cause trouble to you!

No worries, we're all still figuring out what works best for us with the new issue system. :-) Personally, I don't like relying on `added a commit that referenced this issue` because the issue can be mentioned in multiple commits unrelated to the one solving the issue (e.g., "This commit still doesn't fix issue 123 because <reasons>."). That said, I like the fact that the information is tracked along with the issue because sometimes the commits *are* related to solving the issue. Ultimately, I think either approach is fine though -- there should be *some* mention somewhere that lets us get from the issue back to the commit which fixed it.
