### ISSUE TITLE
AMDGPU/TeraScale: `Cannot select: t3: i32 = addrspacecast[0 -> 5] Constant:i32<0>` (crash, regression)

### ISSUE THREAD

**Issue by illwieckz** [llvm/llvm-project#55679]
I'm running Mesa Clover 22 against LLVM 15 (built from repositories)

When running [Luxmark 3.1](http://wiki.luxcorerender.org/LuxMark_v3#Binaries) OpenCL benchmark, I got this crash:

 ```
LLVM ERROR: Cannot select: t3: i32 = addrspacecast[0 -> 5] Constant:i32<0>
   t2: i32 = Constant<0>
In function: AdvancePaths_MK_DL_SAMPLE_BSDF
```

I reproduced the issue with this TeraScale 2 GPU:

- AMD Radeon HD 5870 RV870 Cypress XT.

I assume `AdvancePaths_MK_DL_SAMPLE_BSDF` is a LuxMark OpenCL function.

This is a regression as it works with older LLVM 20.0.4 and Mesa 9.0.1: http://luxmark.info/node/9192 (completed benchmark run on the exact same computer and installation, but running old builds of Mesa and LLVM instead).

_Note:_ This crash is specific to TeraScale2, see #54942 for another crash affecting TeraScale3 and #54947 for a bug (not a crash) affecting GCN1, 2, 3.

**Comment by illwieckz** [comment]
As a side note, GCN architecture suffered from a similar bug in LLVM 11 (introduced between LLVM 9 and LLVM 11 and fixed between LLVM 11 et LLVM 13):

```
LLVM ERROR: Cannot select: 0x7f74c1f54fa0: i32 = addrspacecast[0 -> 5] Constant:i64<0>
  0x7f74b2d05050: i64 = Constant<0>
In function: AdvancePaths_MK_DL_ILLUMINATE
```

cf. https://github.com/llvm/llvm-project/issues/54947#issuecomment-1103529078 (the test on Ubuntu 20.10).

So maybe looking what fixed GCN may be useful to know what is the issue in TeraScale 2 side.

**Comment by arsenm** [comment]
Cypress long predates flat address spaces so it's not expected for this to work. Not even the original GCN/tahiti supported flat addressing. Somebody would have to implement software flat pointers in order for this to work. Presumably this is coming from OpenCL 2.0, which should have errored when targeting such an old device

**Comment by illwieckz** [comment]
Interestingly it worked with LLVM 20.0.4 and Mesa 9.0.1, so maybe the alternate code already exists and isn't used, or maybe something in the compiling task is now using features that are not available on this hardware instead of features that are available.

The OpenCL code didn't changed from a single byte (neither the binary running said OpenCL code) between the time it worked and the time it stopped to work, so there is a regression for sure, either in Mesa, either in LLVM.

**Comment by arsenm** [comment]
I see now that this is a cast from constant. We started representing NULL as an addrspacecast from a generic null pointer to get the proper treatment as a -1 value for private pointers. The lowering of addrspacecast could special case this

**Comment by illwieckz** [comment]
When building recent LLVM 16 commit (d7d586e5a7d71082200231a7cd407cae50924f9c), this is fixed.

Note that I have tried old LLVM 11 (even before rc1, commit 29a2b20ab363bcc0b9573e358a5ad12c0eddca86) and the bug was not there.

I tried the stock LLVM 13 build from Ubuntu 22.04.1 and it reproduces the issue on both TeraScale 2 and TeraScale 3. I assume I was not able to reproduce on TeraScale 3 before because of this issue being caught first:

- https://github.com/llvm/llvm-project/issues/54942

For reference, here is the reproduction on LLVM 13:

- Cypress

```
[LuxCore] [15.161] [PathOCLBaseRenderThread::0] Compiling kernels 
LLVM ERROR: Cannot select: 0x7f41f7fa07f0: i32 = addrspacecast[0 -> 5] Constant:i32<0>
  0x7f41e031de60: i32 = Constant<0>
In function: AdvancePaths_MK_DL_SAMPLE_BSDF
```

- Cayman

```
[LuxCore] [10.137] [PathOCLBaseRenderThread::0] Compiling kernels 
LLVM ERROR: Cannot select: 0x7f10454d3aa0: i32 = addrspacecast[0 -> 5] Constant:i32<0>
  0x7f1045204c08: i32 = Constant<0>
In function: AdvancePaths_MK_DL_SAMPLE_BSDF
```

So this is known the issue was introduced between LLVM 11 and LLVM 13 and was fixed either in LLVM 15, either in LLVM 16. Early LLVM 15 (in May 2022) still had the bug.

**Comment by lorn10** [comment]
Sorry for jumping-in but it would be really helpful to know if that TeraScale2 related bug was resolved in LLVM 15 or 16?

I am now on Mesa 23.0.0-devel (git-09d5c55 2022-12-16 jammy-oibaf-ppa) which includes LLVM 15.0.5 and something is telling me that this bug is still present. So in the end this would mean that the issue here was effectively resolved in LLVM 16 and not 15. :wink:

**Comment by illwieckz** [comment]
Unfortunately I don't know which commit introduced the fix. 😟️

**Comment by arsenm** [comment]
I don't know if this was really fixed. We would probably need to special case this cast for r600

**Comment by lorn10** [comment]
Okay, let's see what the new year will bring in regard to the final LLVM 16. 

If the bug is no longer reproducible then it was resolved unnoticed and "incidentally" by another fix. :+1:

**Comment by arsenm** [comment]
17069608940d22cd6266afb948443b11793f0a57 attempts to directly address this case

**Comment by lorn10** [comment]
Hi again. Just for the record, - I have looked somewhat deeper into this topic and unfortunately I am not fit enough in building Mesa + LLVM at my own. So I cannot provide here any testing results about the aforementioned https://github.com/llvm/llvm-project/commit/17069608940d22cd6266afb948443b11793f0a57 fix.

But I'm confident that @illwieckz will find some time to verify in conjunction with LLVM 15 if that fix is really the ultimate solution in this topic here. :wink:  :+1: PS With a lot of delay, - a happy new year to all!

**Comment by lorn10** [comment]
A new addition. https://github.com/llvm/llvm-project/commit/17069608940d22cd6266afb948443b11793f0a57 was tested recently with something which looks like a new TeraScale 3 LLVM bug but it didn't resolve the underlying issue there. See #62832 for more information.

**Comment by lorn10** [comment]
And by the way the "AMDGPU/R600: Special case addrspacecast lowering for null" tweak https://github.com/llvm/llvm-project/commit/17069608940d22cd6266afb948443b11793f0a57 could be of some relevance also for the **[Terakan](https://www.phoronix.com/news/Mesa-Terakan-R600-Vulkan-Driver)** project. :thinking: 

I mean just for the case that also Terakan will allow at some point the switching between **NIR** and **LLVM**. RADV offers this option for ACO and LLVM. And this was regarding NIR/TGSI and LLVM (at some point in the past) even possible for radeonsi and r600 but it looks that the LLVM envvar option is for the later two [no longer available](https://docs.mesa3d.org/envvars.html). 

Whatever, pinging @Triang3l about that R600 "AMDGPU/R600: Special case addrspacecast lowering for null" matter. :wink:

**Comment by Triang3l** [comment]
> And by the way the "AMDGPU/R600: Special case addrspacecast lowering for null" tweak https://github.com/llvm/llvm-project/commit/17069608940d22cd6266afb948443b11793f0a57 could be of some relevance also for the **[Terakan](https://www.phoronix.com/news/Mesa-Terakan-R600-Vulkan-Driver)** project. :thinking: 

It looks like this is mostly applicable to OpenCL, not to Vulkan. If I understand correctly what flat and global addressing means (are those unified global+GDS+LDS (?) pointers for the former and just absolute global memory pointers for the latter?), neither truly exists in shaders on both Evergreen and Cayman — everything needs to be accesses through some kind of a binding. But as far as I know, Vulkan doesn't have the former too, and the closest to the latter is only available in the form of buffer device address.

Gallium, I think (but I may be wrong — that's how I understand what `r600/compute_memory_pool` does in it), implements OpenCL global memory by suballocating needed buffers from one large buffer (actually backed by one big physical allocation), and manually managing residency of buffers within it and defragmenting it, involving implicit copying of memory. For Vulkan, that has explicit memory management among its core design principles, this is likely not a viable approach.

Buffer device address is only mandatory in Vulkan 1.3, and for it my implementation (only for Cayman due to the lack of virtual memory on Evergreen) will likely be lowering it on the NIR level to a storage buffer that the CPU will bind a 4 GB virtual memory range to (the kernel thankfully intentionally doesn't perform bounds checking of bindings when using virtual memory), and virtual addresses of buffers that support buffer device address will be within that range.

Though that will possibly be compatible with LLVM's global addressing too given that the latter also likely uses vfetch+RAT behind the scenes (the hardware simply doesn't have arbitrary pointer access in shaders, and it's the only way to bind memory to a shader so that all buffer functionality like atomics works), but I don't think even if Terakan starts using LLVM, it will actually be using LLVM global memory addressing rather than the usual storage buffer logic for buffer device address.

Anyway, it's won't be a NIR vs. LLVM choice either — it's NIR>SFN or NIR>LLVM, because NIR is what Mesa converts SPIR-V and GLSL shaders to first. We'll still be able to do all the lowerings, needed for SFN, for LLVM, or for both, on the NIR side — including to avoid problematic cases in LLVM.

But I'm not sure if Terakan will be using LLVM, as having a custom compiler directly in the driver simplifies adding new functionality, such as maybe using the clause global register on Cayman and the active wave mask ALU operand for basic communication between lanes in a wave (although I haven't researched that deeply yet), or maybe the LDS for full-blown subgroup operations (complicated if the compute shader already uses all 32 KB of it for its group-shared memory, however).

**Comment by lorn10** [comment]
Many thanks for this super detailed answer! :+1:   

Okay, I understand this in the way that Terakan doesn't work in the way like RADV so there will be no option between NIR and LLVM. Yeah this seems to make sense because LLVM on R600 (and clover) is unfortunately somehow flawed as we can see in clpeak and several other OpenCL applications.

**Comment by Triang3l** [comment]
> work in the way like RADV so there will be no option between NIR and LLVM

Small off-topic correction: RADV doesn't let you choose between NIR and LLVM, it has NIR>ACO and NIR>LLVM paths. NIR is the intermediate representation used in all modern Mesa drivers, and GLSL and SPIR-V shaders are first translated into architecture-agnostic NIR, and only then they go through architecture-specific lowering passes that can decompose abstract concepts into simpler driver-specific intrinsics while still using the SSA, control flow and optimization infrastructure that NIR provides (that is specifically designed for easy code modification and traversal) to simplify the job for the driver's shader compiling backend and to reduce code duplication between drivers and between the driver and the common logic. But in the GCN/RDNA case in Mesa, a lot of lowering passes are still shared between the ACO and LLVM backends. A very basic example is anything that involves interacting with RADV's internal concepts — like the GPU-agnostic "load MSAA sample location" functionality being transformed (as the hardware doesn't have such an instruction, it's done in software shader logic instead) into some NIR arithmetic instructions for computing the address where RADV specifically puts the location of the needed sample, and NIR buffer load instructions, that both the ACO and LLVM backends implement. The same applies to NIR>SFN and a potential NIR>LLVM path for TeraScale.

**Comment by lorn10** [comment]
Again thanks for the clarification. Yes, this NIR>LLVM, NIR>SFN and NIR>ACO stuff seems to be (again) more complex then expected. It looks that I am still at a somewhat outdated level from around 10 years ago, [R600 Gallium3D LLVM & SB Shader Back-End Tests](https://www.phoronix.com/news/MTQzODc). At that time there was only TGSI, NIR was just in its earliest stage. :wink:

**Comment by lorn10** [comment]
A final comment to this topic. As of May 2024 [Luxmark 3.1](http://wiki.luxcorerender.org/LuxMark_v3#Binaries) seems to work (mostly) also with LLVM 15 without any crash. I can confirm this for Mesa 24.2-git2405210600.e1b4b3-oibaf-j (git-e1b4b39 2024-05-21 jammy-oibaf-ppa).

So it looks that a change in newer Mesa builds, like the switch to the new "[LLVM pass manager](https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/24879)", has improved the situation. However, the reported Luxmark 3.1 result with LLVM 15.0.7 is not fully correct. It is confirmed that this works properly with LLVM 16.0.6 and LLVM 18.1.5 while LLVM 17.0.6 is also broken but on a different way. More information can be found in [Mesa bug report 24879](https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/24879).

And when I am here, sorry to bother again @arsenm, but I still think that https://github.com/llvm/llvm-project/commit/17069608940d22cd6266afb948443b11793f0a57 would be a nice win for older Radeon hardware. This is even more true now because clover might stay somewhat longer, - rusticl is simply far away to be operational also on TeraScale hardware. :wink:

**Comment by arsenm** [comment]
> And when I am here, sorry to bother again @arsenm, but I still think that [1706960](https://github.com/llvm/llvm-project/commit/17069608940d22cd6266afb948443b11793f0a57) would be a nice win for older Radeon hardware. This is even more true now because clover might stay somewhat longer, - rusticl is simply far away to be operational also on TeraScale hardware. 😉

I'm not sure what the request is, this was committed long ago?

**Comment by lorn10** [comment]
Yeah & sorry I am not really GitHub aware but I think that commit didn't land? :thinking:  

At least I didn't see a corresponding merge or pull request.

**Comment by arsenm** [comment]
> Yeah & sorry I am not really GitHub aware but I think that commit didn't land? 🤔
> 
> At least I didn't see a corresponding merge or pull request.

That was long before the switch to GitHub. git branch --contains 17069608940d22cd6266afb948443b11793f0a57  |  grep main shows it
