### ISSUE TITLE
LLVM 15.0.0-rc2: compiler_rt does not build out of the box on older macOS: Failed to determine SDK version for "iphonesimulator" SDK

### ISSUE THREAD

**Issue by debohman** [llvm/llvm-project#57037]
```console
CMake Error at /tera/tera/debo/Projects/llvm/llvmorg-15.0.0-rc2/compiler-rt/cmake/Modules/CompilerRTDarwinUtils.cmake:73 (message):
  Failed to determine SDK version for "iphonesimulator" SDK
Call Stack (most recent call first):
  /tera/tera/debo/Projects/llvm/llvmorg-15.0.0-rc2/compiler-rt/cmake/builtin-config-ix.cmake:120 (find_darwin_sdk_version)
  CMakeLists.txt:51 (include)


-- Configuring incomplete, errors occurred!
See also "/tera/tera/debo/Projects/llvm/llvmorg-15.0.0-rc2-build/runtimes/builtins-bins/CMakeFiles/CMakeOutput.log".
See also "/tera/tera/debo/Projects/llvm/llvmorg-15.0.0-rc2-build/runtimes/builtins-bins/CMakeFiles/CMakeError.log".
FAILED: runtimes/builtins-stamps/builtins-configure /tera/tera/debo/Projects/llvm/llvmorg-15.0.0-rc2-build/runtimes/builtins-stamps/builtins-configure
```
Configuration:
```shell
cmake -G Ninja -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_EXE_LINKER_FLAGS=-L/usr/local/lib -DCMAKE_BUILD_TYPE=Release -DLLVM_TARGETS_TO_BUILD=X86 -DLLVM_ENABLE_PROJECTS="clang" -DLLVM_ENABLE_RUNTIMES="libcxx;libcxxabi;libunwind;compiler-rt" ../llvmorg-15.0.0-rc2/llvm
```
I was able to build it by changing the configuration in `build/runtimes/builtins-bins/CMakeCache.txt`:
```cmake
COMPILER_RT_ENABLE_IOS:BOOL=OFF
```
macOS 10.12.6
cmake version 3.24.0

**Comment by carlocab** [comment]
You can pass
```
-DBUILTINS_CMAKE_ARGS=-DCOMPILER_RT_ENABLE_IOS=OFF
```
to your `cmake` invocation to avoid having to edit a `CMakeCache.txt`.

**Comment by carlocab** [comment]
Since #57362 is now closed, I'll copy my comment from there in case it might be useful:

> You need an Xcode installation to build 15.0.0-rc2. The CLT alone does not suffice, at least not without an extra CMake flag. I've been meaning to file an issue about this for a few days now, but I haven't gotten around to it. But this is a regression against 14.0.6.
> 
> The errant commit seems to be [a680c21](https://github.com/llvm/llvm-project/commit/a680c212cb213bf73be7d3e2ee919fdc743cef0c).
> 
> A workaround is to pass
> 
> ```
> -DBUILTINS_CMAKE_ARGS=-DCOMPILER_RT_ENABLE_IOS=OFF
> ```
> 
> to your `cmake` invocation, if you don't want to use a full Xcode installation. It would be nice for a CLT-only build to just work without needing the flag above, since it's rather arcane.
> 
> Related discussion at [Homebrew/homebrew-core#106925](https://github.com/Homebrew/homebrew-core/pull/106925).

**Comment by balay** [comment]
Hm `-DBUILTINS_CMAKE_ARGS=-DCOMPILER_RT_ENABLE_IOS=OFF` does not work for me. Attaching the log

[spack-build-out.txt](https://github.com/llvm/llvm-project/files/9428580/spack-build-out.txt)

**Comment by debohman** [comment]
The workaround was successful for me. This is bootstrapping using llvm-14.0.6 and cmake-3.24.1.

**Comment by balay** [comment]
I tried the alternate fix  - and could make progress
```diff
--- a/compiler-rt/cmake/base-config-ix.cmake    2022-08-25 17:44:01.000000000 -0500
+++ b/compiler-rt/cmake/base-config-ix.cmake    2022-08-25 17:42:05.000000000 -0500
@@ -145,7 +145,7 @@
                    "-darwin-target-variant" "x86_64-apple-ios13.1-macabi"
                    "-Werror")
   option(COMPILER_RT_ENABLE_MACCATALYST "Enable building for Mac Catalyst" ${COMPILER_RT_HAS_DARWIN_TARGET_VARIANT_FLAG})
-  option(COMPILER_RT_ENABLE_IOS "Enable building for iOS" On)
+  option(COMPILER_RT_ENABLE_IOS "Enable building for iOS" Off)
   option(COMPILER_RT_ENABLE_WATCHOS "Enable building for watchOS - Experimental" Off)
   option(COMPILER_RT_ENABLE_TVOS "Enable building for tvOS - Experimental" Off)
 
```
However got build errors (with native compilers)
[clt-spack-build-out.txt](https://github.com/llvm/llvm-project/files/9429055/clt-spack-build-out.txt)
Then I tried gcc from brew - and got similar errors.

> This is bootstrapping using llvm-14.0.6

Ah so - I tried using (previously installed) llvm-14.0.6  - and that worked!
```
balay@ypro spack % /Users/balay/spack/opt/spack/darwin-catalina-skylake/clang-14.0.6/llvm-15.0.0-rc2-5lploygnzkvgilunkqbdffoecobed6vu/bin/clang-format --version
clang-format version 15.0.0
```

**Comment by carlocab** [comment]
> Hm `-DBUILTINS_CMAKE_ARGS=-DCOMPILER_RT_ENABLE_IOS=OFF` does not work for me. Attaching the log
> 
> [spack-build-out.txt](https://github.com/llvm/llvm-project/files/9428580/spack-build-out.txt)

This is because you pass `compiler-rt` to `LLVM_ENABLE_PROJECTS`. Pass it to `LLVM_ENABLE_RUNTIMES` instead. You don't need to adjust your compiler to a recent-ish LLVM if you do this (since `LLVM_ENABLE_RUNTIMES` will use the just-built `clang` compiler to build `compiler-rt`).

**Comment by balay** [comment]
Ah - ok. That's whats currently in spack recipe for llvm. [hence in the current build]

setting `compiler-rt` via `LLVM_ENABLE_RUNTIMES` gets `DBUILTINS_CMAKE_ARGS=-DCOMPILER_RT_ENABLE_IOS=OFF` working

>  '-DLLVM_ENABLE_PROJECTS:STRING=lldb;clang;clang-tools-extra;lld;compiler-rt;libcxx;libcxxabi;libunwind;polly'

the build failure was in libcxxabi  - so I guess that should also be switched? Ok - switched libcxx ,libcxxabi and  the build now goes through with apple compilers.

**Comment by carlocab** [comment]
Generally I'd recommend passing arguments to `LLVM_ENABLE_RUNTIMES` whenever possible.

This works for `libcxx`, `libcxxabi`, `compiler-rt`, `libunwind`, and `openmp`.

**Comment by balay** [comment]
Since what version of llvm is it recommended to use LLVM_ENABLE_RUNTIMES [instead of LLVM_ENABLE_PROJECTS] for the above?

**Comment by carlocab** [comment]
> Since what version of llvm is it recommended to use LLVM_ENABLE_RUNTIMES [instead of LLVM_ENABLE_PROJECTS] for the above?

It works on at least LLVM 12 and newer. That's probably a good place to start doing it.

**Comment by carlocab** [comment]
@tru, @tstellar (apologies for tagging you both; I'm not sure who the release manager for LLVM 15 is), I view this as a release-blocker. Build configurations that used to build for LLVM 14 on Darwin now no longer build unless you have a full Xcode installation. A full Xcode installation was not needed to build LLVM 14.

**Comment by tru** [comment]
@carlocab thats me. Tom is on vacation at this time.

Have you bisected the problem to see what created the problem? It's pretty late in the cycle to get a fix into 15.0.0 - but later releases will be no problem.

I will put it into the 15.0.1 milestone for now to keep an eye on it.

**Comment by carlocab** [comment]
I have not bisected it, but I'm pretty sure it's https://github.com/llvm/llvm-project/commit/a680c212cb213bf73be7d3e2ee919fdc743cef0c. That commit introduces the calls to `find_darwin_sdk_version` that results in an error.

**Comment by tru** [comment]
Can you try reverting that and see if that fixes it?

**Comment by tru** [comment]
Ping @nico that have been working on this recently

**Comment by carlocab** [comment]
> Can you try reverting that and see if that fixes it?

Yes, started on that when I posted my comment. Will update you in an hour or so.

**Comment by carlocab** [comment]
Also, while I'm waiting to see if reverting does in fact fix it (I started from a clean build directory to make sure, so it's taking a bit), an alternative would be to change this:

https://github.com/llvm/llvm-project/blob/e941b031d316f74267350fe2373d30e28b3a2c2e/compiler-rt/cmake/base-config-ix.cmake#L148

Instead of defaulting to `On`, it should either default to `OFF`. Or, perhaps better, check if the toolchain supports building for iOS and choose the appropriate setting.

**Comment by carlocab** [comment]
Reverting https://github.com/llvm/llvm-project/commit/a680c212cb213bf73be7d3e2ee919fdc743cef0c allows the build to succeed.

**Comment by tru** [comment]
This is a possible fix:

```
diff --git a/compiler-rt/cmake/Modules/CompilerRTDarwinUtils.cmake b/compiler-rt/cmake/Modules/CompilerRTDarwinUtils.cmake
index 2c9983c6a1ae..478bd163e7cf 100644
--- a/compiler-rt/cmake/Modules/CompilerRTDarwinUtils.cmake
+++ b/compiler-rt/cmake/Modules/CompilerRTDarwinUtils.cmake
@@ -70,8 +70,10 @@ function(find_darwin_sdk_version var sdk_name)
     )
   endif()
   if(NOT result_process EQUAL 0)
-    message(FATAL_ERROR
+    message(WARNING
       "Failed to determine SDK version for \"${sdk_name}\" SDK")
+    set(${var} 0 PARENT_SCOPE )
+    return
   endif()
   # Check reported version looks sane.
   if (NOT "${var_internal}" MATCHES "^[0-9]+\\.[0-9]+(\\.[0-9]+)?$")
```

but I don't have the setup to test this.

**Comment by carlocab** [comment]
I can test it later tonight when I'm back to my computer.

Though, if you have the CLT installed (`xcode-select --install`), it suffices to switch the active developer directory to the CLT -- the build will fail even if you have a full Xcode installation.

Something like
```
xcode-select -switch /Library/Developer/CommandLineTools
```
and/or
```
export DEVELOPER_DIR=/Library/Developer/CommandLineTools
```
should do the trick.

(Assuming you have a machine running macOS, anyway.)

**Comment by carlocab** [comment]
The patch doesn't work, unfortunately:
```
CMake Error at /Users/carlocab/github/llvm-project/compiler-rt/cmake/Modules/CompilerRTDarwinUtils.cmake:77:
  Parse error.  Expected "(", got newline with text "

  ".
Call Stack (most recent call first):
  CMakeLists.txt:33 (include)
```
I'll look into how to fix it tomorrow.

**Comment by tru** [comment]
I fixed it and uploaded it here: https://reviews.llvm.org/D133273

**Comment by tru** [comment]
Didn't have time to address the suggestions in the review so I'll move this to 15.0.2.

**Comment by aaron-michaux** [comment]
This is still an issue in LLVM 15.0.6

**Comment by rorth** [comment]
This is still an issue on LLLVM 16.0.0 rc1 (seen on `arm64-apple-darwin21.6` with Command Line Tools for Xcode 14.2).  I agree this is a stopper, especially on systems where you don't have admin privileges to install full Xcode yourself.  Having the build fail several hours in for this is extremely user-unfriendly.

**Comment by tru** [comment]
I submitted a updated fix: https://reviews.llvm.org/D133273

**Comment by debohman** [comment]
I have tested the patch from [D133273](https://reviews.llvm.org/D133273) against 16.0.0-rc2, and the patch seems to work. Thanks.
