### ISSUE TITLE
Type trait used in concept definition not being transiently pulled into the current module?

### ISSUE THREAD

**Issue by erichkeane** [llvm/llvm-project#60336]
See the discussion/reduction work done here: 

https://reviews.llvm.org/rG12cb1cb3720de8d164196010123ce1a8901d8122
https://godbolt.org/z/v58x71j4a

This is a regression thanks to that revert, which we unfortunately cannot un-revert.

For some reason, the `common_reference` type-trait isn't being pulled into the current context, which does `import std.functional`.  Seemingly, the `assignable_from`/`common_reference_with` from `std.concepts.assignable` is, but not the stuff from `std.type_traits`.

For some reason the sugared version of the concept DID include it somehow, but it isn't clear how.

**Comment by mordante** [comment]
I think the revert introduced the ICE, but the missing clang module seems a libc++ bug.
(As @mstorsjo mentioned it might be the ICE was there already longer, but a refactoring in libc++ uncovered it.)

https://reviews.llvm.org/D142690 fixes libc++ locally, but still needs to finish its CI run to make sure it fixes everything. (Unlike the version posted earlier today, this version should be the real fix.)

**Comment by erichkeane** [comment]
> I think the revert introduced the ICE, but the missing clang module seems a libc++ bug. (As @mstorsjo mentioned it might be the ICE was there already longer, but a refactoring in libc++ uncovered it.)
> 
> https://reviews.llvm.org/D142690 fixes libc++ locally, but still needs to finish its CI run to make sure it fixes everything. (Unlike the version posted earlier today, this version should be the real fix.)

So the revert did NOT introduce the ICE, it simply 'revealed' it if that makes sense.  The problem is it re-introduced the diagnostic we see, and the process of diagnosing introduced the ICE.  That ICE should be fixed in https://github.com/llvm/llvm-project/commit/42e371b174d4407ec5805010c2ecfef9c086b5c2

**Comment by mordante** [comment]
Yes the issue is that clang-modules (not C++20 modules) are maintained in a handcrafted module map and this is a bit fragile. I've seen several times that including a granularized headers in libc++ reveals missing exports. It seems the revert caused some missing exports. I'm still not sure why that happened, but the missing exports seemed to be real.

The thing that got me distracted that instead of issuing a diagnostic we got a diagnostic + ICE which got me distracted by focusing on the ICE.

Thanks for fixing it.

**Comment by erichkeane** [comment]
Looks like it was an  inverse-regression in that case then :)  I'll add that reproducer as a test to ensure we diagnose it (and not ICE!) then close this.  Thanks for your confirmation.

**Comment by mizvekov** [comment]
I am reopening the issue, since I have a fix for the original test case introduced here, and a further reduction of it.

See https://github.com/llvm/llvm-project/pull/101745
