### ISSUE TITLE
Remove __attribute__((target_clones)) requirement in function prototype

### ISSUE THREAD

**Issue by HFTrader** [llvm/llvm-project#61219]
Let's say I have a library that I want to share with multiple targets
```c++
#include <array>
#include <cstdio>

using Vector = std::array<float, 2>;
using Matrix = std::array<float, 4>;

__attribute__((target_clones("default","arch=core2","arch=znver2")))
Vector multiply(const Matrix& m, const Vector& v) {
    Vector r;
    r[0] = v[0] * m[0] + v[1] * m[2];
    r[1] = v[0] * m[1] + v[1] * m[3];
    return r;
}
```
and I want to use that as below
```c++
#include <array>
#include <cstdio>

using Vector = std::array<float, 2>;
using Matrix = std::array<float, 4>;

Vector multiply(const Matrix& m, const Vector& v);

int main() {
    Matrix m{1,2,3,4};
    Vector v{1,2};
    Vector r = multiply(m,v);
    printf( "%f %f\n", r[0], r[1] );
}
```
Godbolt project: https://godbolt.org/z/3hd4MrzsG

GCC will be happy to compile and link the above two files together but Clang++ will complain about undefined references. 
```console
ld: CMakeFiles/example.dir/example.cpp.o: in function `main':
example.cpp:(.text+0x2a): undefined reference to `multiply(std::array<float, 4ul> const&, std::array<float, 2ul> const&)'
```
To make this work, I have to add all the targets in the prototype as well as in 
```cpp
#include <array>
#include <cstdio>

using Vector = std::array<float, 2>;
using Matrix = std::array<float, 4>;

__attribute__((target_clones("default","arch=core2","arch=znver2")))
Vector multiply(const Matrix& m, const Vector& v);

int main() {
    Matrix m{1,2,3,4};
    Vector v{1,2};
    Vector r = multiply(m,v);
    printf( "%f %f\n", r[0], r[1] );
}
```
Looking at the object files generated, it seeems that the main difference is that GCC generates an indirect link for the naked prototype while Clang generate an indirect link to `.ifunc` and that requires knowledge of the target attributes. 
```console
$ diff nm.gcc nm.clang
3,4d2
<                 U _GLOBAL_OFFSET_TABLE_
<                 U __stack_chk_fail
6,13c4,11
< i multiply(std::array<float, 4ul> const&, std::array<float, 2ul> const&)
< t multiply(std::array<float, 4ul> const&, std::array<float, 2ul> const&) [clone .arch_cascadelake.3]
< t _Z8multiplyRKSt5arrayIfLm4EERKS_IfLm2EE.arch_core2.0
< t multiply(std::array<float, 4ul> const&, std::array<float, 2ul> const&) [clone .arch_haswell.2]
< t multiply(std::array<float, 4ul> const&, std::array<float, 2ul> const&) [clone .arch_sandybridge.1]
< t _Z8multiplyRKSt5arrayIfLm4EERKS_IfLm2EE.arch_znver1.4
< t _Z8multiplyRKSt5arrayIfLm4EERKS_IfLm2EE.arch_znver2.5
< t multiply(std::array<float, 4ul> const&, std::array<float, 2ul> const&) [clone .default.6]
---
> T multiply(std::array<float, 4ul> const&, std::array<float, 2ul> const&) [clone .arch_cascadelake.3]
> T _Z8multiplyRKSt5arrayIfLm4EERKS_IfLm2EE.arch_core2.0
> T multiply(std::array<float, 4ul> const&, std::array<float, 2ul> const&) [clone .arch_haswell.2]
> T multiply(std::array<float, 4ul> const&, std::array<float, 2ul> const&) [clone .arch_sandybridge.1]
> T _Z8multiplyRKSt5arrayIfLm4EERKS_IfLm2EE.arch_znver1.4
> T _Z8multiplyRKSt5arrayIfLm4EERKS_IfLm2EE.arch_znver2.5
> T multiply(std::array<float, 4ul> const&, std::array<float, 2ul> const&) [clone .default.6]
> i multiply(std::array<float, 4ul> const&, std::array<float, 2ul> const&) [clone .ifunc]
20d17
< r std::piecewise_construct
```
The request is that Clang emits targets in a way that the target attributes won't be necessary in the function declaration/prototype.

**Comment by MaskRay** [comment]
Clang's current behavior is a result of the symbol difference: https://maskray.me/blog/2023-02-05-function-multi-versioning

I wonder whether GCC intentionally supports the use case. My may need a clarification from them.

**Comment by HFTrader** [comment]
@MaskRay what would be the correct place to ask that question? Their bugzilla?

**Comment by HFTrader** [comment]
GCC answered 

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=109047

https://gcc.gnu.org/onlinedocs/gcc-12.2.0/gcc/Common-Function-Attributes.html#index-target_005fclones-function-attribute

> It also creates a resolver function (see the ifunc attribute above) that dynamically selects a clone suitable for current architecture. The resolver is created only if there is a usage of a function with target_clones attribute.

**Comment by lawben** [comment]
I just stumbled across this in a project that I'm working on (with Clang/LLVM 18). This is really not my area of expertise, but it feels like not exporting the "naked" symbol somewhat defeats the "I will resolve this for you" purpose of this feature. The symbol is created, but it is not exported (at least according to `nm` it is a local symbol). Currently, I can only use `target_clones` within the same compilation unit but not from a library, which I would like to do. 

Is there any technical reason to _not_ export the symbol? If GCC does this, and there is no technical reason to avoid doing it, not exporting the symbol feels more like a bug than a "missing feature/enhancement". 

As nothing has happened here for over a year: is anybody working on this or is there a decision on how to move forward? I'm happy to help, as I have a specific use-case that needs exactly this feature.

**Comment by jroelofs** [comment]
cc @labrinea: I vaguely remember we talked about the corresponding problem for `target_version`, but I don't remember the resolution.

**Comment by jroelofs** [comment]
* https://github.com/llvm/llvm-project/issues/81494
* https://github.com/llvm/llvm-project/issues/81043

**Comment by jroelofs** [comment]
I think this has been fixed. @HFTrader's original example works now: https://godbolt.org/z/3hd4MrzsG

**Comment by lawben** [comment]
@jroelofs Thanks for the update! I'm actually trying to use this on ARM, and it does not seem to work there. I've updated the [godbolt example](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMRMAPVgB3oDpkPHqSqoGBAMrIm9EAEYALKPEEAqgGdMABU4gA5AAZ9pAFYLStJg1DIApACYAQo6ekt9ZATzjKjdADCqLQAriwMCgDMpP4AMngMmAByYQBGmMQgAJykPKgahD4MQaHhUbn5heLxiSks6Zk5HpheRZIETMQEJWER8tHNreLtnQQ1yWkZ2e4dXT1l/TOj43UN2QCU7qghxMjs%2Bo6RCcihWADUdpEBncRMAJ6X2HaGAIKHx6eYF1fIGgT4qEezzerxCBRsZwAai0iMRvgARM5/dAgEA3e6XAJUWioJgEUhnBxAyIuUHg4BnACyeOIeE4CKR/1R6IeV2xuPxZ0UxNJIJe0K8JDOLBCtG8fDuEDQDD%2BVJpdMcADZhQTpbKBbClWcAG7rS684EJAjCpgJCDrC4Adl5Z1tcoItPpLDs1vkpAcpGi3Mt8P1wLtUJhQu1LqcbqJPr9rwDGqFcMuiJFYrwEogLFIuqjLwDPFpEioEAuDiJDgArFQi%2BW7KWAgxHB6zsRq05DNX4QSm6Ww22znqScCXfD9JtaAZSyYIvp5CZUBxuCw%2BJhBMJSAQDMZNhAkGgsLhCCRyJQaPRmGwQFQQgwhjLlyIxBJpLJ2EoVBJNDo9EYTOYPVYbChXFcdxME8bxfAgfx5giUtSxiBh0BWSZMnkQwKgKMDimCXoQBgtCqgYRD6imFDgNAtpZm6LCylwwYMJGLpCLWEi/lGKCcNgliGISCYiOQwxNg0bZdn2d4r0%2Bb5rmIW5WSeV5RJOEJzkxX5/h8IE5LJBIKVjeNIkRZFmSkjE2RxPECSJSInn7TSIWpB06QZAy0SM1ksVMzluUsrMBwcI4KywGhEnQCAAH0Qs4AAORUQsVRQwr1V4wrxezUhCAhMDCqBZmATACBCk5xEwDQIHrAKmFFAh61IetOmQBAEzQYhMBLD0at2eq9IALwYbUMha9YBp8yIQK0YEkoIFK0oykKss6HK8oKxJivrDReqqlbepa6rizKir6wGhK3l8/w8CoYEdOFCqU1oSU1WNOzHS1dMzjuwNBSbBxlV1K0bTtC6m2s7M7U7FsewTHVm1bUtEQAKmFSGwecCGu3kHs4edLsiWhrMAxB1HoYZEMuyh2H4ZRxGnGR7sCfR5tIjbHHgdynYGEbbzI1eYdLDHCd1xnc9L2vDRb1XPnN23DAcHwWFD2oOhGFYdgAmpABrTB4j%2BYWCE4fF7ykGQ5BfPX310PmzBAaI/1sFgmDV0iYSKPx4LYxRojibjVimS08Iwl3ojydCikYr37evejKNKCJXdDuiKODzJvc4iPsOjpP45AS0BKEvYDGQG21ZClgEjwEUWBCpqAEcQjwJrgqhbAACVJAASQAeSSM5In4BxeyGpFcsLZWXgAaWwEKAgADQnkKADFYheABxSQQob7BYmwF5JDH5ukmbgAVIsHAAWht9qE06FhtQio%2BmH2vutAIQfKRHsfJ%2BnufF%2BX1f1837fd4P%2BsJ9aodXhBfK%2BN876vFzKgUwMJCxcF4PQXurwmDoHQCFLgLQ0pMFSPQeB85FxnAQQuAQQgeDIJeKg9BtA8CpFuMQSUZwLxXgwhoM4kg94vD3s3AITDBasNvBQ7KuUQo0IYCrURtD6F4CKvgxBXxmFC17FzUc%2BhxykEnMYUgs5la23VngTW/Btb4jXF%2BcWIAHSYEwLLPOeiXjEGABoAwR94RD1HiFJwahm6xHhCFPeABNbQVl4RNXoEwLQJg0ALnlsQWI1hgAhCYDlZuKJ7DOCAsgMERAWCtzSjwNKM95annYMQxcoh5ZONgJgaWJAUkWGPJgOpboGnFLnPIkWoB9AmAMc3MSilqlmwMdSBIkhs77GnOQDQrceCMDNlbOpXTNzVP3MQOpHoGlrPKSeRWAsWFFGFmQ0gnTukaF6QpLAKIvyTOGQwUZOwc5ThOdM2ZVz5mXK5hBGpqyUTRA2T8rZCszy6LVhrAgWsdZHIMCcs5nxLlaKGaaW5YzBlTJmZokwbyoUDUmcCnQxAYEwjNuYN0iQADuhT6B1MUCOHmGizazn0HvJqXxDgTNMRuTYCBMCoKmOaUgKsFCGEMPwIVoqxVistgYRQJgWAgEUKWfgipFSRFLIYKKpZixZFLCqulVyGUmCcW6dlHyYBQFNVuFAqBon0DIBQKUVqeAxOcpfa%2BJx4nyAiiRY86ViBOIgKkM2qQEidDuAYCZQbmAMNbqkWBXgw2RKtWwCQrcGA3TNlgVKwBri0FoE4x5pAsA2xsHIK5%2BAmqtF6nmrRmDMnpXjeQCQIE5lSJDUELAZt7Kyvzb1YgqR8iYHhJgItwAxGdI3KIKwjjIQyNJc8ycEy9aPkNsoY2WhTZXOJZYeJAF0nOEsLQypfLUA8FYc41ukQzgzh7bSLAh6BIgQduBSCVEIgOGUO7WoSELAB3wmxN9Psg4ey/W6Wi5FWIvpAP%2B0Dww45Ad4hYJOf7lBpzg0xTYljnw0rUbzPVBgzhgOvkwF6Vszgev4PIEVZwIBMqsUWSI8h1gmGNdirlPLMh8oFaq7m%2BhpWkFlShVC6LtFQvcCAVCzHSBwFgBLa1GQbEOqdW6mwHqvV0B9X6gNVyI0hvrdpqNMbCX5qiUmggKa02lswJm7Nub62FviSWrRZaHaVrNjWqa9ajRNteS2hhbb9haM7fWntfatCDuHaOsWE6kkaGnZgWdaL62LoNs%2BFdqgTafi0T%2BLd/40kuD3TQ1Id7tEnv2WeyIV6Mg3qKvAe9ZEn3Owg2WOCCFUPEX9pUX2jXYI/owunRY0HbkUT/RxB9YdYOfvg/1obXWlhcQm0xSI6HmUKCw%2BooTDKziRUVEfWKxH4mkYiuRyj1HmV0YY0xsWnLuVYHY5sTjqFVG8f40K3VWj9WifE5d7jDgZU4UUPwSIkRYpZH6IoS0lpDCKCVYqV7/MumizMVh8rsPhPw%2BY5sHtBRfCKCAA%3D) to ARM and it does not generate any assembly. I'm not sure if I'm messing something up or not.

**Comment by lawben** [comment]
Sorry, guys. I accidentally hit a key combination in the wrong window that apparently closed the issue with a comment. That was not intended, please ignore 😅

**Comment by lawben** [comment]
I'm trying to run this on ARM, which _seems to work_ if I inspect the output of `nm` in [godbolt](https://godbolt.org/z/8EoYne8e1) when changing the compiler. However, on my M1 Macbook, this still does not work. I guess this is related to `.ifunc` features. If I use `target_clones` in the prototype on M1, it works. But if I only put it in the .cpp file, it does not. Should this work or does this not work in non-linux?

**Comment by tahonermann** [comment]
I think this might have been fixed in December, 2023 by [this commit](https://github.com/llvm/llvm-project/commit/cee5b8777fa98312b05bf8aa81554910a8f867c5).

**Comment by jroelofs** [comment]
> However, on my M1 Macbook, this still does not work.

What version of the toolchain? FMV and ifunc support would only be in the developer beta we shipped last week, or in an open source toolchain you've built yourself.

**Comment by jroelofs** [comment]
> I've updated the [godbolt example](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMRMAPVgB3oDpkPHqSqoGBAMrIm9EAEYALKPEEAqgGdMABU4gA5AAZ9pAFYLStJg1DIApACYAQo6ekt9ZATzjKjdADCqLQAriwMCgDMpP4AMngMmAByYQBGmMQgAJykPKgahD4MQaHhUbn5heLxiSks6Zk5HpheRZIETMQEJWER8tHNreLtnQQ1yWkZ2e4dXT1l/TOj43UN2QCU7qghxMjs%2Bo6RCcihWADUdpEBncRMAJ6X2HaGAIKHx6eYF1fIGgT4qEezzerxCBRsZwAai0iMRvgARM5/dAgEA3e6XAJUWioJgEUhnBxAyIuUHg4BnACyeOIeE4CKR/1R6IeV2xuPxZ0UxNJIJe0K8JDOLBCtG8fDuEDQDD%2BVJpdMcADZhQTpbKBbClWcAG7rS684EJAjCpgJCDrC4Adl5Z1tcoItPpLDs1vkpAcpGi3Mt8P1wLtUJhQu1LqcbqJPr9rwDGqFcMuiJFYrwEogLFIuqjLwDPFpEioEAuDiJDgArFQi%2BW7KWAgxHB6zsRq05DNX4QSm6Ww22znqScCXfD9JtaAZSyYIvp5CZUBxuCw%2BJhBMJSAQDMZNhAkGgsLhCCRyJQaPRmGwQFQQgwhjLlyIxBJpLJ2EoVBJNDo9EYTOYPVYbChXFcdxME8bxfAgfx5giUtSxiBh0BWSZMnkQwKgKMDimCXoQBgtCqgYRD6imFDgNAtpZm6LCylwwYMJGLpCLWEi/lGKCcNgliGISCYiOQwxNg0bZdn2d4r0%2Bb5rmIW5WSeV5RJOEJzkxX5/h8IE5LJBIKVjeNIkRZFmSkjE2RxPECSJSInn7TSIWpB06QZAy0SM1ksVMzluUsrMBwcI4KywGhEnQCAAH0Qs4AAORUQsVRQwr1V4wrxezUhCAhMDCqBZmATACBCk5xEwDQIHrAKmFFAh61IetOmQBAEzQYhMBLD0at2eq9IALwYbUMha9YBp8yIQK0YEkoIFK0oykKss6HK8oKxJivrDReqqlbepa6rizKir6wGhK3l8/w8CoYEdOFCqU1oSU1WNOzHS1dMzjuwNBSbBxlV1K0bTtC6m2s7M7U7FsewTHVm1bUtEQAKmFSGwecCGu3kHs4edLsiWhrMAxB1HoYZEMuyh2H4ZRxGnGR7sCfR5tIjbHHgdynYGEbbzI1eYdLDHCd1xnc9L2vDRb1XPnN23DAcHwWFD2oOhGFYdgAmpABrTB4j%2BYWCE4fF7ykGQ5BfPX310PmzBAaI/1sFgmDV0iYSKPx4LYxRojibjVimS08Iwl3ojydCikYr37evejKNKCJXdDuiKODzJvc4iPsOjpP45AS0BKEvYDGQG21ZClgEjwEUWBCpqAEcQjwJrgqhbAACVJAASQAeSSM5In4BxeyGpFcsLZWXgAaWwEKAgADQnkKADFYheABxSQQob7BYmwF5JDH5ukmbgAVIsHAAWht9qE06FhtQio%2BmH2vutAIQfKRHsfJ%2BnufF%2BX1f1837fd4P%2BsJ9aodXhBfK%2BN876vFzKgUwMJCxcF4PQXurwmDoHQCFLgLQ0pMFSPQeB85FxnAQQuAQQgeDIJeKg9BtA8CpFuMQSUZwLxXgwhoM4kg94vD3s3AITDBasNvBQ7KuUQo0IYCrURtD6F4CKvgxBXxmFC17FzUc%2BhxykEnMYUgs5la23VngTW/Btb4jXF%2BcWIAHSYEwLLPOeiXjEGABoAwR94RD1HiFJwahm6xHhCFPeABNbQVl4RNXoEwLQJg0ALnlsQWI1hgAhCYDlZuKJ7DOCAsgMERAWCtzSjwNKM95annYMQxcoh5ZONgJgaWJAUkWGPJgOpboGnFLnPIkWoB9AmAMc3MSilqlmwMdSBIkhs77GnOQDQrceCMDNlbOpXTNzVP3MQOpHoGlrPKSeRWAsWFFGFmQ0gnTukaF6QpLAKIvyTOGQwUZOwc5ThOdM2ZVz5mXK5hBGpqyUTRA2T8rZCszy6LVhrAgWsdZHIMCcs5nxLlaKGaaW5YzBlTJmZokwbyoUDUmcCnQxAYEwjNuYN0iQADuhT6B1MUCOHmGizazn0HvJqXxDgTNMRuTYCBMCoKmOaUgKsFCGEMPwIVoqxVistgYRQJgWAgEUKWfgipFSRFLIYKKpZixZFLCqulVyGUmCcW6dlHyYBQFNVuFAqBon0DIBQKUVqeAxOcpfa%2BJx4nyAiiRY86ViBOIgKkM2qQEidDuAYCZQbmAMNbqkWBXgw2RKtWwCQrcGA3TNlgVKwBri0FoE4x5pAsA2xsHIK5%2BAmqtF6nmrRmDMnpXjeQCQIE5lSJDUELAZt7Kyvzb1YgqR8iYHhJgItwAxGdI3KIKwjjIQyNJc8ycEy9aPkNsoY2WhTZXOJZYeJAF0nOEsLQypfLUA8FYc41ukQzgzh7bSLAh6BIgQduBSCVEIgOGUO7WoSELAB3wmxN9Psg4ey/W6Wi5FWIvpAP%2B0Dww45Ad4hYJOf7lBpzg0xTYljnw0rUbzPVBgzhgOvkwF6Vszgev4PIEVZwIBMqsUWSI8h1gmGNdirlPLMh8oFaq7m%2BhpWkFlShVC6LtFQvcCAVCzHSBwFgBLa1GQbEOqdW6mwHqvV0B9X6gNVyI0hvrdpqNMbCX5qiUmggKa02lswJm7Nub62FviSWrRZaHaVrNjWqa9ajRNteS2hhbb9haM7fWntfatCDuHaOsWE6kkaGnZgWdaL62LoNs%2BFdqgTafi0T%2BLd/40kuD3TQ1Id7tEnv2WeyIV6Mg3qKvAe9ZEn3Owg2WOCCFUPEX9pUX2jXYI/owunRY0HbkUT/RxB9YdYOfvg/1obXWlhcQm0xSI6HmUKCw%2BooTDKziRUVEfWKxH4mkYiuRyj1HmV0YY0xsWnLuVYHY5sTjqFVG8f40K3VWj9WifE5d7jDgZU4UUPwSIkRYpZH6IoS0lpDCKCVYqV7/MumizMVh8rsPhPw%2BY5sHtBRfCKCAA%3D) to ARM and it does not generate any assembly. I'm not sure if I'm messing something up or not.

Looks like a godbolt bug to me.

**Comment by jroelofs** [comment]
reported here: https://github.com/compiler-explorer/compiler-explorer/discussions/2763#discussioncomment-9830228

**Comment by lawben** [comment]
> What version of the toolchain? FMV and ifunc support would only be in the developer beta we shipped last week, or in an open source toolchain you've built yourself.

I'm running LLVM 18.1.4 installed via brew (`Homebrew clang version 18.1.4 | Target: arm64-apple-darwin21.6.0`). From the godbolt examples and the issue dates, it looks like this is available in Clang/LLVM 18. I'm not sure which developer beta you are referring to in this case. Were there recent changes that affect this? If so, I'll try to build the current trunk. 

I'll try to create a MWE for my use case and see what the exact issue is, as it involves templates and explicit instantiation etc.  There is a non-zero chance that I'm simply messing something up in the process.

**Comment by jroelofs** [comment]
> I'm not sure which developer beta you are referring to in this case

The toolchain in the Xcode 16 beta has support for FMV and ifuncs, Xcode 15 does not.

https://download.developer.apple.com/Developer_Tools/Xcode_16_beta/Xcode_16_beta.xip

**Comment by lawben** [comment]
I've figured out that I can get the exported symbol on my Macbook if I manually set the target to `aarch64-unknown-linux-gnu` (I guess the `gnu` suffix is important here for the `ifunc` logic). But then everything else breaks. I guess I'll just wait for Xcode 16. Thanks for the info!

**Comment by jroelofs** [comment]
> I guess the gnu suffix is important here for the ifunc logic

Before https://github.com/llvm/llvm-project/pull/73686, only ELF targets supported it.
