### ISSUE TITLE
clang-include-cleaner - replaces chrono with bit/chrono

### ISSUE THREAD

**Issue by PiotrZSL** [llvm/llvm-project#68213]
Issues found:

a) 
```
+#include <bits/basic_string.h>
+#include <string>
```
b) 
```
-#include <chrono>
+#include <bits/chrono.h>
```
Tested version from LLVM 17.0.2

misc-include-cleaner provide more information:
```
160   - DiagnosticName:  misc-include-cleaner
161     DiagnosticMessage:
162       Message:         'no header providing "std::operator""s" is directly included'
163       FilePath:        'some-file.cpp'
164       FileOffset:      982
165       Replacements:
166         - FilePath:        'some-file.cpp'
167           Offset:          52
168           Length:          0
169           ReplacementText: "#include <bits/basic_string.h>\n"
```

And:
```
304   - DiagnosticName:  misc-include-cleaner
305     DiagnosticMessage:
306       Message:         'no header providing "std::chrono::ceil" is directly included'
307       FilePath:        'some-file.cpp'
308       FileOffset:      3133
309       Replacements:
310         - FilePath:        'some-file.cpp'
311           Offset:          43
312           Length:          0
313           ReplacementText: "#include <bits/chrono.h>\n"
```

When `<chrono>` is already included.

**Comment by ZedThree** [comment]
I've just bumped into this with `std::string_literals::operator""s`, I get a warning that 

> no header providing "std::operator""s" is directly included

which can only be silenced by including `bits/basic_string.h`. It would be nice to teach `misc-include-cleaner` about these implementation details.

Here's a minimal reproducer on Compiler Explorer:

https://godbolt.org/z/r9Tzrs4nx

**Comment by kaimast** [comment]
> I've just bumped into this with `std::string_literals::operator""s`, I get a warning that

I still see this error a year later.

**Comment by andrea-cassioli-maersk** [comment]
same issue here, quite annoying

**Comment by kadircet** [comment]
the one for `std::chrono::ceil` should be fixed with https://github.com/llvm/llvm-project/commit/c0ce44e8fc03882641f270539265b20dba0fffdd.

the one with UDLs is because we don't have support for that in stdlib-recognizer in https://github.com/llvm/llvm-project/blob/main/clang/lib/Tooling/Inclusions/Stdlib/StandardLibrary.cpp#L276. i think this is something that we can improve, if anyone is willing to contribute some patches

**Comment by andrea-cassioli-maersk** [comment]
@kadircet unfortunately I would not know where to start to contribute to the code...

**Comment by LindaSummer** [comment]
Hi @kadircet ,

I'm a newbie of llvm and want to make some contribution.

Could it be assigned to me? I'll try my best to fix it. 😊

Best Regards,
Edward

**Comment by PatrickKa** [comment]
I'm using LLVM 20 and still have this issue with string and chrono literals suggesting the inclusion of `<bits/basic_string.h>` and `<bits/chrono.h>` instead of the normal standard library headers. The following issues deal with basically the same problem: #98122, https://github.com/clangd/clangd/issues/1761, https://github.com/clangd/clangd/issues/1756. Is there any plan to work on this in the near future?

Since I am afraid the answer to my question is "no", does anyone have a workaround? Adding `.*bits.*` to the `IgnoreHeader` configuration does not help. According to [the docs](https://clangd.llvm.org/guides/include-cleaner#iwyu-pragmas), [`IWYU pragma: no include`](https://github.com/include-what-you-use/include-what-you-use/blob/master/docs/IWYUPragmas.md#iwyu-pragma-no_include) is not supported by the include cleaner. The issue about supporting mapping files (https://github.com/clangd/clangd/issues/1276) is open since 2022 and doesn't seem to be actively worked on either.

**Comment by gg-sr** [comment]
I'm a bit late to the party, but adding `misc-include-cleaner.IgnoreHeaders: bits/chrono.h` to `.clang-tidy`'s `CheckOptions` fixed it for me.

**Comment by israbbani** [comment]
> I'm using LLVM 20 and still have this issue with string and chrono literals suggesting the inclusion of `<bits/basic_string.h>` and `<bits/chrono.h>` instead of the normal standard library headers. The following issues deal with basically the same problem: [#98122](https://github.com/llvm/llvm-project/issues/98122), [clangd/clangd#1761](https://github.com/clangd/clangd/issues/1761), [clangd/clangd#1756](https://github.com/clangd/clangd/issues/1756). Is there any plan to work on this in the near future?
> 
> Since I am afraid the answer to my question is "no", does anyone have a workaround? Adding `.*bits.*` to the `IgnoreHeader` configuration does not help. According to [the docs](https://clangd.llvm.org/guides/include-cleaner#iwyu-pragmas), [`IWYU pragma: no include`](https://github.com/include-what-you-use/include-what-you-use/blob/master/docs/IWYUPragmas.md#iwyu-pragma-no_include) is not supported by the include cleaner. The issue about supporting mapping files ([clangd/clangd#1276](https://github.com/clangd/clangd/issues/1276)) is open since 2022 and doesn't seem to be actively worked on either.

+1 to this. If no one wants to do this, I can try to help out.
