### ISSUE TITLE
clang-format Leave option for AlignTrailingComments is broken

### ISSUE THREAD

**Issue by ChristophStrehle** [llvm/llvm-project#75035]
looks like the Leave option for AlignTrailingComments is broken in clang-format 17.0.6 when using tabs for indentation.

When formatting the following code:
```
namespace mynamespace {
// My struct
struct MyStruct final {
	constexpr int NoError{0};		//!< Successfully
	constexpr int Error{1};		//!< Error
};
} // namespace mynamespace
```
with this command line:
`clang-format -style="{Language: Cpp, UseTab: Always, IndentWidth: 4, TabWidth: 4, AlignTrailingComments: {Kind: Leave}}"`
I get the following output after the first run:
```
namespace mynamespace {
 // My struct
struct MyStruct final {
	constexpr int NoError{0};  //!< Successfully
	constexpr int Error{1};	//!< Error
};
} // namespace mynamespace
```
That means that clang-format will change the indentation of the trailing comments by replacing the tabs with spaces.

Even worse then the trailing comments is that clang-format will insert a space in front of the comment `// My struct` in the first run. In a second run clang-format will insert a second space, then a third space, then a tab and then two spaces again.

**Comment by MartinsSmirnovs** [comment]
Many `AlignTrailingComments: Leave` bugs (#59203, #59635, #67116, #71825) were actually fixed in `clang-format-18`. Try it instead.

**Comment by ChristophStrehle** [comment]
Hello MartinsSmirnovs,

Thanks for your replay. I tried this again with the commit 970152bec1ca2e9a924fb8dc92d098bd110b4dae from the main branch and indeed the `// My struct` comment is not indented as expected. However the trailing comments are still not left as they are and now I get an unexpected indentation with a comment that precedes a variable.

For example the following:
```
namespace mynamespace {
// My struct
struct MyStruct final {
	constexpr int NoError{0};	//!< Successfully
	constexpr int Error{1};		//!< Error

 	//! comment
	static constexpr int test{1};
};
} // namespace mynamespace
```
will look like this after the second run:
```
namespace mynamespace {
// My struct
struct MyStruct final {
	constexpr int NoError{0}; //!< Successfully
	constexpr int Error{1}; //!< Error

 //! comment
	static constexpr int test{1};
};
} // namespace mynamespace
```
So the comment for `test` is not aligned with the variable any more.

**Comment by MartinsSmirnovs** [comment]
Tried this. You are right. The formatter has yet another bug with `AlignTrailingComments: {Kind: Leave}}`.

**Comment by bastian2001** [comment]
Hi, are there any updates on this?

**Comment by EtienneBasilik** [comment]
Will this be fixed soon?

I think this bug is also resulting in bad alignment of Doxygen comments for function headers. The following:
```
/**************************************************************************/ /**
* @details Function description.
*
* @param   [out]  param1          Parameter 1
* @param   [in]   param2          Parameter 2
*
* @return Return value
*****************************************************************************/
```

is formatted as follows when ColumnLimit is set to 150:
```
/**************************************************************************/ /**
                                                                              * @details Function description.
                                                                              *
                                                                              * @param   [out]  param1          Parameter 1
                                                                              * @param   [in]   param2          Parameter 2
                                                                              *
                                                                              * @return Return value
                                                                              *****************************************************************************/
```
